-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_ProcessTableOp1.vhd
-- Created: 2025-10-22 15:46:40
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_ProcessTableOp1
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Subsystem Reference2/ProcessTableOp1
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_ProcessTableOp1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        tableEntryIn_num                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableEntryIn_staticReads          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntryIn_currentReads         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntryIn_epoch                :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntryIn_isConstant           :   IN    std_logic;
        tableEntryIn_isState              :   IN    std_logic;
        tableOp_stackNum                  :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_num                       :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableOp_cmd                       :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        tableOp_staticReads               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_epoch                     :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_isConstant                :   IN    std_logic;
        tableOpValid                      :   IN    std_logic;
        frameCount                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        tableEntry_num                    :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableEntry_staticReads            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntry_currentReads           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntry_epoch                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableEntry_isConstant             :   OUT   std_logic;
        tableEntry_isState                :   OUT   std_logic;
        hasRsp                            :   OUT   std_logic;
        isModified                        :   OUT   std_logic;
        tableRsp_stackNum                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableRsp_value                    :   OUT   std_logic;
        tableRsp_isError                  :   OUT   std_logic;
        isReady                           :   OUT   std_logic
        );
END MyProc_src_ProcessTableOp1;


ARCHITECTURE rtl OF MyProc_src_ProcessTableOp1 IS

  -- Component Declarations
  COMPONENT MyProc_src_MATLAB_Function_block43
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          tableEntryIn_num                :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          tableEntryIn_staticReads        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntryIn_currentReads       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntryIn_epoch              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntryIn_isConstant         :   IN    std_logic;
          tableEntryIn_isState            :   IN    std_logic;
          tableRspConst_stackNum          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableRspConst_value             :   IN    std_logic;
          tableRspConst_isError           :   IN    std_logic;
          tableOp_stackNum                :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableOp_num                     :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          tableOp_cmd                     :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
          tableOp_staticReads             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableOp_epoch                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tableOp_isConstant              :   IN    std_logic;
          tableOpValid                    :   IN    std_logic;
          frameCount                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          tableEntry_num                  :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          tableEntry_staticReads          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntry_currentReads         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntry_epoch                :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          tableEntry_isConstant           :   OUT   std_logic;
          tableEntry_isState              :   OUT   std_logic;
          tableRsp_stackNum               :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          tableRsp_value                  :   OUT   std_logic;
          tableRsp_isError                :   OUT   std_logic;
          hasRsp                          :   OUT   std_logic;
          isReady                         :   OUT   std_logic;
          isModified                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_MATLAB_Function_block43
    USE ENTITY work.MyProc_src_MATLAB_Function_block43(rtl);

  -- Signals
  SIGNAL Constant_out1_stackNum           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1_value              : std_logic;
  SIGNAL Constant_out1_isError            : std_logic;
  SIGNAL tableEntry_num_tmp               : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL tableEntry_staticReads_tmp       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL tableEntry_currentReads_tmp      : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL tableEntry_epoch_tmp             : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL tableRsp_stackNum_tmp            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL isReadydeadOutdeadOut            : std_logic;

BEGIN
  u_MATLAB_Function : MyProc_src_MATLAB_Function_block43
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              tableEntryIn_num => tableEntryIn_num,  -- ufix10
              tableEntryIn_staticReads => tableEntryIn_staticReads,  -- uint8
              tableEntryIn_currentReads => tableEntryIn_currentReads,  -- uint8
              tableEntryIn_epoch => tableEntryIn_epoch,  -- uint8
              tableEntryIn_isConstant => tableEntryIn_isConstant,
              tableEntryIn_isState => tableEntryIn_isState,
              tableRspConst_stackNum => std_logic_vector(Constant_out1_stackNum),  -- uint8
              tableRspConst_value => Constant_out1_value,
              tableRspConst_isError => Constant_out1_isError,
              tableOp_stackNum => tableOp_stackNum,  -- uint8
              tableOp_num => tableOp_num,  -- ufix10
              tableOp_cmd => tableOp_cmd,  -- enum type TableOpCmd (10 enums)
              tableOp_staticReads => tableOp_staticReads,  -- uint8
              tableOp_epoch => tableOp_epoch,  -- uint8
              tableOp_isConstant => tableOp_isConstant,
              tableOpValid => tableOpValid,
              frameCount => frameCount,  -- uint32
              tableEntry_num => tableEntry_num_tmp,  -- ufix10
              tableEntry_staticReads => tableEntry_staticReads_tmp,  -- uint8
              tableEntry_currentReads => tableEntry_currentReads_tmp,  -- uint8
              tableEntry_epoch => tableEntry_epoch_tmp,  -- uint8
              tableEntry_isConstant => tableEntry_isConstant,
              tableEntry_isState => tableEntry_isState,
              tableRsp_stackNum => tableRsp_stackNum_tmp,  -- uint8
              tableRsp_value => tableRsp_value,
              tableRsp_isError => tableRsp_isError,
              hasRsp => hasRsp,
              isReady => isReadydeadOutdeadOut,
              isModified => isModified
              );

  Constant_out1_stackNum <= to_unsigned(16#00#, 8);

  Constant_out1_value <= '0';

  Constant_out1_isError <= '0';

  isReady <= '0';

  tableEntry_num <= tableEntry_num_tmp;

  tableEntry_staticReads <= tableEntry_staticReads_tmp;

  tableEntry_currentReads <= tableEntry_currentReads_tmp;

  tableEntry_epoch <= tableEntry_epoch_tmp;

  tableRsp_stackNum <= tableRsp_stackNum_tmp;

END rtl;

