-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DebugableRAM_block1.vhd
-- Created: 2025-10-22 15:46:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DebugableRAM_block1
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/OutputProcessor_T/OPsync/SyncedProcessorDynamicLCLoading/SyncHub/DebugableRAM
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_DebugableRAM_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        wr_din                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        wr_addr                           :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        wr_en                             :   IN    std_logic;
        rd_addr                           :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        CONV_DEBUGINTAG_debugEnable       :   IN    std_logic;
        CONV_DEBUGINTAG_debugSelect       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_DEBUGINTAG_resultValid       :   IN    std_logic;
        CONV_DEBUGINTAG_resultWrData      :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_DEBUGINTAG_resultWrAddr      :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        CONV_DEBUGINTAG_resultRdAddr      :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        CONV_DEBUGINTAG_resultRdEn        :   IN    std_logic;
        rd_dout                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        CONV_DEBUGOUTTAG_4_debugID        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_DEBUGOUTTAG_4_debugRdData    :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END MyProc_src_DebugableRAM_block1;


ARCHITECTURE rtl OF MyProc_src_DebugableRAM_block1 IS

  -- Component Declarations
  COMPONENT MyProc_src_DebugDecoder_block5
    PORT( debugIn_debugEnable             :   IN    std_logic;
          debugIn_debugSelect             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          debugIn_resultValid             :   IN    std_logic;
          debugIn_resultWrData            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          debugIn_resultWrAddr            :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          debugIn_resultRdAddr            :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          debugIn_resultRdEn              :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          wr_addr                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          id                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          debugBank                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          wr_din_out                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          wr_addr_out                     :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          wr_en_out                       :   OUT   std_logic;
          rd_addr_out                     :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
          );
  END COMPONENT;

  COMPONENT MyProc_src_Simple_Dual_Port_RAM_by_Depth_block5
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          wr_addr                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          rd_dout                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT MyProc_src_Delay3_block5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          alpharesultRdEn                 :   IN    std_logic;
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT MyProc_src_Delay4_block5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          alpharesultRdEn                 :   IN    std_logic;
          Out1                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT MyProc_src_Delay5_block5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          alpharesultRdEn                 :   IN    std_logic;
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT MyProc_src_DebugEncoder_block5
    PORT( id                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          data                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          debugBank                       :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          debugOut_debugID                :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          debugOut_debugRdData            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT MyProc_src_Delay2_block5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1_debugID                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          In1_debugRdData                 :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          alpharesultRdEn                 :   IN    std_logic;
          Out1_debugID                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Out1_debugRdData                :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_DebugDecoder_block5
    USE ENTITY work.MyProc_src_DebugDecoder_block5(rtl);

  FOR ALL : MyProc_src_Simple_Dual_Port_RAM_by_Depth_block5
    USE ENTITY work.MyProc_src_Simple_Dual_Port_RAM_by_Depth_block5(rtl);

  FOR ALL : MyProc_src_Delay3_block5
    USE ENTITY work.MyProc_src_Delay3_block5(rtl);

  FOR ALL : MyProc_src_Delay4_block5
    USE ENTITY work.MyProc_src_Delay4_block5(rtl);

  FOR ALL : MyProc_src_Delay5_block5
    USE ENTITY work.MyProc_src_Delay5_block5(rtl);

  FOR ALL : MyProc_src_DebugEncoder_block5
    USE ENTITY work.MyProc_src_DebugEncoder_block5(rtl);

  FOR ALL : MyProc_src_Delay2_block5
    USE ENTITY work.MyProc_src_Delay2_block5(rtl);

  -- Signals
  SIGNAL CONV_DEBUGINTAG_debugSelect_unsigned : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL debugEnable                      : std_logic;
  SIGNAL debugSelect                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL resultValid                      : std_logic;
  SIGNAL CONV_DEBUGINTAG_resultWrAddr_unsigned : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL CONV_DEBUGINTAG_resultRdAddr_unsigned : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL resultWrData                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL resultWrAddr                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL resultRdAddr                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL resultRdEn                       : std_logic;
  SIGNAL debugID                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL debugBank                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DebugDecoder_out3                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL DebugDecoder_out4                : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL DebugDecoder_out5                : std_logic;
  SIGNAL DebugDecoder_out6                : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL DebugDecoder_out4_unsigned       : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Delay10_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay11_out1                     : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL DebugDecoder_out6_unsigned       : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Delay12_out1                     : std_logic;
  SIGNAL Delay13_out1                     : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL debugRdData                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL resultRdEn_1                     : std_logic;
  SIGNAL Delay7_out1                      : std_logic;
  SIGNAL debugID_unsigned                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay8_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_delOut                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_ectrl                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_last_value                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay3_out1                      : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Delay4_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL debugBank_unsigned               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay9_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay1_delOut                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay1_ectrl                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay1_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay1_last_value                : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay5_out1                      : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DebugEncoder_out1_debugID        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL DebugEncoder_out1_debugRdData    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay2_out1_debugID              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay2_out1_debugRdData          : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_DebugDecoder : MyProc_src_DebugDecoder_block5
    PORT MAP( debugIn_debugEnable => debugEnable,
              debugIn_debugSelect => std_logic_vector(debugSelect),  -- uint32
              debugIn_resultValid => resultValid,
              debugIn_resultWrData => resultWrData,  -- single
              debugIn_resultWrAddr => std_logic_vector(resultWrAddr),  -- ufix15
              debugIn_resultRdAddr => std_logic_vector(resultRdAddr),  -- ufix15
              debugIn_resultRdEn => resultRdEn,
              wr_din => wr_din,  -- single
              wr_addr => wr_addr,  -- ufix13
              wr_en => wr_en,
              rd_addr => rd_addr,  -- ufix13
              id => debugID,  -- uint16
              debugBank => debugBank,  -- uint16
              wr_din_out => DebugDecoder_out3,  -- single
              wr_addr_out => DebugDecoder_out4,  -- ufix13
              wr_en_out => DebugDecoder_out5,
              rd_addr_out => DebugDecoder_out6  -- ufix13
              );

  u_Simple_Dual_Port_RAM_by_Depth : MyProc_src_Simple_Dual_Port_RAM_by_Depth_block5
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => Delay10_out1,  -- single
              wr_addr => std_logic_vector(Delay11_out1),  -- ufix13
              wr_en => Delay12_out1,
              rd_addr => std_logic_vector(Delay13_out1),  -- ufix13
              rd_dout => debugRdData  -- single
              );

  u_Delay3 : MyProc_src_Delay3_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Delay_out1),  -- uint16
              alpharesultRdEn => Delay7_out1,
              Out1 => Delay3_out1  -- uint16
              );

  u_Delay4 : MyProc_src_Delay4_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => debugRdData,  -- single
              alpharesultRdEn => Delay7_out1,
              Out1 => Delay4_out1  -- single
              );

  u_Delay5 : MyProc_src_Delay5_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Delay1_out1),  -- uint16
              alpharesultRdEn => Delay7_out1,
              Out1 => Delay5_out1  -- uint16
              );

  u_DebugEncoder : MyProc_src_DebugEncoder_block5
    PORT MAP( id => Delay3_out1,  -- uint16
              data => Delay4_out1,  -- single
              debugBank => Delay5_out1,  -- uint16
              debugOut_debugID => DebugEncoder_out1_debugID,  -- uint32
              debugOut_debugRdData => DebugEncoder_out1_debugRdData  -- single
              );

  u_Delay2 : MyProc_src_Delay2_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1_debugID => DebugEncoder_out1_debugID,  -- uint32
              In1_debugRdData => DebugEncoder_out1_debugRdData,  -- single
              alpharesultRdEn => Delay7_out1,
              Out1_debugID => Delay2_out1_debugID,  -- uint32
              Out1_debugRdData => Delay2_out1_debugRdData  -- single
              );

  CONV_DEBUGINTAG_debugSelect_unsigned <= unsigned(CONV_DEBUGINTAG_debugSelect);

  Delay6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      debugEnable <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        debugEnable <= CONV_DEBUGINTAG_debugEnable;
      END IF;
    END IF;
  END PROCESS Delay6_1_process;


  Delay6_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      debugSelect <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        debugSelect <= CONV_DEBUGINTAG_debugSelect_unsigned;
      END IF;
    END IF;
  END PROCESS Delay6_2_process;


  Delay6_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      resultValid <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        resultValid <= CONV_DEBUGINTAG_resultValid;
      END IF;
    END IF;
  END PROCESS Delay6_3_process;


  CONV_DEBUGINTAG_resultWrAddr_unsigned <= unsigned(CONV_DEBUGINTAG_resultWrAddr);

  CONV_DEBUGINTAG_resultRdAddr_unsigned <= unsigned(CONV_DEBUGINTAG_resultRdAddr);

  Delay6_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      resultWrData <= X"00000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        resultWrData <= CONV_DEBUGINTAG_resultWrData;
      END IF;
    END IF;
  END PROCESS Delay6_4_process;


  Delay6_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      resultWrAddr <= to_unsigned(16#0000#, 15);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        resultWrAddr <= CONV_DEBUGINTAG_resultWrAddr_unsigned;
      END IF;
    END IF;
  END PROCESS Delay6_5_process;


  Delay6_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      resultRdAddr <= to_unsigned(16#0000#, 15);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        resultRdAddr <= CONV_DEBUGINTAG_resultRdAddr_unsigned;
      END IF;
    END IF;
  END PROCESS Delay6_6_process;


  Delay6_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      resultRdEn <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        resultRdEn <= CONV_DEBUGINTAG_resultRdEn;
      END IF;
    END IF;
  END PROCESS Delay6_7_process;


  DebugDecoder_out4_unsigned <= unsigned(DebugDecoder_out4);

  Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay10_out1 <= X"00000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay10_out1 <= DebugDecoder_out3;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_out1 <= to_unsigned(16#0000#, 13);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_out1 <= DebugDecoder_out4_unsigned;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  DebugDecoder_out6_unsigned <= unsigned(DebugDecoder_out6);

  Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay12_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay12_out1 <= DebugDecoder_out5;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= to_unsigned(16#0000#, 13);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay13_out1 <= DebugDecoder_out6_unsigned;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  rd_dout <= debugRdData;

  resultRdEn_1 <= resultRdEn;

  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= resultRdEn_1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  debugID_unsigned <= unsigned(debugID);

  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= debugID_unsigned;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  
  Delay_ectrl <= Delay_delOut WHEN Delay7_out1 = '0' ELSE
      Delay8_out1;

  Delay_lowered_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_delOut <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_delOut <= Delay_ectrl;
      END IF;
    END IF;
  END PROCESS Delay_lowered_process;


  Delay_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_last_value <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_last_value <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay_bypass_process;


  
  Delay_out1 <= Delay_last_value WHEN Delay7_out1 = '0' ELSE
      Delay_delOut;

  debugBank_unsigned <= unsigned(debugBank);

  Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay9_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_out1 <= debugBank_unsigned;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  
  Delay1_ectrl <= Delay1_delOut WHEN Delay7_out1 = '0' ELSE
      Delay9_out1;

  Delay1_lowered_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_delOut <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_delOut <= Delay1_ectrl;
      END IF;
    END IF;
  END PROCESS Delay1_lowered_process;


  Delay1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_last_value <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_last_value <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay1_bypass_process;


  
  Delay1_out1 <= Delay1_last_value WHEN Delay7_out1 = '0' ELSE
      Delay1_delOut;

  CONV_DEBUGOUTTAG_4_debugRdData <= Delay2_out1_debugRdData;

  CONV_DEBUGOUTTAG_4_debugID <= Delay2_out1_debugID;

END rtl;

