-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_MATLAB_Function_block52.vhd
-- Created: 2025-10-22 15:46:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_MATLAB_Function_block52
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/MATLAB Function
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_MATLAB_Function_block52 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        start                             :   IN    std_logic;
        done                              :   IN    std_logic;
        rdVal                             :   OUT   std_logic
        );
END MyProc_src_MATLAB_Function_block52;


ARCHITECTURE rtl OF MyProc_src_MATLAB_Function_block52 IS

  -- Signals
  SIGNAL rdValid                          : std_logic;
  SIGNAL doneDelay                        : std_logic;
  SIGNAL rdValid_next                     : std_logic;
  SIGNAL doneDelay_next                   : std_logic;

BEGIN
  dnnfpgacnn4integrationbeta2_c3_MATLAB_Function_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdValid <= '0';
      doneDelay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdValid <= rdValid_next;
        doneDelay <= doneDelay_next;
      END IF;
    END IF;
  END PROCESS dnnfpgacnn4integrationbeta2_c3_MATLAB_Function_process;

  dnnfpgacnn4integrationbeta2_c3_MATLAB_Function_output : PROCESS (done, doneDelay, rdValid, start)
  BEGIN
    rdValid_next <= rdValid;
    IF start = '1' THEN 
      rdValid_next <= '1';
    ELSIF (done AND ( NOT doneDelay)) = '1' THEN 
      rdValid_next <= '0';
    END IF;
    doneDelay_next <= done;
    rdVal <= rdValid;
  END PROCESS dnnfpgacnn4integrationbeta2_c3_MATLAB_Function_output;


END rtl;

