-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_OutputLogic_block.vhd
-- Created: 2025-10-22 15:46:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_OutputLogic_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Subsystem/ConvController/OutputLogic
-- Hierarchy Level: 10
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_OutputLogic_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        count                             :   IN    vector_of_std_logic_vector7(0 TO 4);  -- ufix7 [5]
        nextCount                         :   IN    vector_of_std_logic_vector7(0 TO 4);  -- ufix7 [5]
        halfInputFeatureNum               :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        halfOutputFeatureNum              :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        origOpIterMinusOne                :   IN    vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        origOpIterMinusTwo                :   IN    vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        fullFeatureSize                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        fullColumnsSize                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        nextTileOffset                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        resultBaseAddrValid               :   OUT   std_logic;
        tileAddr                          :   OUT   vector_of_std_logic_vector7(0 TO 2);  -- ufix7 [3]
        resultBaseAddr                    :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        opBaseAddr                        :   OUT   vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        inputFeatureAddr                  :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        outputFeatureAddr                 :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        firstInputFeature                 :   OUT   std_logic;
        finalInputFeature                 :   OUT   std_logic;
        finalOutputFeatureTile            :   OUT   std_logic;
        unpoolIndexAddr                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END MyProc_src_OutputLogic_block;


ARCHITECTURE rtl OF MyProc_src_OutputLogic_block IS

  -- Constants
  CONSTANT b0                             : vector_of_unsigned2(0 TO 2) := 
    (to_unsigned(16#3#, 2), to_unsigned(16#3#, 2), to_unsigned(16#1#, 2));  -- ufix2 [3]

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL count_unsigned                   : vector_of_unsigned7(0 TO 4);  -- ufix7 [5]
  SIGNAL nextCount_unsigned               : vector_of_unsigned7(0 TO 4);  -- ufix7 [5]
  SIGNAL halfInputFeatureNum_unsigned     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL halfOutputFeatureNum_unsigned    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL origOpIterMinusOne_unsigned      : vector_of_unsigned8(0 TO 4);  -- uint8 [5]
  SIGNAL origOpIterMinusTwo_unsigned      : vector_of_unsigned8(0 TO 4);  -- uint8 [5]
  SIGNAL fullFeatureSize_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL fullColumnsSize_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL nextTileOffset_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL resultBaseAddrValiddeadOut       : std_logic;
  SIGNAL tileAddr_tmp                     : vector_of_unsigned7(0 TO 2);  -- ufix7 [3]
  SIGNAL resultBaseAddr_tmp               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL opBaseAddrdeadOut                : vector_of_unsigned8(0 TO 2);  -- uint8 [3]
  SIGNAL inputFeatureAddr_tmp             : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL outputFeatureAddr_tmp            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL finalOutputFeatureTiledeadOut    : std_logic;
  SIGNAL unpoolIndexAddr_tmp              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL multTerm1                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL multTerm2                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL multTerm3                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL useNextTileOffset                : std_logic;
  SIGNAL multTerm1_next                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL multTerm2_next                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL multTerm3_next                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL useNextTileOffset_next           : std_logic;
  SIGNAL opBaseAddr_1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL opBaseAddr_tmp                   : vector_of_unsigned8(0 TO 2);  -- uint8 [3]

BEGIN
  resultBaseAddrValid <= '0';

  outputgen5: FOR k IN 0 TO 4 GENERATE
    count_unsigned(k) <= unsigned(count(k));
  END GENERATE;

  outputgen4: FOR k IN 0 TO 4 GENERATE
    nextCount_unsigned(k) <= unsigned(nextCount(k));
  END GENERATE;

  halfInputFeatureNum_unsigned <= unsigned(halfInputFeatureNum);

  halfOutputFeatureNum_unsigned <= unsigned(halfOutputFeatureNum);

  outputgen3: FOR k IN 0 TO 4 GENERATE
    origOpIterMinusOne_unsigned(k) <= unsigned(origOpIterMinusOne(k));
  END GENERATE;

  outputgen2: FOR k IN 0 TO 4 GENERATE
    origOpIterMinusTwo_unsigned(k) <= unsigned(origOpIterMinusTwo(k));
  END GENERATE;

  fullFeatureSize_unsigned <= unsigned(fullFeatureSize);

  fullColumnsSize_unsigned <= unsigned(fullColumnsSize);

  nextTileOffset_unsigned <= unsigned(nextTileOffset);

  dnnfpgaConvcontroller2lib_c10_OutputLogic_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      multTerm1 <= to_unsigned(16#00000000#, 32);
      multTerm2 <= to_unsigned(16#00000000#, 32);
      multTerm3 <= to_unsigned(16#00000000#, 32);
      useNextTileOffset <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        multTerm1 <= multTerm1_next;
        multTerm2 <= multTerm2_next;
        multTerm3 <= multTerm3_next;
        useNextTileOffset <= useNextTileOffset_next;
      END IF;
    END IF;
  END PROCESS dnnfpgaConvcontroller2lib_c10_OutputLogic_process;

  dnnfpgaConvcontroller2lib_c10_OutputLogic_output : PROCESS (count_unsigned, fullColumnsSize_unsigned, fullFeatureSize_unsigned,
       halfInputFeatureNum_unsigned, halfOutputFeatureNum_unsigned, multTerm1,
       multTerm2, multTerm3, nextCount_unsigned, nextTileOffset_unsigned,
       origOpIterMinusOne_unsigned, origOpIterMinusTwo_unsigned,
       useNextTileOffset, valid)
    VARIABLE tileAddr1 : vector_of_unsigned7(0 TO 2);
    VARIABLE halfInputFeatureNumMinusOne : unsigned(7 DOWNTO 0);
    VARIABLE halfOutputFeatureNumMinusOne : unsigned(7 DOWNTO 0);
    VARIABLE halfInputFeatureNumMinusTwo : unsigned(7 DOWNTO 0);
    VARIABLE isCountFinalValue : std_logic;
    VARIABLE b : unsigned(31 DOWNTO 0);
    VARIABLE b_0 : unsigned(31 DOWNTO 0);
    VARIABLE add_cast : unsigned(2 DOWNTO 0);
    VARIABLE add_cast_0 : unsigned(2 DOWNTO 0);
    VARIABLE add_temp : unsigned(32 DOWNTO 0);
    VARIABLE add_cast_1 : unsigned(31 DOWNTO 0);
    VARIABLE add_cast_2 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(32 DOWNTO 0);
    VARIABLE mul_temp : unsigned(38 DOWNTO 0);
    VARIABLE mul_temp_0 : unsigned(13 DOWNTO 0);
    VARIABLE mul_temp_1 : unsigned(27 DOWNTO 0);
    VARIABLE mul_temp_2 : unsigned(38 DOWNTO 0);
    VARIABLE mul_temp_3 : vector_of_unsigned9(0 TO 2);
  BEGIN
    add_temp := to_unsigned(0, 33);
    add_temp_0 := to_unsigned(0, 33);
    add_cast_1 := to_unsigned(16#00000000#, 32);
    add_cast_2 := to_unsigned(0, 33);
    add_cast := to_unsigned(16#0#, 3);
    add_cast_0 := to_unsigned(16#0#, 3);
    useNextTileOffset_next <= useNextTileOffset;
    --Persistent variables
    tileAddr1(0) := to_unsigned(16#00#, 7);
    tileAddr1(1 TO 2) := count_unsigned(1 TO 2);
    -- bitwidth
    IF count_unsigned(0) = to_unsigned(16#00#, 7) THEN 
      IF count_unsigned(3)(6 DOWNTO 4) /= "000" THEN 
        inputFeatureAddr_tmp <= "1111";
      ELSE 
        inputFeatureAddr_tmp <= count_unsigned(3)(3 DOWNTO 0);
      END IF;
      IF count_unsigned(4)(6 DOWNTO 4) /= "000" THEN 
        outputFeatureAddr_tmp <= "1111";
      ELSE 
        outputFeatureAddr_tmp <= count_unsigned(4)(3 DOWNTO 0);
      END IF;
    ELSE 
      IF count_unsigned(3)(6 DOWNTO 3) /= "0000" THEN 
        add_cast := "111";
      ELSE 
        add_cast := count_unsigned(3)(2 DOWNTO 0);
      END IF;
      inputFeatureAddr_tmp <= resize(add_cast, 4) + resize(halfInputFeatureNum_unsigned, 4);
      IF count_unsigned(4)(6 DOWNTO 3) /= "0000" THEN 
        add_cast_0 := "111";
      ELSE 
        add_cast_0 := count_unsigned(4)(2 DOWNTO 0);
      END IF;
      outputFeatureAddr_tmp <= resize(add_cast_0, 4) + resize(halfOutputFeatureNum_unsigned, 4);
    END IF;
    halfInputFeatureNumMinusOne := origOpIterMinusOne_unsigned(3);
    halfOutputFeatureNumMinusOne := origOpIterMinusOne_unsigned(4);
    halfInputFeatureNumMinusTwo := origOpIterMinusTwo_unsigned(3);
    --     finalOutputFeatureTile = finalInputFeature && ...
    --         (count(ControlLogicTileXAddrIdx) == origOpIterMinusOne(ControlLogicTileXAddrIdx)) && ...
    --         (count(ControlLogicTileYAddrIdx) == origOpIterMinusTwo(ControlLogicTileYAddrIdx));
    finalOutputFeatureTiledeadOut <= hdlcoder_to_stdlogic(((resize(count_unsigned(1), 8) = origOpIterMinusOne_unsigned(1)) AND (resize(count_unsigned(2), 8) = origOpIterMinusOne_unsigned(2))) AND (((resize(count_unsigned(3), 8) = halfInputFeatureNumMinusOne) AND (resize(count_unsigned(4), 8) < halfOutputFeatureNumMinusOne)) OR ((resize(count_unsigned(3), 8) = halfInputFeatureNumMinusTwo) AND (resize(count_unsigned(4), 8) = halfOutputFeatureNumMinusOne))));
    --    %% Unpool Index Activations Address Calculation
    -- Constant
    -- UnpoolIndexAddr output calculation has been split into multiple
    -- cycles (two, in this case).
    -- 
    -- 1. The first cycle writes output from register and performs
    -- multiplication operation with current inputs afterwards. 
    -- 2. The second cycle adds these products and writes out valid output.
    --
    -- This delayed-output behaviour should be followed for the last tile
    -- too. But no computation or registers are used to assign LC input to
    -- output. In order to do this, we use a flag to mark that the LC input
    -- should be used for the ouput in the second clock cycle.
    IF useNextTileOffset = '1' THEN 
      -- During the last weight fetch for current tile, send the address
      -- to fetch index activations for next tile
      unpoolIndexAddr_tmp <= nextTileOffset_unsigned;
      useNextTileOffset_next <= '0';
    ELSE 
      -- something like... 
      -- 3*featureSize*tNum*singleBW + 2*wtLen*tNum*singleBW + 79*numCols*tNum*singleBW
      -- where ADDRESSSCALINGFACTOR = tNum*singleBW.
      -- *ADDRESSSCALINGFACTOR is precomputed for the LC params. 
      add_temp := resize(multTerm1, 33) + resize(multTerm2, 33);
      IF add_temp(32) /= '0' THEN 
        add_cast_1 := X"FFFFFFFF";
      ELSE 
        add_cast_1 := add_temp(31 DOWNTO 0);
      END IF;
      add_cast_2 := resize(add_cast_1, 33);
      add_temp_0 := add_cast_2 + resize(multTerm3, 33);
      IF add_temp_0(32) /= '0' THEN 
        unpoolIndexAddr_tmp <= X"FFFFFFFF";
      ELSE 
        unpoolIndexAddr_tmp <= add_temp_0(31 DOWNTO 0);
      END IF;
    END IF;
    -- Identify in the first clock cycle whether the LC param should be used
    -- as output in the second clock cycle instead of the sum of products.
    isCountFinalValue := hdlcoder_to_stdlogic(((((resize(count_unsigned(0), 8) = origOpIterMinusOne_unsigned(0)) AND (resize(count_unsigned(1), 8) = origOpIterMinusOne_unsigned(1))) AND (resize(count_unsigned(2), 8) = origOpIterMinusOne_unsigned(2))) AND (resize(count_unsigned(3), 8) = origOpIterMinusOne_unsigned(3))) AND (resize(count_unsigned(4), 8) = origOpIterMinusOne_unsigned(4)));
    IF isCountFinalValue = '1' THEN 
      useNextTileOffset_next <= '1';
    END IF;
    b := fullFeatureSize_unsigned;
    mul_temp := nextCount_unsigned(3) * b;
    IF mul_temp(38 DOWNTO 32) /= "0000000" THEN 
      multTerm1_next <= X"FFFFFFFF";
    ELSE 
      multTerm1_next <= mul_temp(31 DOWNTO 0);
    END IF;
    -- f-th feature in input
    mul_temp_0 := nextCount_unsigned(2) * to_unsigned(16#60#, 7);
    -- CSD Encoding (8192) : 10000000000000; Cost (Adders) = 0
    mul_temp_1 := resize(mul_temp_0 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);
    multTerm2_next <= (resize(mul_temp_1(27 DOWNTO 14), 32)) + ('0' & mul_temp_1(13));
    -- n-th weight read in a row 
    b_0 := fullColumnsSize_unsigned;
    mul_temp_2 := nextCount_unsigned(1) * b_0;
    IF mul_temp_2(38 DOWNTO 32) /= "0000000" THEN 
      multTerm3_next <= X"FFFFFFFF";
    ELSE 
      multTerm3_next <= mul_temp_2(31 DOWNTO 0);
    END IF;
    -- k-th row within a tile
    resultBaseAddrValiddeadOut <= valid;
    resultBaseAddr_tmp <= to_unsigned(16#00#, 8);

    FOR t_0 IN 0 TO 2 LOOP
      tileAddr_tmp(t_0) <= tileAddr1(t_0);
      mul_temp_3(t_0) := tileAddr1(t_0) * b0(t_0);
      IF mul_temp_3(t_0)(8) /= '0' THEN 
        opBaseAddrdeadOut(t_0) <= "11111111";
      ELSE 
        opBaseAddrdeadOut(t_0) <= mul_temp_3(t_0)(7 DOWNTO 0);
      END IF;
    END LOOP;

    IF count_unsigned(3) = to_unsigned(16#00#, 7) THEN 
      firstInputFeature <= '1';
    ELSE 
      firstInputFeature <= '0';
    END IF;
    IF resize(count_unsigned(3), 8) = halfInputFeatureNumMinusOne THEN 
      finalInputFeature <= '1';
    ELSE 
      finalInputFeature <= '0';
    END IF;
  END PROCESS dnnfpgaConvcontroller2lib_c10_OutputLogic_output;


  outputgen1: FOR k IN 0 TO 2 GENERATE
    tileAddr(k) <= std_logic_vector(tileAddr_tmp(k));
  END GENERATE;

  resultBaseAddr <= std_logic_vector(resultBaseAddr_tmp);

  opBaseAddr_1 <= to_unsigned(16#00#, 8);

  opBaseAddr_tmp(0) <= opBaseAddr_1;
  opBaseAddr_tmp(1) <= opBaseAddr_1;
  opBaseAddr_tmp(2) <= opBaseAddr_1;

  outputgen: FOR k IN 0 TO 2 GENERATE
    opBaseAddr(k) <= std_logic_vector(opBaseAddr_tmp(k));
  END GENERATE;

  inputFeatureAddr <= std_logic_vector(inputFeatureAddr_tmp);

  outputFeatureAddr <= std_logic_vector(outputFeatureAddr_tmp);

  finalOutputFeatureTile <= '0';

  unpoolIndexAddr <= std_logic_vector(unpoolIndexAddr_tmp);

END rtl;

