-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Rising_Edge_Debug_Log_Tap4_block1.vhd
-- Created: 2025-10-22 15:46:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Rising_Edge_Debug_Log_Tap4_block1
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/OutputProcessor_T/OPsync/Rising Edge Debug 
-- Log Tap
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Rising_Edge_Debug_Log_Tap4_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic;  -- ufix1
        Out1                              :   OUT   std_logic;  -- ufix1
        CONV_LOGTAPDEBUGOUTTAG_214_data   :   OUT   std_logic;
        CONV_LOGTAPDEBUGOUTTAG_214_valid  :   OUT   std_logic
        );
END MyProc_src_Rising_Edge_Debug_Log_Tap4_block1;


ARCHITECTURE rtl OF MyProc_src_Rising_Edge_Debug_Log_Tap4_block1 IS

  -- Component Declarations
  COMPONENT MyProc_src_EdgeDetection1_block29
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic;  -- ufix1
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MyProc_src_Debug_Log_Tap_block20
    PORT( data                            :   IN    std_logic;
          valid                           :   IN    std_logic;
          CONV_LOGTAPDEBUGOUTTAG_214_data :   OUT   std_logic;
          CONV_LOGTAPDEBUGOUTTAG_214_valid :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_EdgeDetection1_block29
    USE ENTITY work.MyProc_src_EdgeDetection1_block29(rtl);

  FOR ALL : MyProc_src_Debug_Log_Tap_block20
    USE ENTITY work.MyProc_src_Debug_Log_Tap_block20(rtl);

  -- Signals
  SIGNAL EdgeDetection1_out1              : std_logic;

BEGIN
  u_EdgeDetection1 : MyProc_src_EdgeDetection1_block29
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => In1,  -- ufix1
              Out1 => EdgeDetection1_out1
              );

  u_Debug_Log_Tap : MyProc_src_Debug_Log_Tap_block20
    PORT MAP( data => EdgeDetection1_out1,
              valid => EdgeDetection1_out1,
              CONV_LOGTAPDEBUGOUTTAG_214_data => CONV_LOGTAPDEBUGOUTTAG_214_data,
              CONV_LOGTAPDEBUGOUTTAG_214_valid => CONV_LOGTAPDEBUGOUTTAG_214_valid
              );

  Out1 <= In1;

END rtl;

