-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_ETD.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_ETD
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/StreamFIFO_DDRBurstControl/StreamingFIFO/AsymmetricFIFO/Dual 
-- Rate StreamingRAM/EnabledTappedDelay/ET
-- Hierarchy Level: 11
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_ETD IS
  PORT( In_rsvd                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        En                                :   IN    std_logic;
        Out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END MyProc_src_ETD;


ARCHITECTURE rtl OF MyProc_src_ETD IS

BEGIN
  Out_rsvd <= In_rsvd;

END rtl;

