-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_block17.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_block17
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/Subsystem
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem_block17 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        IMdone                            :   IN    std_logic;
        start                             :   IN    std_logic;
        validIn                           :   IN    std_logic;
        IPdone                            :   IN    std_logic;
        FCdone                            :   IN    std_logic;
        OPdone                            :   IN    std_logic;
        opImageCount                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        FCLayerDone                       :   IN    std_logic;
        canSendDone                       :   IN    std_logic;
        payloadValid                      :   IN    std_logic;
        payload_instrCount                :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        payload_srcAddr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_dstAddr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        RUNNING                           :   OUT   std_logic;
        IMstart                           :   OUT   std_logic;
        moveOn                            :   OUT   std_logic;
        readyOut                          :   OUT   std_logic;
        IPstart                           :   OUT   std_logic;
        OPstart                           :   OUT   std_logic;
        stateOut                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        doneOut                           :   OUT   std_logic;
        FCLayerRst                        :   OUT   std_logic;
        FCLayerStart                      :   OUT   std_logic;
        FCstart                           :   OUT   std_logic;
        IPvalid                           :   OUT   std_logic;
        OPDDRaddr                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        FCvalid                           :   OUT   std_logic;
        OPvalid                           :   OUT   std_logic;
        sendDone                          :   OUT   std_logic;
        payloadDeq                        :   OUT   std_logic;
        IPDDRaddr                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END MyProc_src_Subsystem_block17;


ARCHITECTURE rtl OF MyProc_src_Subsystem_block17 IS

  -- Component Declarations
  COMPONENT MyProc_src_FC_Scheduler
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          start                           :   IN    std_logic;
          validIn                         :   IN    std_logic;
          IMdone                          :   IN    std_logic;
          IPdone                          :   IN    std_logic;
          FCLayerDone                     :   IN    std_logic;
          FCdone                          :   IN    std_logic;
          OPdone                          :   IN    std_logic;
          opImageCount                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_instrCount              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          payload_srcAddr                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_dstAddr                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadValid                    :   IN    std_logic;
          canSendDone                     :   IN    std_logic;
          readyOut                        :   OUT   std_logic;
          IMstart                         :   OUT   std_logic;
          moveOn                          :   OUT   std_logic;
          IPstart                         :   OUT   std_logic;
          IPvalid                         :   OUT   std_logic;
          FCstart                         :   OUT   std_logic;
          FCLayerStart                    :   OUT   std_logic;
          FCLayerRst                      :   OUT   std_logic;
          FCvalid                         :   OUT   std_logic;
          IPDDRaddr                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          OPstart                         :   OUT   std_logic;
          OPvalid                         :   OUT   std_logic;
          OPDDRaddr                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          stateOut                        :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          doneOut                         :   OUT   std_logic;
          payloadDeq                      :   OUT   std_logic;
          sendDone                        :   OUT   std_logic;
          RUNNING                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_FC_Scheduler
    USE ENTITY work.MyProc_src_FC_Scheduler(rtl);

  -- Signals
  SIGNAL readyOutdeadOutdeadOut           : std_logic;
  SIGNAL IPvaliddeadOutdeadOut            : std_logic;
  SIGNAL IPDDRaddr_tmp                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL OPDDRaddr_tmp                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL stateOutdeadOutdeadOut           : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL doneOutdeadOutdeadOut            : std_logic;
  SIGNAL RUNNINGdeadOutdeadOut            : std_logic;
  SIGNAL stateOut_tmp                     : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  u_FC_Scheduler : MyProc_src_FC_Scheduler
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              start => start,
              validIn => validIn,
              IMdone => IMdone,
              IPdone => IPdone,
              FCLayerDone => FCLayerDone,
              FCdone => FCdone,
              OPdone => OPdone,
              opImageCount => opImageCount,  -- uint32
              payload_instrCount => payload_instrCount,  -- uint16
              payload_srcAddr => payload_srcAddr,  -- uint32
              payload_dstAddr => payload_dstAddr,  -- uint32
              payloadValid => payloadValid,
              canSendDone => canSendDone,
              readyOut => readyOutdeadOutdeadOut,
              IMstart => IMstart,
              moveOn => moveOn,
              IPstart => IPstart,
              IPvalid => IPvaliddeadOutdeadOut,
              FCstart => FCstart,
              FCLayerStart => FCLayerStart,
              FCLayerRst => FCLayerRst,
              FCvalid => FCvalid,
              IPDDRaddr => IPDDRaddr_tmp,  -- uint32
              OPstart => OPstart,
              OPvalid => OPvalid,
              OPDDRaddr => OPDDRaddr_tmp,  -- uint32
              stateOut => stateOutdeadOutdeadOut,  -- ufix4
              doneOut => doneOutdeadOutdeadOut,
              payloadDeq => payloadDeq,
              sendDone => sendDone,
              RUNNING => RUNNINGdeadOutdeadOut
              );

  RUNNING <= '0';

  readyOut <= '0';

  stateOut_tmp <= to_unsigned(16#0#, 4);

  stateOut <= std_logic_vector(stateOut_tmp);

  doneOut <= '0';

  IPvalid <= '0';

  OPDDRaddr <= OPDDRaddr_tmp;

  IPDDRaddr <= IPDDRaddr_tmp;

END rtl;

