-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DebugDecoder_block3.vhd
-- Created: 2025-10-22 15:46:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DebugDecoder_block3
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/DataMemMask/DataMem/Result Mem/DebugDecoder
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_DebugDecoder_block3 IS
  PORT( debugIn_debugEnable               :   IN    std_logic;
        debugIn_debugSelect               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        debugIn_resultValid               :   IN    std_logic;
        debugIn_resultWrData              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        debugIn_resultWrAddr              :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        debugIn_resultRdAddr              :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        debugIn_resultRdEn                :   IN    std_logic;
        wr_din                            :   IN    vector_of_std_logic_vector32(0 TO 17);  -- int32 [18]
        wr_addr                           :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
        wr_en                             :   IN    std_logic_vector(17 DOWNTO 0);  -- boolean [18]
        rd_addr                           :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
        id                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        debugBank                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        wr_din_out                        :   OUT   vector_of_std_logic_vector32(0 TO 17);  -- int32 [18]
        wr_addr_out                       :   OUT   vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
        wr_en_out                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- boolean [18]
        rd_addr_out                       :   OUT   vector_of_std_logic_vector6(0 TO 17)  -- ufix6 [18]
        );
END MyProc_src_DebugDecoder_block3;


ARCHITECTURE rtl OF MyProc_src_DebugDecoder_block3 IS

  -- Component Declarations
  COMPONENT MyProc_src_EnLogic_block3
    PORT( debugEnable                     :   IN    std_logic;
          debugSelection                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          debugValid                      :   IN    std_logic;
          de                              :   OUT   std_logic;
          id                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          we                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          debugBank                       :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT MyProc_src_Scalar_Replicator_block6
    PORT( In_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          Out_rsvd                        :   OUT   vector_of_std_logic_vector8(0 TO 17)  -- int8 [18]
          );
  END COMPONENT;

  COMPONENT MyProc_src_Scalar_Replicator1_block8
    PORT( In_rsvd                         :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          Out_rsvd                        :   OUT   vector_of_std_logic_vector15(0 TO 17)  -- ufix15 [18]
          );
  END COMPONENT;

  COMPONENT MyProc_src_Scalar_Replicator2_block4
    PORT( In_rsvd                         :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          Out_rsvd                        :   OUT   vector_of_std_logic_vector15(0 TO 17)  -- ufix15 [18]
          );
  END COMPONENT;

  COMPONENT MyProc_src_Subsystem_block25
    PORT( In1                             :   IN    std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          In2                             :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
          In3                             :   IN    vector_of_std_logic_vector15(0 TO 17);  -- ufix15 [18]
          In4                             :   IN    vector_of_std_logic_vector15(0 TO 17);  -- ufix15 [18]
          Out1                            :   OUT   vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
          Out2                            :   OUT   vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          Out3                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          Out4                            :   OUT   vector_of_std_logic_vector6(0 TO 17)  -- ufix6 [18]
          );
  END COMPONENT;

  COMPONENT MyProc_src_switch_block3
    PORT( In1                             :   IN    std_logic;
          In2                             :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
          In3                             :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          In4                             :   IN    std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          In5                             :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          In6                             :   IN    vector_of_std_logic_vector32(0 TO 17);  -- int32 [18]
          In7                             :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          In8                             :   IN    std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          In9                             :   IN    vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          Out1                            :   OUT   vector_of_std_logic_vector32(0 TO 17);  -- int32 [18]
          Out2                            :   OUT   vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
          Out3                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- boolean [18]
          Out4                            :   OUT   vector_of_std_logic_vector6(0 TO 17)  -- ufix6 [18]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_EnLogic_block3
    USE ENTITY work.MyProc_src_EnLogic_block3(rtl);

  FOR ALL : MyProc_src_Scalar_Replicator_block6
    USE ENTITY work.MyProc_src_Scalar_Replicator_block6(rtl);

  FOR ALL : MyProc_src_Scalar_Replicator1_block8
    USE ENTITY work.MyProc_src_Scalar_Replicator1_block8(rtl);

  FOR ALL : MyProc_src_Scalar_Replicator2_block4
    USE ENTITY work.MyProc_src_Scalar_Replicator2_block4(rtl);

  FOR ALL : MyProc_src_Subsystem_block25
    USE ENTITY work.MyProc_src_Subsystem_block25(rtl);

  FOR ALL : MyProc_src_switch_block3
    USE ENTITY work.MyProc_src_switch_block3(rtl);

  -- Signals
  SIGNAL debugEnable                      : std_logic;
  SIGNAL debugSelect                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL debugSelect_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL resultValid                      : std_logic;
  SIGNAL de                               : std_logic;
  SIGNAL id_tmp                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL we                               : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL debugBank_tmp                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL resultWrData                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL resultWrData_1                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Scalar_Replicator_out1           : vector_of_std_logic_vector8(0 TO 17);  -- ufix8 [18]
  SIGNAL resultWrAddr                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL resultWrAddr_1                   : std_logic_vector(14 DOWNTO 0);  -- ufix15
  SIGNAL Scalar_Replicator1_out1          : vector_of_std_logic_vector15(0 TO 17);  -- ufix15 [18]
  SIGNAL resultRdAddr                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL resultRdAddr_1                   : std_logic_vector(14 DOWNTO 0);  -- ufix15
  SIGNAL Scalar_Replicator2_out1          : vector_of_std_logic_vector15(0 TO 17);  -- ufix15 [18]
  SIGNAL wr_din_1                         : vector_of_std_logic_vector8(0 TO 17);  -- ufix8 [18]
  SIGNAL wr_addr_1                        : vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
  SIGNAL wr_en_1                          : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL rd_addr_1                        : vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
  SIGNAL switch_out1                      : vector_of_std_logic_vector32(0 TO 17);  -- ufix32 [18]
  SIGNAL switch_out2                      : vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]
  SIGNAL switch_out3                      : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL switch_out4                      : vector_of_std_logic_vector6(0 TO 17);  -- ufix6 [18]

BEGIN
  u_EnLogic : MyProc_src_EnLogic_block3
    PORT MAP( debugEnable => debugEnable,
              debugSelection => debugSelect_1,  -- uint32
              debugValid => resultValid,
              de => de,
              id => id_tmp,  -- uint16
              we => we,  -- boolean [18]
              debugBank => debugBank_tmp  -- uint16
              );

  u_Scalar_Replicator : MyProc_src_Scalar_Replicator_block6
    PORT MAP( In_rsvd => resultWrData_1,  -- int8
              Out_rsvd => Scalar_Replicator_out1  -- int8 [18]
              );

  u_Scalar_Replicator1 : MyProc_src_Scalar_Replicator1_block8
    PORT MAP( In_rsvd => resultWrAddr_1,  -- ufix15
              Out_rsvd => Scalar_Replicator1_out1  -- ufix15 [18]
              );

  u_Scalar_Replicator2 : MyProc_src_Scalar_Replicator2_block4
    PORT MAP( In_rsvd => resultRdAddr_1,  -- ufix15
              Out_rsvd => Scalar_Replicator2_out1  -- ufix15 [18]
              );

  u_Subsystem : MyProc_src_Subsystem_block25
    PORT MAP( In1 => we,  -- boolean [18]
              In2 => Scalar_Replicator_out1,  -- int8 [18]
              In3 => Scalar_Replicator1_out1,  -- ufix15 [18]
              In4 => Scalar_Replicator2_out1,  -- ufix15 [18]
              Out1 => wr_din_1,  -- int8 [18]
              Out2 => wr_addr_1,  -- ufix6 [18]
              Out3 => wr_en_1,  -- boolean [18]
              Out4 => rd_addr_1  -- ufix6 [18]
              );

  u_switch : MyProc_src_switch_block3
    PORT MAP( In1 => de,
              In2 => wr_din_1,  -- int8 [18]
              In3 => wr_addr_1,  -- ufix6 [18]
              In4 => wr_en_1,  -- boolean [18]
              In5 => rd_addr_1,  -- ufix6 [18]
              In6 => wr_din,  -- int32 [18]
              In7 => wr_addr,  -- ufix6 [18]
              In8 => wr_en,  -- boolean [18]
              In9 => rd_addr,  -- ufix6 [18]
              Out1 => switch_out1,  -- int32 [18]
              Out2 => switch_out2,  -- ufix6 [18]
              Out3 => switch_out3,  -- boolean [18]
              Out4 => switch_out4  -- ufix6 [18]
              );

  debugEnable <= debugIn_debugEnable;

  debugSelect <= unsigned(debugIn_debugSelect);

  debugSelect_1 <= std_logic_vector(debugSelect);

  resultValid <= debugIn_resultValid;

  resultWrData <= signed(debugIn_resultWrData);

  resultWrData_1 <= std_logic_vector(resultWrData);

  resultWrAddr <= unsigned(debugIn_resultWrAddr);

  resultWrAddr_1 <= std_logic_vector(resultWrAddr);

  resultRdAddr <= unsigned(debugIn_resultRdAddr);

  resultRdAddr_1 <= std_logic_vector(resultRdAddr);

  wr_en_out <= switch_out3;

  id <= id_tmp;

  debugBank <= debugBank_tmp;

  wr_din_out <= switch_out1;

  wr_addr_out <= switch_out2;

  rd_addr_out <= switch_out4;

END rtl;

