-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_zWeAdapter.vhd
-- Created: 2025-10-22 15:46:42
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_zWeAdapter
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/DataMemSingleCycleAccumulator/zAddapter/zWeAdapter
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_zWeAdapter IS
  PORT( weIn                              :   IN    std_logic;
        zSelIn                            :   IN    std_logic;  -- ufix1
        active                            :   IN    std_logic;
        weOut                             :   OUT   std_logic_vector(3 DOWNTO 0)  -- boolean [4]
        );
END MyProc_src_zWeAdapter;


ARCHITECTURE rtl OF MyProc_src_zWeAdapter IS

BEGIN
  dnnfpgaDatamemlibZAdapterslib_c1_sM6EPvzJ6MJ8XQq8QSyGtpE_zWeAda_output : PROCESS (active, weIn, zSelIn)
    VARIABLE weOutT : std_logic_vector(3 DOWNTO 0);
  BEGIN

    FOR t_0 IN 0 TO 3 LOOP
      weOutT(t_0) := '0';
    END LOOP;

    IF active = '1' THEN 
      IF zSelIn /= '0' THEN 
        FOR t_3 IN 0 TO 1 LOOP
          weOutT(t_3) := '0';
          weOutT(2 + t_3) := weIn;
        END LOOP;
      ELSE 
        FOR t_2 IN 0 TO 1 LOOP
          weOutT(t_2) := weIn;
          weOutT(2 + t_2) := '0';
        END LOOP;
      END IF;
    ELSE 
      FOR t_1 IN 0 TO 3 LOOP
        weOutT(t_1) := weIn;
      END LOOP;
    END IF;

    FOR t_4 IN 0 TO 3 LOOP
      weOut(t_4) <= weOutT(t_4);
    END LOOP;

  END PROCESS dnnfpgaDatamemlibZAdapterslib_c1_sM6EPvzJ6MJ8XQq8QSyGtpE_zWeAda_output;


END rtl;

