-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_From1_block14.vhd
-- Created: 2025-10-22 15:46:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_From1_block14
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Subsystem2/ConvXDc/Conv/From1
-- Hierarchy Level: 11
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_From1_block14 IS
  PORT( CONV_ModeTag                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END MyProc_src_From1_block14;


ARCHITECTURE rtl OF MyProc_src_From1_block14 IS

  -- Signals
  SIGNAL convMode                         : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  convMode <= unsigned(CONV_ModeTag);

  Out1 <= std_logic_vector(convMode);

END rtl;

