-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_MATLAB_Function_block3.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_MATLAB_Function_block3
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Output_InstructionStack/Subsystem Reference1/Subsystem Reference/StackControl/MATLAB 
-- Functio
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_MATLAB_Function_block3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        payload_addr                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_sizeInBytes               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_id                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_isLast                    :   IN    std_logic;
        valid                             :   IN    std_logic;
        top_cmd                           :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        top_src0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src1                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_dst0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_src1Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_dst0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_epoch                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        rspValid                          :   IN    std_logic;
        rsp_stackNum                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        rsp_value                         :   IN    std_logic;
        rsp_isError                       :   IN    std_logic;
        frameCount                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        stoppedIn                         :   IN    std_logic;
        tableOpConst_stackNum             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_num                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableOpConst_cmd                  :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        tableOpConst_staticReads          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_epoch                :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_isConstant           :   IN    std_logic;
        state                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        topDeq                            :   IN    std_logic;
        tableOp_stackNum                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_num                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableOp_cmd                       :   OUT   T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        tableOp_staticReads               :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_epoch                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_isConstant                :   OUT   std_logic;
        tableValid                        :   OUT   std_logic;
        rspDeq                            :   OUT   std_logic;
        topValid                          :   OUT   std_logic;
        toIdle                            :   OUT   std_logic;
        advance                           :   OUT   std_logic
        );
END MyProc_src_MATLAB_Function_block3;


ARCHITECTURE rtl OF MyProc_src_MATLAB_Function_block3 IS

  -- Signals
  SIGNAL payload_addr_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_sizeInBytes_unsigned     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_id_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL top_src0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_src1_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_dst0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_epoch_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL rsp_stackNum_unsigned            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL frameCount_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL tableOpConst_stackNum_unsigned   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOpConst_num_unsigned        : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tableOpConst_staticReads_unsigned : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOpConst_epoch_unsigned      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_stackNum_tmp             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_num_tmp                  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tableOp_staticReads_tmp          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_epoch_tmp                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count                            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL countTrue                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL isChangedReg                     : std_logic;
  SIGNAL count_next                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL countTrue_next                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL isChangedReg_next                : std_logic;

BEGIN
  payload_addr_unsigned <= unsigned(payload_addr);

  payload_sizeInBytes_unsigned <= unsigned(payload_sizeInBytes);

  payload_id_unsigned <= unsigned(payload_id);

  top_src0_unsigned <= unsigned(top_src0);

  top_src1_unsigned <= unsigned(top_src1);

  top_dst0_unsigned <= unsigned(top_dst0);

  top_epoch_unsigned <= unsigned(top_epoch);

  rsp_stackNum_unsigned <= unsigned(rsp_stackNum);

  frameCount_unsigned <= unsigned(frameCount);

  tableOpConst_stackNum_unsigned <= unsigned(tableOpConst_stackNum);

  tableOpConst_num_unsigned <= unsigned(tableOpConst_num);

  tableOpConst_staticReads_unsigned <= unsigned(tableOpConst_staticReads);

  tableOpConst_epoch_unsigned <= unsigned(tableOpConst_epoch);

  state_unsigned <= unsigned(state);

  MATLAB_Function_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count <= to_unsigned(16#00#, 8);
      countTrue <= to_unsigned(16#00#, 8);
      isChangedReg <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        count <= count_next;
        countTrue <= countTrue_next;
        isChangedReg <= isChangedReg_next;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_process;

  MATLAB_Function_output : PROCESS (count, countTrue, isChangedReg, rspValid, rsp_stackNum_unsigned, rsp_value,
       state_unsigned, tableOpConst_isConstant, tableOpConst_num_unsigned,
       tableOpConst_staticReads_unsigned, topDeq, top_dst0_unsigned,
       top_epoch_unsigned, top_src0_unsigned, top_src1_unsigned, valid)
    VARIABLE topValid1 : std_logic;
    VARIABLE count_temp : unsigned(7 DOWNTO 0);
    VARIABLE countTrue_temp : unsigned(7 DOWNTO 0);
    VARIABLE add_temp : unsigned(8 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(8 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#000#, 9);
    add_temp_0 := to_unsigned(16#000#, 9);
    count_temp := count;
    countTrue_temp := countTrue;
    isChangedReg_next <= isChangedReg;
    tableValid <= '0';
    tableOp_num_tmp <= tableOpConst_num_unsigned;
    tableOp_cmd <= ALWAYSTRUE;
    rspDeq <= '0';
    advance <= '0';
    toIdle <= '0';
    topValid1 := '0';
    IF rspValid = '1' THEN 
      IF rsp_stackNum_unsigned = to_unsigned(16#000000FF#, 8) THEN 
        isChangedReg_next <= '1';
      END IF;
      IF rsp_stackNum_unsigned /= to_unsigned(16#00000004#, 8) THEN 
        rspDeq <= '1';
        -- not ours, just drop.
      END IF;
      IF (rsp_stackNum_unsigned = to_unsigned(16#00000004#, 8)) AND (state_unsigned = to_unsigned(16#00000004#, 8)) THEN 
        add_temp := resize(count, 9) + to_unsigned(16#001#, 9);
        IF add_temp(8) /= '0' THEN 
          count_temp := "11111111";
        ELSE 
          count_temp := add_temp(7 DOWNTO 0);
        END IF;
        IF rsp_value = '1' THEN 
          add_temp_0 := resize(countTrue, 9) + to_unsigned(16#001#, 9);
          IF add_temp_0(8) /= '0' THEN 
            countTrue_temp := "11111111";
          ELSE 
            countTrue_temp := add_temp_0(7 DOWNTO 0);
          END IF;
        END IF;
        rspDeq <= '1';
      END IF;
    END IF;
    CASE state_unsigned IS
      WHEN "00000000" =>
        IF (valid AND isChangedReg) = '1' THEN 
          isChangedReg_next <= '0';
          advance <= '1';
        END IF;
      WHEN "00000001" =>
        NULL;
      WHEN "00000010" =>
        NULL;
      WHEN "00000011" =>
        NULL;
      WHEN "00000100" =>
        IF count_temp = to_unsigned(16#00000003#, 8) THEN 
          advance <= '1';
        END IF;
      WHEN "00000101" =>
        IF countTrue_temp /= to_unsigned(16#00000003#, 8) THEN 
          advance <= '1';
        END IF;
      WHEN "00000110" =>
        toIdle <= '1';
      WHEN OTHERS => 
        NULL;
    END CASE;
    CASE state_unsigned IS
      WHEN "00000001" =>
        IF top_src0_unsigned /= to_unsigned(16#000#, 10) THEN 
          tableOp_num_tmp <= top_src0_unsigned;
          tableOp_cmd <= CANREAD;
        END IF;
        tableValid <= '1';
      WHEN "00000010" =>
        IF top_src1_unsigned /= to_unsigned(16#000#, 10) THEN 
          tableOp_num_tmp <= top_src1_unsigned;
          tableOp_cmd <= CANREAD;
        END IF;
        tableValid <= '1';
      WHEN "00000011" =>
        IF top_dst0_unsigned /= to_unsigned(16#000#, 10) THEN 
          tableOp_num_tmp <= top_dst0_unsigned;
          tableOp_cmd <= CANWRITE;
        END IF;
        tableValid <= '1';
      WHEN "00000101" =>
        IF countTrue_temp = to_unsigned(16#00000003#, 8) THEN 
          topValid1 := '1';
        END IF;
      WHEN "00000110" =>
        count_temp := to_unsigned(16#00#, 8);
        countTrue_temp := to_unsigned(16#00#, 8);
      WHEN OTHERS => 
        NULL;
    END CASE;
    IF (topValid1 AND topDeq) = '1' THEN 
      isChangedReg_next <= '1';
    END IF;
    tableOp_stackNum_tmp <= to_unsigned(16#04#, 8);
    tableOp_staticReads_tmp <= tableOpConst_staticReads_unsigned;
    tableOp_epoch_tmp <= top_epoch_unsigned;
    tableOp_isConstant <= tableOpConst_isConstant;
    topValid <= topValid1;
    count_next <= count_temp;
    countTrue_next <= countTrue_temp;
  END PROCESS MATLAB_Function_output;


  tableOp_stackNum <= std_logic_vector(tableOp_stackNum_tmp);

  tableOp_num <= std_logic_vector(tableOp_num_tmp);

  tableOp_staticReads <= std_logic_vector(tableOp_staticReads_tmp);

  tableOp_epoch <= std_logic_vector(tableOp_epoch_tmp);

END rtl;

