-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_Reference3_block.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_Reference3_block
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Output_InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/Subsystem 
-- Reference
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Subsystem_Reference3_block IS
  PORT( Fxd                               :   IN    std_logic_vector(69 DOWNTO 0);  -- ufix70
        Data_cmd                          :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        Data_src0                         :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        Data_src1                         :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        Data_dst0                         :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        Data_src0Mode                     :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        Data_src1Mode                     :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        Data_dst0Mode                     :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        Data_epoch                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END MyProc_src_Subsystem_Reference3_block;


ARCHITECTURE rtl OF MyProc_src_Subsystem_Reference3_block IS

  -- Component Declarations
  COMPONENT MyProc_src_fromFixed_block1
    PORT( fs                              :   IN    std_logic_vector(69 DOWNTO 0);  -- ufix70
          dataConst_cmd                   :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
          dataConst_src0                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dataConst_src1                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dataConst_dst0                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dataConst_src0Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dataConst_src1Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dataConst_dst0Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dataConst_epoch                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data_cmd                        :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
          data_src0                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          data_src1                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          data_dst0                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          data_src0Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          data_src1Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          data_dst0Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          data_epoch                      :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_fromFixed_block1
    USE ENTITY work.MyProc_src_fromFixed_block1(rtl);

  -- Signals
  SIGNAL Constant_out1_cmd                : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL Constant_out1_src0               : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Constant_out1_src1               : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Constant_out1_dst0               : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Constant_out1_src0Mode           : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL Constant_out1_src1Mode           : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL Constant_out1_dst0Mode           : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL Constant_out1_epoch              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL data_cmd_1                       : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL data_src0_1                      : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_src1_1                      : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_dst0_1                      : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_src0Mode_1                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_src1Mode_1                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_dst0Mode_1                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_epoch_1                     : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_fromFixed : MyProc_src_fromFixed_block1
    PORT MAP( fs => Fxd,  -- ufix70
              dataConst_cmd => Constant_out1_cmd,  -- enum type DLCmd (11 enums)
              dataConst_src0 => std_logic_vector(Constant_out1_src0),  -- ufix10
              dataConst_src1 => std_logic_vector(Constant_out1_src1),  -- ufix10
              dataConst_dst0 => std_logic_vector(Constant_out1_dst0),  -- ufix10
              dataConst_src0Mode => Constant_out1_src0Mode,  -- enum type AddrMode (5 enums)
              dataConst_src1Mode => Constant_out1_src1Mode,  -- enum type AddrMode (5 enums)
              dataConst_dst0Mode => Constant_out1_dst0Mode,  -- enum type AddrMode (5 enums)
              dataConst_epoch => std_logic_vector(Constant_out1_epoch),  -- uint8
              data_cmd => data_cmd_1,  -- enum type DLCmd (11 enums)
              data_src0 => data_src0_1,  -- ufix10
              data_src1 => data_src1_1,  -- ufix10
              data_dst0 => data_dst0_1,  -- ufix10
              data_src0Mode => data_src0Mode_1,  -- enum type AddrMode (5 enums)
              data_src1Mode => data_src1Mode_1,  -- enum type AddrMode (5 enums)
              data_dst0Mode => data_dst0Mode_1,  -- enum type AddrMode (5 enums)
              data_epoch => data_epoch_1  -- uint8
              );

  Constant_out1_cmd <= DFLT;

  Constant_out1_src0 <= to_unsigned(16#000#, 10);

  Constant_out1_src1 <= to_unsigned(16#000#, 10);

  Constant_out1_dst0 <= to_unsigned(16#000#, 10);

  Constant_out1_src0Mode <= Direct;

  Constant_out1_src1Mode <= Direct;

  Constant_out1_dst0Mode <= Direct;

  Constant_out1_epoch <= to_unsigned(16#00#, 8);

  Data_cmd <= data_cmd_1;

  Data_src0Mode <= data_src0Mode_1;

  Data_src1Mode <= data_src1Mode_1;

  Data_dst0Mode <= data_dst0Mode_1;

  Data_src0 <= data_src0_1;

  Data_src1 <= data_src1_1;

  Data_dst0 <= data_dst0_1;

  Data_epoch <= data_epoch_1;

END rtl;

