-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Delay3_block7.vhd
-- Created: 2025-10-22 15:46:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Delay3_block7
-- Source Path: testbench/DUT/DUT/Subsystem/CNN5_debug1/Debug Log Msg/Debug Mem/Delay3
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Delay3_block7 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        alpharesultRdEn                   :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END MyProc_src_Delay3_block7;


ARCHITECTURE rtl OF MyProc_src_Delay3_block7 IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay3_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay3_ectrl                     : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  In1_unsigned <= unsigned(In1);

  
  Delay3_ectrl <= Delay3_out1 WHEN alpharesultRdEn = '0' ELSE
      In1_unsigned;

  Delay3_lowered_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Delay3_ectrl;
      END IF;
    END IF;
  END PROCESS Delay3_lowered_process;


  Out1 <= std_logic_vector(Delay3_out1);

END rtl;

