-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DDR_Read_Arbitrator3.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DDR_Read_Arbitrator3
-- Source Path: testbench/DUT/DUT/DDR Read Arbitrator3
-- Hierarchy Level: 2
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_DDR_Read_Arbitrator3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        axi_rd_s2m_in_rd_aready           :   IN    std_logic;
        axi_rd_s2m_in_rd_dvalid           :   IN    std_logic;
        axi_rd_m2s_in1_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in1_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in1_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in1_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in2_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in2_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in2_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in2_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in3_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in3_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in3_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in3_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in4_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in4_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in4_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in4_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in5_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in5_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in5_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in5_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in6_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in6_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in6_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in6_rd_dready          :   IN    std_logic;
        axi_rd_m2s_in6_rd_arid            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        axi_rd_m2s_in7_rd_avalid          :   IN    std_logic;
        axi_rd_m2s_in7_rd_len             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in7_rd_addr            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_in7_rd_dready          :   IN    std_logic;
        axi_rd_m2s_rd_addr                :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_rd_len                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        axi_rd_m2s_rd_avalid              :   OUT   std_logic;
        axi_rd_m2s_rd_dready              :   OUT   std_logic;
        rd_clearReq                       :   OUT   std_logic_vector(6 DOWNTO 0);  -- boolean [7]
        rd_dvalid                         :   OUT   std_logic_vector(6 DOWNTO 0);  -- boolean [7]
        rd_aready                         :   OUT   std_logic_vector(6 DOWNTO 0)  -- boolean [7]
        );
END MyProc_src_DDR_Read_Arbitrator3;


ARCHITECTURE rtl OF MyProc_src_DDR_Read_Arbitrator3 IS

  -- Component Declarations
  COMPONENT MyProc_src_HDL_FIFO1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Push                            :   IN    std_logic;
          Pop                             :   IN    std_logic;
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT MyProc_src_data_counter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          length                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          rd_dvalid                       :   IN    std_logic;
          dec_counter                     :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MyProc_src_DMA_Req
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          start                           :   IN    std_logic;
          length                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          offset                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          times_counter                   :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          done_out                        :   OUT   std_logic;
          rd_addr                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          rd_len                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          rd_avalid                       :   OUT   std_logic;
          rd_ready                        :   OUT   std_logic;
          req_counter_out                 :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
          state_out                       :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT MyProc_src_HDL_FIFO_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          Push                            :   IN    std_logic;
          Pop                             :   IN    std_logic;
          Out_rsvd                        :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
          );
  END COMPONENT;

  COMPONENT MyProc_src_clearReq_translator
    PORT( req_counter                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          send_req                        :   IN    std_logic;
          clearReq                        :   OUT   std_logic_vector(6 DOWNTO 0)  -- boolean [7]
          );
  END COMPONENT;

  COMPONENT MyProc_src_rd_dvalid_translator
    PORT( send_req                        :   IN    std_logic;
          req_counter                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          clearReq                        :   OUT   std_logic_vector(6 DOWNTO 0)  -- boolean [7]
          );
  END COMPONENT;

  COMPONENT MyProc_src_rd_dvalid_translator1
    PORT( send_req                        :   IN    std_logic;
          req_counter                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          clearReq                        :   OUT   std_logic_vector(6 DOWNTO 0)  -- boolean [7]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_HDL_FIFO1
    USE ENTITY work.MyProc_src_HDL_FIFO1(rtl);

  FOR ALL : MyProc_src_data_counter
    USE ENTITY work.MyProc_src_data_counter(rtl);

  FOR ALL : MyProc_src_DMA_Req
    USE ENTITY work.MyProc_src_DMA_Req(rtl);

  FOR ALL : MyProc_src_HDL_FIFO_block
    USE ENTITY work.MyProc_src_HDL_FIFO_block(rtl);

  FOR ALL : MyProc_src_clearReq_translator
    USE ENTITY work.MyProc_src_clearReq_translator(rtl);

  FOR ALL : MyProc_src_rd_dvalid_translator
    USE ENTITY work.MyProc_src_rd_dvalid_translator(rtl);

  FOR ALL : MyProc_src_rd_dvalid_translator1
    USE ENTITY work.MyProc_src_rd_dvalid_translator1(rtl);

  -- Signals
  SIGNAL rd_avalid                        : std_logic;
  SIGNAL rd_avalid_1                      : std_logic;
  SIGNAL rd_avalid_2                      : std_logic;
  SIGNAL rd_avalid_3                      : std_logic;
  SIGNAL rd_avalid_4                      : std_logic;
  SIGNAL rd_avalid_5                      : std_logic;
  SIGNAL rd_avalid_6                      : std_logic;
  SIGNAL rd_len                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_1                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_2                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_3                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_4                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_5                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_len_6                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_1                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_2                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_3                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_4                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_5                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_addr_6                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rd_dvalid_1                      : std_logic;
  SIGNAL rd_len_7                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL rd_avalid_7                      : std_logic;
  SIGNAL dec_counter                      : std_logic;
  SIGNAL HDL_FIFO1_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL done_out                         : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL times_counter_0to3_count         : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL times_counter_0to3_count_next    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL times_counter_0to3_count_step    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL times_counter_0to3_out1          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL req_counter_out_unsigned         : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Multiport_Switch_offset_out1     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Multiport_Switch_length_out1     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL req_counter_out                  : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL Multiport_Switch_start_out1      : std_logic;
  SIGNAL rd_addr_7                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL rd_readydeadOutdeadOut           : std_logic;
  SIGNAL state_out                        : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL state_out_unsigned               : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL HDL_FIFO_out1                    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL HDL_FIFO_out1_unsigned           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL rd_dready                        : std_logic;
  SIGNAL rd_dready_1                      : std_logic;
  SIGNAL rd_dready_2                      : std_logic;
  SIGNAL rd_dready_3                      : std_logic;
  SIGNAL rd_dready_4                      : std_logic;
  SIGNAL rd_dready_5                      : std_logic;
  SIGNAL rd_dready_6                      : std_logic;
  SIGNAL rd_dready_7                      : std_logic;
  SIGNAL clearReq                         : std_logic_vector(6 DOWNTO 0);  -- boolean [7]
  SIGNAL clearReq_1                       : std_logic_vector(6 DOWNTO 0);  -- boolean [7]
  SIGNAL rd_aready_1                      : std_logic;
  SIGNAL clearReq_2                       : std_logic_vector(6 DOWNTO 0);  -- boolean [7]

BEGIN
  -- DMA_req state machine takes in requests from masters,
  -- and manages req_counter to poll through each request periodically
  -- when state is SEND_REQ, save req_counter value
  -- also push length value into FIFO

  u_HDL_FIFO1 : MyProc_src_HDL_FIFO1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => rd_len_7,  -- uint32
              Push => rd_avalid_7,
              Pop => dec_counter,
              Out_rsvd => HDL_FIFO1_out1  -- uint32
              );

  u_data_counter : MyProc_src_data_counter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              length => HDL_FIFO1_out1,  -- uint32
              rd_dvalid => rd_dvalid_1,
              dec_counter => dec_counter
              );

  u_DMA_Req : MyProc_src_DMA_Req
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              start => Multiport_Switch_start_out1,
              length => std_logic_vector(Multiport_Switch_length_out1),  -- uint32
              offset => std_logic_vector(Multiport_Switch_offset_out1),  -- uint32
              times_counter => std_logic_vector(times_counter_0to3_out1),  -- ufix2
              done_out => done_out,
              rd_addr => rd_addr_7,  -- uint32
              rd_len => rd_len_7,  -- uint32
              rd_avalid => rd_avalid_7,
              rd_ready => rd_readydeadOutdeadOut,
              req_counter_out => req_counter_out,  -- ufix3
              state_out => state_out  -- ufix4
              );

  u_HDL_FIFO : MyProc_src_HDL_FIFO_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => req_counter_out,  -- ufix3
              Push => Compare_To_Constant3_out1,
              Pop => dec_counter,
              Out_rsvd => HDL_FIFO_out1  -- ufix3
              );

  u_clearReq_translator : MyProc_src_clearReq_translator
    PORT MAP( req_counter => req_counter_out,  -- ufix3
              send_req => Compare_To_Constant3_out1,
              clearReq => clearReq  -- boolean [7]
              );

  u_rd_dvalid_translator : MyProc_src_rd_dvalid_translator
    PORT MAP( send_req => axi_rd_s2m_in_rd_dvalid,
              req_counter => HDL_FIFO_out1,  -- ufix3
              clearReq => clearReq_1  -- boolean [7]
              );

  u_rd_dvalid_translator1 : MyProc_src_rd_dvalid_translator1
    PORT MAP( send_req => rd_aready_1,
              req_counter => HDL_FIFO_out1,  -- ufix3
              clearReq => clearReq_2  -- boolean [7]
              );

  rd_avalid <= axi_rd_m2s_in1_rd_avalid;

  rd_avalid_1 <= axi_rd_m2s_in2_rd_avalid;

  rd_avalid_2 <= axi_rd_m2s_in3_rd_avalid;

  rd_avalid_3 <= axi_rd_m2s_in4_rd_avalid;

  rd_avalid_4 <= axi_rd_m2s_in5_rd_avalid;

  rd_avalid_5 <= axi_rd_m2s_in6_rd_avalid;

  rd_avalid_6 <= axi_rd_m2s_in7_rd_avalid;

  rd_len <= unsigned(axi_rd_m2s_in1_rd_len);

  rd_len_1 <= unsigned(axi_rd_m2s_in2_rd_len);

  rd_len_2 <= unsigned(axi_rd_m2s_in3_rd_len);

  rd_len_3 <= unsigned(axi_rd_m2s_in4_rd_len);

  rd_len_4 <= unsigned(axi_rd_m2s_in5_rd_len);

  rd_len_5 <= unsigned(axi_rd_m2s_in6_rd_len);

  rd_len_6 <= unsigned(axi_rd_m2s_in7_rd_len);

  rd_addr <= unsigned(axi_rd_m2s_in1_rd_addr);

  rd_addr_1 <= unsigned(axi_rd_m2s_in2_rd_addr);

  rd_addr_2 <= unsigned(axi_rd_m2s_in3_rd_addr);

  rd_addr_3 <= unsigned(axi_rd_m2s_in4_rd_addr);

  rd_addr_4 <= unsigned(axi_rd_m2s_in5_rd_addr);

  rd_addr_5 <= unsigned(axi_rd_m2s_in6_rd_addr);

  rd_addr_6 <= unsigned(axi_rd_m2s_in7_rd_addr);

  rd_dvalid_1 <= axi_rd_s2m_in_rd_dvalid;

  Logical_Operator_out1 <= done_out XOR dec_counter;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 3
  times_counter_0to3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      times_counter_0to3_count <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Logical_Operator_out1 = '1' THEN
        times_counter_0to3_count <= times_counter_0to3_count_next;
      END IF;
    END IF;
  END PROCESS times_counter_0to3_process;

  times_counter_0to3_out1 <= times_counter_0to3_count;
  
  times_counter_0to3_count_step <= to_unsigned(16#1#, 2) WHEN done_out = '1' ELSE
      to_unsigned(16#3#, 2);
  times_counter_0to3_count_next <= times_counter_0to3_count + times_counter_0to3_count_step;

  
  Multiport_Switch_offset_out1 <= rd_addr WHEN req_counter_out_unsigned = to_unsigned(16#0#, 3) ELSE
      rd_addr_1 WHEN req_counter_out_unsigned = to_unsigned(16#1#, 3) ELSE
      rd_addr_2 WHEN req_counter_out_unsigned = to_unsigned(16#2#, 3) ELSE
      rd_addr_3 WHEN req_counter_out_unsigned = to_unsigned(16#3#, 3) ELSE
      rd_addr_4 WHEN req_counter_out_unsigned = to_unsigned(16#4#, 3) ELSE
      rd_addr_5 WHEN req_counter_out_unsigned = to_unsigned(16#5#, 3) ELSE
      rd_addr_6;

  
  Multiport_Switch_length_out1 <= rd_len WHEN req_counter_out_unsigned = to_unsigned(16#0#, 3) ELSE
      rd_len_1 WHEN req_counter_out_unsigned = to_unsigned(16#1#, 3) ELSE
      rd_len_2 WHEN req_counter_out_unsigned = to_unsigned(16#2#, 3) ELSE
      rd_len_3 WHEN req_counter_out_unsigned = to_unsigned(16#3#, 3) ELSE
      rd_len_4 WHEN req_counter_out_unsigned = to_unsigned(16#4#, 3) ELSE
      rd_len_5 WHEN req_counter_out_unsigned = to_unsigned(16#5#, 3) ELSE
      rd_len_6;

  req_counter_out_unsigned <= unsigned(req_counter_out);

  
  Multiport_Switch_start_out1 <= rd_avalid WHEN req_counter_out_unsigned = to_unsigned(16#0#, 3) ELSE
      rd_avalid_1 WHEN req_counter_out_unsigned = to_unsigned(16#1#, 3) ELSE
      rd_avalid_2 WHEN req_counter_out_unsigned = to_unsigned(16#2#, 3) ELSE
      rd_avalid_3 WHEN req_counter_out_unsigned = to_unsigned(16#3#, 3) ELSE
      rd_avalid_4 WHEN req_counter_out_unsigned = to_unsigned(16#4#, 3) ELSE
      rd_avalid_5 WHEN req_counter_out_unsigned = to_unsigned(16#5#, 3) ELSE
      rd_avalid_6;

  axi_rd_m2s_rd_avalid <= rd_avalid_7;

  state_out_unsigned <= unsigned(state_out);

  
  Compare_To_Constant3_out1 <= '1' WHEN state_out_unsigned = to_unsigned(16#3#, 4) ELSE
      '0';

  HDL_FIFO_out1_unsigned <= unsigned(HDL_FIFO_out1);

  rd_dready <= axi_rd_m2s_in1_rd_dready;

  rd_dready_1 <= axi_rd_m2s_in2_rd_dready;

  rd_dready_2 <= axi_rd_m2s_in3_rd_dready;

  rd_dready_3 <= axi_rd_m2s_in4_rd_dready;

  rd_dready_4 <= axi_rd_m2s_in5_rd_dready;

  rd_dready_5 <= axi_rd_m2s_in6_rd_dready;

  rd_dready_6 <= axi_rd_m2s_in7_rd_dready;

  
  rd_dready_7 <= rd_dready WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#0#, 3) ELSE
      rd_dready_1 WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#1#, 3) ELSE
      rd_dready_2 WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#2#, 3) ELSE
      rd_dready_3 WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#3#, 3) ELSE
      rd_dready_4 WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#4#, 3) ELSE
      rd_dready_5 WHEN HDL_FIFO_out1_unsigned = to_unsigned(16#5#, 3) ELSE
      rd_dready_6;

  axi_rd_m2s_rd_dready <= rd_dready_7;

  rd_clearReq <= clearReq;

  rd_dvalid <= clearReq_1;

  rd_aready_1 <= axi_rd_s2m_in_rd_aready;

  rd_aready <= clearReq_2;

  axi_rd_m2s_rd_addr <= rd_addr_7;

  axi_rd_m2s_rd_len <= rd_len_7;

END rtl;

