-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Unpool_Output.vhd
-- Created: 2025-10-22 15:46:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Unpool_Output
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Unpool Output
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Unpool_Output IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        pixelIn                           :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
        indexIn                           :   IN    vector_of_std_logic_vector17(0 TO 8);  -- ufix17 [9]
        coefIn                            :   IN    vector_of_std_logic_vector8(0 TO 51);  -- int8 [52]
        rSel                              :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        wIndx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        wIndxOffset                       :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        dataValid                         :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
        firstElement                      :   IN    std_logic;
        isModeSix                         :   IN    std_logic;
        out_rsvd                          :   OUT   vector_of_std_logic_vector32(0 TO 1)  -- int32 [2]
        );
END MyProc_src_Unpool_Output;


ARCHITECTURE rtl OF MyProc_src_Unpool_Output IS

  -- Component Declarations
  COMPONENT MyProc_src_NonSingleUnpoolOutput
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          pixelIn                         :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
          indexIn                         :   IN    vector_of_std_logic_vector17(0 TO 8);  -- ufix17 [9]
          rSel                            :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          dataValid                       :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
          isModeSix                       :   IN    std_logic;
          firstElement                    :   IN    std_logic;
          out_rsvd                        :   OUT   vector_of_std_logic_vector32(0 TO 1)  -- int32 [2]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_NonSingleUnpoolOutput
    USE ENTITY work.MyProc_src_NonSingleUnpoolOutput(rtl);

  -- Signals
  SIGNAL NonSingleUnpoolOutput_out1       : vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]

BEGIN
  u_NonSingleUnpoolOutput : MyProc_src_NonSingleUnpoolOutput
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              pixelIn => pixelIn,  -- int8 [18]
              indexIn => indexIn,  -- ufix17 [9]
              rSel => rSel,  -- ufix5
              dataValid => dataValid,  -- ufix1 [9]
              isModeSix => isModeSix,
              firstElement => firstElement,
              out_rsvd => NonSingleUnpoolOutput_out1  -- int32 [2]
              );

  out_rsvd <= NonSingleUnpoolOutput_out1;

END rtl;

