-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_nfp_wire_single_block.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_nfp_wire_single_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Vector quant 
-- single2int32/QFC/DTC/DynamicShiftSingle/nfp_wire_singl
-- Hierarchy Level: 11
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_nfp_wire_single_block IS
  PORT( nfp_in                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        nfp_out                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END MyProc_src_nfp_wire_single_block;


ARCHITECTURE rtl OF MyProc_src_nfp_wire_single_block IS

BEGIN
  nfp_out <= nfp_in;

END rtl;

