-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_block.vhd
-- Created: 2025-10-22 15:46:34
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_block
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/conv/Subsystem
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        incr                              :   IN    std_logic;
        decr                              :   IN    std_logic;
        num                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
        );
END MyProc_src_Subsystem_block;


ARCHITECTURE rtl OF MyProc_src_Subsystem_block IS

  -- Signals
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Logical_Operator7_out1           : std_logic;
  SIGNAL HDL_Counter_count                : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL HDL_Counter_count_next           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL HDL_Counter_count_step           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL HDL_Counter_out1                 : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  Logical_Operator_out1 <=  NOT decr;

  Logical_Operator7_out1 <= incr XOR decr;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 7
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_count <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Logical_Operator7_out1 = '1' THEN
        HDL_Counter_count <= HDL_Counter_count_next;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;

  HDL_Counter_out1 <= HDL_Counter_count;
  
  HDL_Counter_count_step <= to_unsigned(16#1#, 3) WHEN Logical_Operator_out1 = '1' ELSE
      to_unsigned(16#7#, 3);
  HDL_Counter_count_next <= HDL_Counter_count + HDL_Counter_count_step;

  num <= std_logic_vector(HDL_Counter_out1);

END rtl;

