-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem1_block30.vhd
-- Created: 2025-10-22 15:46:43
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem1_block30
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/Subsystem1
-- Hierarchy Level: 4
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem1_block30 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        sendBus_Valid                     :   IN    std_logic;
        sendBus_Payload_ipCount           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        sendBus_Payload_opCount           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        sendBus_Payload_srcAddr           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_dstAddr           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Deq                       :   IN    std_logic;
        sendDone                          :   IN    std_logic;
        payloadDeq                        :   IN    std_logic;
        canSendDone                       :   OUT   std_logic;
        payloadValid                      :   OUT   std_logic;
        payload_ipCount                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        payload_opCount                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        payload_srcAddr                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_dstAddr                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        backBus_Valid                     :   OUT   std_logic;
        backBus_Deq                       :   OUT   std_logic
        );
END MyProc_src_Subsystem1_block30;


ARCHITECTURE rtl OF MyProc_src_Subsystem1_block30 IS

  -- Component Declarations
  COMPONENT MyProc_src_SchedulerIFC_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          START_DIN_ipCount               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          START_DIN_opCount               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          START_DIN_srcAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          START_DIN_dstAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          START_VALID                     :   IN    std_logic;
          DONE_DEQ                        :   IN    std_logic;
          payloadDeq                      :   IN    std_logic;
          sendDone                        :   IN    std_logic;
          payload_ipCount                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          payload_opCount                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          payload_srcAddr                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_dstAddr                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadValid                    :   OUT   std_logic;
          canSendDone                     :   OUT   std_logic;
          START_DEQ                       :   OUT   std_logic;
          DONE_VALID                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_SchedulerIFC_block
    USE ENTITY work.MyProc_src_SchedulerIFC_block(rtl);

  -- Signals
  SIGNAL Valid                            : std_logic;
  SIGNAL Deq                              : std_logic;
  SIGNAL SchedulerIFC_out1_ipCount        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SchedulerIFC_out1_opCount        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SchedulerIFC_out1_srcAddr        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SchedulerIFC_out1_dstAddr        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SchedulerIFC_out2                : std_logic;
  SIGNAL SchedulerIFC_out3                : std_logic;
  SIGNAL Deq_1                            : std_logic;
  SIGNAL Valid_1                          : std_logic;

BEGIN
  u_SchedulerIFC : MyProc_src_SchedulerIFC_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              START_DIN_ipCount => sendBus_Payload_ipCount,  -- uint16
              START_DIN_opCount => sendBus_Payload_opCount,  -- uint16
              START_DIN_srcAddr => sendBus_Payload_srcAddr,  -- uint32
              START_DIN_dstAddr => sendBus_Payload_dstAddr,  -- uint32
              START_VALID => Valid,
              DONE_DEQ => Deq,
              payloadDeq => payloadDeq,
              sendDone => sendDone,
              payload_ipCount => SchedulerIFC_out1_ipCount,  -- uint16
              payload_opCount => SchedulerIFC_out1_opCount,  -- uint16
              payload_srcAddr => SchedulerIFC_out1_srcAddr,  -- uint32
              payload_dstAddr => SchedulerIFC_out1_dstAddr,  -- uint32
              payloadValid => SchedulerIFC_out2,
              canSendDone => SchedulerIFC_out3,
              START_DEQ => Deq_1,
              DONE_VALID => Valid_1
              );

  Valid <= sendBus_Valid;

  Deq <= sendBus_Deq;

  canSendDone <= SchedulerIFC_out3;

  payloadValid <= SchedulerIFC_out2;

  backBus_Valid <= Valid_1;

  backBus_Deq <= Deq_1;

  payload_ipCount <= SchedulerIFC_out1_ipCount;

  payload_opCount <= SchedulerIFC_out1_opCount;

  payload_srcAddr <= SchedulerIFC_out1_srcAddr;

  payload_dstAddr <= SchedulerIFC_out1_dstAddr;

END rtl;

