-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_FIFO_PAYLOAD_block.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_FIFO_PAYLOAD_block
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/NoOp_ InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/StackBufferWithClr/FIFO_PAYLOAD
-- Hierarchy Level: 10
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_FIFO_PAYLOAD_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        DIn                               :   IN    std_logic;  -- ufix1
        Enq                               :   IN    std_logic;
        Deq                               :   IN    std_logic;
        Clear                             :   IN    std_logic;
        DOut                              :   OUT   std_logic;  -- ufix1
        notEmpty                          :   OUT   std_logic;
        notFull                           :   OUT   std_logic
        );
END MyProc_src_FIFO_PAYLOAD_block;


ARCHITECTURE rtl OF MyProc_src_FIFO_PAYLOAD_block IS

  -- Component Declarations
  COMPONENT MyProc_src_Subsystem1_block9
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          deq                             :   IN    std_logic;
          clear                           :   IN    std_logic;
          enq                             :   IN    std_logic;
          notFull                         :   OUT   std_logic;
          notEmpty                        :   OUT   std_logic;
          writePtr                        :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
          readPtr                         :   OUT   std_logic_vector(5 DOWNTO 0)  -- ufix6
          );
  END COMPONENT;

  COMPONENT MyProc_src_DualPortRAM_singlebit
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic;  -- ufix1
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_dout                         :   OUT   std_logic;  -- ufix1
          rd_dout                         :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Subsystem1_block9
    USE ENTITY work.MyProc_src_Subsystem1_block9(rtl);

  FOR ALL : MyProc_src_DualPortRAM_singlebit
    USE ENTITY work.MyProc_src_DualPortRAM_singlebit(rtl);

  -- Signals
  SIGNAL Subsystem1_out1deadOutdeadOut    : std_logic;
  SIGNAL Subsystem1_out2                  : std_logic;
  SIGNAL Subsystem1_out3                  : std_logic_vector(5 DOWNTO 0);  -- ufix6
  SIGNAL Subsystem1_out4                  : std_logic_vector(5 DOWNTO 0);  -- ufix6
  SIGNAL Subsystem1_out3_unsigned         : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Subsystem1_out4_unsigned         : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Relational_Operator1_out1        : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL WR_DATA                          : std_logic;  -- ufix1
  SIGNAL Simple_Dual_Port_RAM_System1_out1 : std_logic;  -- ufix1
  SIGNAL Simple_Dual_Port_RAM_System1_out2 : std_logic;  -- ufix1
  SIGNAL Switch1_out1                     : std_logic;  -- ufix1
  SIGNAL Switch2_out1                     : std_logic;  -- ufix1
  SIGNAL Delay1_out1                      : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1                  : std_logic;

BEGIN
  -- When FIFO is empty, maintain previous value on output.

  u_Subsystem1 : MyProc_src_Subsystem1_block9
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              deq => Deq,
              clear => Clear,
              enq => Enq,
              notFull => Subsystem1_out1deadOutdeadOut,
              notEmpty => Subsystem1_out2,
              writePtr => Subsystem1_out3,  -- ufix6
              readPtr => Subsystem1_out4  -- ufix6
              );

  u_Simple_Dual_Port_RAM_System1 : MyProc_src_DualPortRAM_singlebit
    GENERIC MAP( AddrWidth => 6,
                 DataWidth => 1
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => WR_DATA,  -- ufix1
              wr_addr => Subsystem1_out3,
              wr_en => Enq,
              rd_addr => Subsystem1_out4,
              wr_dout => Simple_Dual_Port_RAM_System1_out1,  -- ufix1
              rd_dout => Simple_Dual_Port_RAM_System1_out2  -- ufix1
              );

  Subsystem1_out3_unsigned <= unsigned(Subsystem1_out3);

  Subsystem1_out4_unsigned <= unsigned(Subsystem1_out4);

  
  Relational_Operator1_out1 <= '1' WHEN Subsystem1_out3_unsigned = Subsystem1_out4_unsigned ELSE
      '0';

  Logical_Operator_out1 <= Enq AND Relational_Operator1_out1;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Logical_Operator_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  WR_DATA <= DIn;

  
  Switch1_out1 <= Simple_Dual_Port_RAM_System1_out2 WHEN Delay2_out1 = '0' ELSE
      Simple_Dual_Port_RAM_System1_out1;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Switch2_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  
  Switch2_out1 <= Delay1_out1 WHEN Subsystem1_out2 = '0' ELSE
      Switch1_out1;

  DOut <= Switch2_out1;

  notEmpty <= Subsystem1_out2;

  Subsystem1_out1 <= '0';

  notFull <= Subsystem1_out1;

END rtl;

