-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_calcData_INSTR_block59.vhd
-- Created: 2025-10-22 15:46:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_calcData_INSTR_block59
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Subsystem Reference19/Subsystem Reference1/calcData_INSTR
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_calcData_INSTR_block59 IS
  PORT( deq                               :   IN    std_logic;
        enq                               :   IN    std_logic;
        dIn_stackNum                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dIn_num                           :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        dIn_cmd                           :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        dIn_staticReads                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dIn_epoch                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dIn_isConstant                    :   IN    std_logic;
        d0In_stackNum                     :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d0In_num                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        d0In_cmd                          :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        d0In_staticReads                  :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d0In_epoch                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d0In_isConstant                   :   IN    std_logic;
        d1In_stackNum                     :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d1In_num                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        d1In_cmd                          :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        d1In_staticReads                  :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d1In_epoch                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        d1In_isConstant                   :   IN    std_logic;
        notFullIn                         :   IN    std_logic;
        notEmptyIn                        :   IN    std_logic;
        notFull                           :   OUT   std_logic;
        d0_stackNum                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d0_num                            :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        d0_cmd                            :   OUT   T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        d0_staticReads                    :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d0_epoch                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d0_isConstant                     :   OUT   std_logic;
        d1_stackNum                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d1_num                            :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        d1_cmd                            :   OUT   T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        d1_staticReads                    :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d1_epoch                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        d1_isConstant                     :   OUT   std_logic;
        notEmpty                          :   OUT   std_logic
        );
END MyProc_src_calcData_INSTR_block59;


ARCHITECTURE rtl OF MyProc_src_calcData_INSTR_block59 IS

  -- Signals
  SIGNAL dIn_stackNum_unsigned            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL dIn_num_unsigned                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dIn_staticReads_unsigned         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL dIn_epoch_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0In_stackNum_unsigned           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0In_num_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL d0In_staticReads_unsigned        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0In_epoch_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1In_stackNum_unsigned           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1In_num_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL d1In_staticReads_unsigned        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1In_epoch_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0_stackNum_tmp                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0_num_tmp                       : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL d0_staticReads_tmp               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d0_epoch_tmp                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1_stackNum_tmp                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1_num_tmp                       : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL d1_staticReads_tmp               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL d1_epoch_tmp                     : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  dIn_stackNum_unsigned <= unsigned(dIn_stackNum);

  dIn_num_unsigned <= unsigned(dIn_num);

  dIn_staticReads_unsigned <= unsigned(dIn_staticReads);

  dIn_epoch_unsigned <= unsigned(dIn_epoch);

  d0In_stackNum_unsigned <= unsigned(d0In_stackNum);

  d0In_num_unsigned <= unsigned(d0In_num);

  d0In_staticReads_unsigned <= unsigned(d0In_staticReads);

  d0In_epoch_unsigned <= unsigned(d0In_epoch);

  d1In_stackNum_unsigned <= unsigned(d1In_stackNum);

  d1In_num_unsigned <= unsigned(d1In_num);

  d1In_staticReads_unsigned <= unsigned(d1In_staticReads);

  d1In_epoch_unsigned <= unsigned(d1In_epoch);

  calcData_INSTR_output : PROCESS (d0In_cmd, d0In_epoch_unsigned, d0In_isConstant, d0In_num_unsigned,
       d0In_stackNum_unsigned, d0In_staticReads_unsigned, d1In_cmd,
       d1In_epoch_unsigned, d1In_isConstant, d1In_num_unsigned,
       d1In_stackNum_unsigned, d1In_staticReads_unsigned, dIn_cmd,
       dIn_epoch_unsigned, dIn_isConstant, dIn_num_unsigned,
       dIn_stackNum_unsigned, dIn_staticReads_unsigned, deq, enq, notEmptyIn,
       notFullIn)
    VARIABLE enqToD0 : std_logic;
    VARIABLE enqToD1 : std_logic;
    VARIABLE D1ToD0 : std_logic;
  BEGIN
    notFull <= notFullIn;
    notEmpty <= notEmptyIn;
    IF (enq AND ( NOT deq)) = '1' THEN 
      notFull <=  NOT notEmptyIn;
      notEmpty <= '1';
    END IF;
    IF (deq AND ( NOT enq)) = '1' THEN 
      notFull <= '1';
      notEmpty <=  NOT notFullIn;
    END IF;
    enqToD0 := (enq AND ( NOT notEmptyIn)) OR ((enq AND deq) AND notFullIn);
    enqToD1 := enq AND notEmptyIn;
    D1ToD0 := deq AND ( NOT notFullIn);
    IF D1ToD0 = '1' THEN 
      d0_stackNum_tmp <= d1In_stackNum_unsigned;
      d0_num_tmp <= d1In_num_unsigned;
      d0_cmd <= d1In_cmd;
      d0_staticReads_tmp <= d1In_staticReads_unsigned;
      d0_epoch_tmp <= d1In_epoch_unsigned;
      d0_isConstant <= d1In_isConstant;
    ELSE 
      d0_stackNum_tmp <= d0In_stackNum_unsigned;
      d0_num_tmp <= d0In_num_unsigned;
      d0_cmd <= d0In_cmd;
      d0_staticReads_tmp <= d0In_staticReads_unsigned;
      d0_epoch_tmp <= d0In_epoch_unsigned;
      d0_isConstant <= d0In_isConstant;
    END IF;
    IF enqToD0 = '1' THEN 
      d0_stackNum_tmp <= dIn_stackNum_unsigned;
      d0_num_tmp <= dIn_num_unsigned;
      d0_cmd <= dIn_cmd;
      d0_staticReads_tmp <= dIn_staticReads_unsigned;
      d0_epoch_tmp <= dIn_epoch_unsigned;
      d0_isConstant <= dIn_isConstant;
    END IF;
    IF enqToD1 = '1' THEN 
      d1_stackNum_tmp <= dIn_stackNum_unsigned;
      d1_num_tmp <= dIn_num_unsigned;
      d1_cmd <= dIn_cmd;
      d1_staticReads_tmp <= dIn_staticReads_unsigned;
      d1_epoch_tmp <= dIn_epoch_unsigned;
      d1_isConstant <= dIn_isConstant;
    ELSE 
      d1_stackNum_tmp <= d1In_stackNum_unsigned;
      d1_num_tmp <= d1In_num_unsigned;
      d1_cmd <= d1In_cmd;
      d1_staticReads_tmp <= d1In_staticReads_unsigned;
      d1_epoch_tmp <= d1In_epoch_unsigned;
      d1_isConstant <= d1In_isConstant;
    END IF;
  END PROCESS calcData_INSTR_output;


  d0_stackNum <= std_logic_vector(d0_stackNum_tmp);

  d0_num <= std_logic_vector(d0_num_tmp);

  d0_staticReads <= std_logic_vector(d0_staticReads_tmp);

  d0_epoch <= std_logic_vector(d0_epoch_tmp);

  d1_stackNum <= std_logic_vector(d1_stackNum_tmp);

  d1_num <= std_logic_vector(d1_num_tmp);

  d1_staticReads <= std_logic_vector(d1_staticReads_tmp);

  d1_epoch <= std_logic_vector(d1_epoch_tmp);

END rtl;

