-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_createPayload_block4.vhd
-- Created: 2025-10-22 15:46:36
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_createPayload_block4
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Input_InstructionStack  /Subsystem Reference1/Subsystem Reference1/createPayload
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_createPayload_block4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        top_cmd                           :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        top_src0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src1                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_dst0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_src1Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_dst0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_epoch                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        topValid                          :   IN    std_logic;
        payloadIn_addr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_sizeInBytes             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_id                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        payloadIn_frameNumber             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_isFirst                 :   IN    std_logic;
        inputAddrOffset_offset            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        inputAddrOffset_lsbs              :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        outputAddrOffset                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputAddrOffsetPrev              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputTotalLSBs                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        deq                               :   IN    std_logic;
        topDeq                            :   OUT   std_logic;
        payload_addr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_sizeInBytes               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_id                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_frameNumber               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_isFirst                   :   OUT   std_logic;
        valid                             :   OUT   std_logic;
        instr_cmd                         :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        instr_src0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src1                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_dst0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_src1Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_dst0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_epoch                       :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END MyProc_src_createPayload_block4;


ARCHITECTURE rtl OF MyProc_src_createPayload_block4 IS

  -- Component Declarations
  COMPONENT MyProc_src_Subsystem_block7
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inputAddrOffset_offset          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          inputAddrOffset_lsbs            :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          selector                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          offsetSelected                  :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT MyProc_src_Subsystem1_block11
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          const_addr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          const_sizeInBytes               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          const_id                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          const_frameNumber               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          const_isFirst                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MyProc_src_MATLAB_Function3_block1
    PORT( deq                             :   IN    std_logic;
          state                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          advance                         :   IN    std_logic;
          toZero                          :   IN    std_logic;
          stateNext                       :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT MyProc_src_createPayload_block3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inputAddrOffsetIn               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          top_cmd                         :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
          top_src0                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          top_src1                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          top_dst0                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          top_src0Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          top_src1Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          top_dst0Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          top_epoch                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          topValid                        :   IN    std_logic;
          payloadIn_addr                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadIn_sizeInBytes           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadIn_id                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          payloadIn_frameNumber           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadIn_isFirst               :   IN    std_logic;
          outputAddrOffsetIn              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          outputAddrOffsetPrevIn          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          outputTotalLSBsIn               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          state                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          payloadConst_addr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadConst_sizeInBytes        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadConst_id                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          payloadConst_frameNumber        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadConst_isFirst            :   IN    std_logic;
          topDeq                          :   OUT   std_logic;
          instr_cmd                       :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
          instr_src0                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          instr_src1                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          instr_dst0                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          instr_src0Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          instr_src1Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          instr_dst0Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          instr_epoch                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          payload_addr                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_sizeInBytes             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_id                      :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          payload_frameNumber             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payload_isFirst                 :   OUT   std_logic;
          valid                           :   OUT   std_logic;
          advance                         :   OUT   std_logic;
          toIdle                          :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Subsystem_block7
    USE ENTITY work.MyProc_src_Subsystem_block7(rtl);

  FOR ALL : MyProc_src_Subsystem1_block11
    USE ENTITY work.MyProc_src_Subsystem1_block11(rtl);

  FOR ALL : MyProc_src_MATLAB_Function3_block1
    USE ENTITY work.MyProc_src_MATLAB_Function3_block1(rtl);

  FOR ALL : MyProc_src_createPayload_block3
    USE ENTITY work.MyProc_src_createPayload_block3(rtl);

  -- Signals
  SIGNAL epoch                            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Extract_Bits_out1                : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Subsystem_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL v_addr                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL v_sizeInBytes                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL v_id                             : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL v_frameNumber                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL v_isFirst                        : std_logic;
  SIGNAL Delay1_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL advance                          : std_logic;
  SIGNAL toIdle                           : std_logic;
  SIGNAL stateNext                        : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL stateNext_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL instr_src0_tmp                   : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_src1_tmp                   : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_dst0_tmp                   : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_epoch_tmp                  : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL payload_addr_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL payload_sizeInBytes_tmp          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL payload_id_tmp                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL payload_frameNumber_tmp          : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  -- We store 4 input address offsets
  -- inside this subsytem because the frameNumber increment in the inputKernel for multi-frame (multi-inputs) is faster 
  -- than the actual processing time taken for all the inputs to be read. This subsystem kind of acts like a buffer 
  -- that stores 4 input offsets corresponding to four frames at a time
  -- 
  -- Epoch is the correct indication of the when a frame has completely been processed and when that is done, the addressOffset 
  -- that is sent from inputKernel to every module must be updated to read the next set of input data correctly
  --  

  u_Subsystem : MyProc_src_Subsystem_block7
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              inputAddrOffset_offset => inputAddrOffset_offset,  -- uint32
              inputAddrOffset_lsbs => inputAddrOffset_lsbs,  -- ufix2
              selector => std_logic_vector(Data_Type_Conversion_out1),  -- uint8
              offsetSelected => Subsystem_out1  -- uint32
              );

  u_Subsystem1 : MyProc_src_Subsystem1_block11
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              const_addr => v_addr,  -- uint32
              const_sizeInBytes => v_sizeInBytes,  -- uint32
              const_id => v_id,  -- uint8
              const_frameNumber => v_frameNumber,  -- uint32
              const_isFirst => v_isFirst
              );

  u_MATLAB_Function3 : MyProc_src_MATLAB_Function3_block1
    PORT MAP( deq => deq,
              state => std_logic_vector(Delay1_out1),  -- uint8
              advance => advance,
              toZero => toIdle,
              stateNext => stateNext  -- uint8
              );

  u_createPayload : MyProc_src_createPayload_block3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              inputAddrOffsetIn => Subsystem_out1,  -- uint32
              top_cmd => top_cmd,  -- enum type DLCmd (11 enums)
              top_src0 => top_src0,  -- ufix10
              top_src1 => top_src1,  -- ufix10
              top_dst0 => top_dst0,  -- ufix10
              top_src0Mode => top_src0Mode,  -- enum type AddrMode (5 enums)
              top_src1Mode => top_src1Mode,  -- enum type AddrMode (5 enums)
              top_dst0Mode => top_dst0Mode,  -- enum type AddrMode (5 enums)
              top_epoch => top_epoch,  -- uint8
              topValid => topValid,
              payloadIn_addr => payloadIn_addr,  -- uint32
              payloadIn_sizeInBytes => payloadIn_sizeInBytes,  -- uint32
              payloadIn_id => payloadIn_id,  -- uint8
              payloadIn_frameNumber => payloadIn_frameNumber,  -- uint32
              payloadIn_isFirst => payloadIn_isFirst,
              outputAddrOffsetIn => outputAddrOffset,  -- uint32
              outputAddrOffsetPrevIn => outputAddrOffsetPrev,  -- uint32
              outputTotalLSBsIn => outputTotalLSBs,  -- ufix4
              state => std_logic_vector(Delay1_out1),  -- uint8
              payloadConst_addr => v_addr,  -- uint32
              payloadConst_sizeInBytes => v_sizeInBytes,  -- uint32
              payloadConst_id => v_id,  -- uint8
              payloadConst_frameNumber => v_frameNumber,  -- uint32
              payloadConst_isFirst => v_isFirst,
              topDeq => topDeq,
              instr_cmd => instr_cmd,  -- enum type DLCmd (11 enums)
              instr_src0 => instr_src0_tmp,  -- ufix10
              instr_src1 => instr_src1_tmp,  -- ufix10
              instr_dst0 => instr_dst0_tmp,  -- ufix10
              instr_src0Mode => instr_src0Mode,  -- enum type AddrMode (5 enums)
              instr_src1Mode => instr_src1Mode,  -- enum type AddrMode (5 enums)
              instr_dst0Mode => instr_dst0Mode,  -- enum type AddrMode (5 enums)
              instr_epoch => instr_epoch_tmp,  -- uint8
              payload_addr => payload_addr_tmp,  -- uint32
              payload_sizeInBytes => payload_sizeInBytes_tmp,  -- uint32
              payload_id => payload_id_tmp,  -- uint8
              payload_frameNumber => payload_frameNumber_tmp,  -- uint32
              payload_isFirst => payload_isFirst,
              valid => valid,
              advance => advance,
              toIdle => toIdle
              );

  epoch <= unsigned(top_epoch);

  Extract_Bits_out1 <= epoch(1 DOWNTO 0);

  Data_Type_Conversion_out1 <= resize(Extract_Bits_out1, 8);

  stateNext_unsigned <= unsigned(stateNext);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= stateNext_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  payload_addr <= payload_addr_tmp;

  payload_sizeInBytes <= payload_sizeInBytes_tmp;

  payload_id <= payload_id_tmp;

  payload_frameNumber <= payload_frameNumber_tmp;

  instr_src0 <= instr_src0_tmp;

  instr_src1 <= instr_src1_tmp;

  instr_dst0 <= instr_dst0_tmp;

  instr_epoch <= instr_epoch_tmp;

END rtl;

