-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_MATLAB_Function_block1.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_MATLAB_Function_block1
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Output_InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/StackBufferWithClr/updateEpoch/MATLAB 
-- Functio
-- Hierarchy Level: 11
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_MATLAB_Function_block1 IS
  PORT( dlInstrIn_cmd                     :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        dlInstrIn_src0                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstrIn_src1                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstrIn_dst0                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstrIn_src0Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstrIn_src1Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstrIn_dst0Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstrIn_epoch                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dlInstr_cmd                       :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        dlInstr_src0                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstr_src1                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstr_dst0                      :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        dlInstr_src0Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstr_src1Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstr_dst0Mode                  :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        dlInstr_epoch                     :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END MyProc_src_MATLAB_Function_block1;


ARCHITECTURE rtl OF MyProc_src_MATLAB_Function_block1 IS

  -- Signals
  SIGNAL dlInstrIn_src0_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstrIn_src1_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstrIn_dst0_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstrIn_epoch_unsigned         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL dlInstr_src0_tmp                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_src1_tmp                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_dst0_tmp                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_epoch_tmp                : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  dlInstrIn_src0_unsigned <= unsigned(dlInstrIn_src0);

  dlInstrIn_src1_unsigned <= unsigned(dlInstrIn_src1);

  dlInstrIn_dst0_unsigned <= unsigned(dlInstrIn_dst0);

  dlInstrIn_epoch_unsigned <= unsigned(dlInstrIn_epoch);

  MATLAB_Function_output : PROCESS (dlInstrIn_cmd, dlInstrIn_dst0Mode, dlInstrIn_dst0_unsigned,
       dlInstrIn_epoch_unsigned, dlInstrIn_src0Mode, dlInstrIn_src0_unsigned,
       dlInstrIn_src1Mode, dlInstrIn_src1_unsigned)
    VARIABLE dlInstr_epoch1 : unsigned(7 DOWNTO 0);
    VARIABLE add_temp : unsigned(8 DOWNTO 0);
  BEGIN
    add_temp := resize(dlInstrIn_epoch_unsigned, 9) + to_unsigned(16#001#, 9);
    IF add_temp(8) /= '0' THEN 
      dlInstr_epoch1 := "11111111";
    ELSE 
      dlInstr_epoch1 := add_temp(7 DOWNTO 0);
    END IF;
    IF dlInstr_epoch1 = dlInstrIn_epoch_unsigned THEN 
      dlInstr_epoch1 := to_unsigned(16#00#, 8);
    END IF;
    dlInstr_cmd <= dlInstrIn_cmd;
    dlInstr_src0_tmp <= dlInstrIn_src0_unsigned;
    dlInstr_src1_tmp <= dlInstrIn_src1_unsigned;
    dlInstr_dst0_tmp <= dlInstrIn_dst0_unsigned;
    dlInstr_src0Mode <= dlInstrIn_src0Mode;
    dlInstr_src1Mode <= dlInstrIn_src1Mode;
    dlInstr_dst0Mode <= dlInstrIn_dst0Mode;
    dlInstr_epoch_tmp <= dlInstr_epoch1;
  END PROCESS MATLAB_Function_output;


  dlInstr_src0 <= std_logic_vector(dlInstr_src0_tmp);

  dlInstr_src1 <= std_logic_vector(dlInstr_src1_tmp);

  dlInstr_dst0 <= std_logic_vector(dlInstr_dst0_tmp);

  dlInstr_epoch <= std_logic_vector(dlInstr_epoch_tmp);

END rtl;

