-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_block8.vhd
-- Created: 2025-10-22 15:46:36
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_block8
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/FC_InstructionStack/Subsystem
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem_block8 IS
  PORT( backBus_Valid                     :   IN    std_logic;
        backBus_Deq                       :   IN    std_logic;
        sendValid                         :   IN    std_logic;
        sendPayload_instrCount            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        sendPayload_srcAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendPayload_dstAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendDeq                           :   IN    std_logic;
        backValid                         :   OUT   std_logic;
        backDeq                           :   OUT   std_logic;
        sendBus_Valid                     :   OUT   std_logic;
        sendBus_Payload_instrCount        :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        sendBus_Payload_srcAddr           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_dstAddr           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Deq                       :   OUT   std_logic
        );
END MyProc_src_Subsystem_block8;


ARCHITECTURE rtl OF MyProc_src_Subsystem_block8 IS

  -- Signals
  SIGNAL Valid                            : std_logic;
  SIGNAL Deq                              : std_logic;

BEGIN
  Valid <= backBus_Valid;

  backValid <= Valid;

  Deq <= backBus_Deq;

  backDeq <= Deq;

  sendBus_Valid <= sendValid;

  sendBus_Deq <= sendDeq;

  sendBus_Payload_instrCount <= sendPayload_instrCount;

  sendBus_Payload_srcAddr <= sendPayload_srcAddr;

  sendBus_Payload_dstAddr <= sendPayload_dstAddr;

END rtl;

