-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Weight_Loader.vhd
-- Created: 2025-10-22 15:46:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Weight_Loader
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Weight Loader
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Weight_Loader IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        wxyIn                             :   IN    vector_of_std_logic_vector8(0 TO 35);  -- int8 [36]
        load                              :   IN    std_logic;
        wValid                            :   IN    std_logic_vector(35 DOWNTO 0);  -- ufix1 [36]
        coefIn                            :   OUT   vector_of_std_logic_vector8(0 TO 35)  -- int8 [36]
        );
END MyProc_src_Weight_Loader;


ARCHITECTURE rtl OF MyProc_src_Weight_Loader IS

  -- Component Declarations
  COMPONENT MyProc_src_EnabledDelay
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          D                               :   IN    vector_of_std_logic_vector8(0 TO 35);  -- int8 [36]
          En                              :   IN    std_logic;
          Q                               :   OUT   vector_of_std_logic_vector8(0 TO 35)  -- int8 [36]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_EnabledDelay
    USE ENTITY work.MyProc_src_EnabledDelay(rtl);

  -- Signals
  SIGNAL wValid_0                         : std_logic;  -- ufix1
  SIGNAL Constant_out1                    : vector_of_signed8(0 TO 35);  -- int8 [36]
  SIGNAL EnabledDelay_out1_signed         : vector_of_std_logic_vector8(0 TO 35);  -- ufix8 [36]
  SIGNAL wValid_1                         : std_logic;  -- ufix1
  SIGNAL wValid_2                         : std_logic;  -- ufix1
  SIGNAL wValid_3                         : std_logic;  -- ufix1
  SIGNAL wValid_4                         : std_logic;  -- ufix1
  SIGNAL wValid_5                         : std_logic;  -- ufix1
  SIGNAL wValid_6                         : std_logic;  -- ufix1
  SIGNAL wValid_7                         : std_logic;  -- ufix1
  SIGNAL wValid_8                         : std_logic;  -- ufix1
  SIGNAL wValid_9                         : std_logic;  -- ufix1
  SIGNAL wValid_10                        : std_logic;  -- ufix1
  SIGNAL wValid_11                        : std_logic;  -- ufix1
  SIGNAL wValid_12                        : std_logic;  -- ufix1
  SIGNAL wValid_13                        : std_logic;  -- ufix1
  SIGNAL wValid_14                        : std_logic;  -- ufix1
  SIGNAL wValid_15                        : std_logic;  -- ufix1
  SIGNAL wValid_16                        : std_logic;  -- ufix1
  SIGNAL wValid_17                        : std_logic;  -- ufix1
  SIGNAL wValid_18                        : std_logic;  -- ufix1
  SIGNAL wValid_19                        : std_logic;  -- ufix1
  SIGNAL wValid_20                        : std_logic;  -- ufix1
  SIGNAL wValid_21                        : std_logic;  -- ufix1
  SIGNAL wValid_22                        : std_logic;  -- ufix1
  SIGNAL wValid_23                        : std_logic;  -- ufix1
  SIGNAL wValid_24                        : std_logic;  -- ufix1
  SIGNAL wValid_25                        : std_logic;  -- ufix1
  SIGNAL wValid_26                        : std_logic;  -- ufix1
  SIGNAL wValid_27                        : std_logic;  -- ufix1
  SIGNAL wValid_28                        : std_logic;  -- ufix1
  SIGNAL wValid_29                        : std_logic;  -- ufix1
  SIGNAL wValid_30                        : std_logic;  -- ufix1
  SIGNAL wValid_31                        : std_logic;  -- ufix1
  SIGNAL wValid_32                        : std_logic;  -- ufix1
  SIGNAL wValid_33                        : std_logic;  -- ufix1
  SIGNAL wValid_34                        : std_logic;  -- ufix1
  SIGNAL wValid_35                        : std_logic;  -- ufix1
  SIGNAL Constant_out1_0                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_0              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_0                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_1                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_1              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_1                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_2                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_2              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_2                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_3                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_3              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_3                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_4                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_4              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_4                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_5                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_5              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_5                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_6                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_6              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_6                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_7                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_7              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_7                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_8                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_8              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_8                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_9                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_9              : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_9                    : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_10                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_10             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_10                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_11                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_11             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_11                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_12                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_12             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_12                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_13                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_13             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_13                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_14                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_14             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_14                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_15                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_15             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_15                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_16                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_16             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_16                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_17                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_17             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_17                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_18                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_18             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_18                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_19                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_19             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_19                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_20                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_20             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_20                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_21                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_21             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_21                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_22                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_22             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_22                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_23                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_23             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_23                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_24                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_24             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_24                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_25                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_25             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_25                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_26                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_26             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_26                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_27                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_27             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_27                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_28                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_28             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_28                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_29                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_29             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_29                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_30                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_30             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_30                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_31                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_31             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_31                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_32                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_32             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_32                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_33                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_33             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_33                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_34                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_34             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_34                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant_out1_35                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL EnabledDelay_out1_35             : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1_35                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch_out1                      : vector_of_signed8(0 TO 35);  -- int8 [36]

BEGIN
  u_EnabledDelay : MyProc_src_EnabledDelay
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              D => wxyIn,  -- int8 [36]
              En => load,
              Q => EnabledDelay_out1_signed  -- int8 [36]
              );

  wValid_0 <= wValid(0);

  Constant_out1 <= (OTHERS => to_signed(16#00#, 8));

  wValid_1 <= wValid(1);

  wValid_2 <= wValid(2);

  wValid_3 <= wValid(3);

  wValid_4 <= wValid(4);

  wValid_5 <= wValid(5);

  wValid_6 <= wValid(6);

  wValid_7 <= wValid(7);

  wValid_8 <= wValid(8);

  wValid_9 <= wValid(9);

  wValid_10 <= wValid(10);

  wValid_11 <= wValid(11);

  wValid_12 <= wValid(12);

  wValid_13 <= wValid(13);

  wValid_14 <= wValid(14);

  wValid_15 <= wValid(15);

  wValid_16 <= wValid(16);

  wValid_17 <= wValid(17);

  wValid_18 <= wValid(18);

  wValid_19 <= wValid(19);

  wValid_20 <= wValid(20);

  wValid_21 <= wValid(21);

  wValid_22 <= wValid(22);

  wValid_23 <= wValid(23);

  wValid_24 <= wValid(24);

  wValid_25 <= wValid(25);

  wValid_26 <= wValid(26);

  wValid_27 <= wValid(27);

  wValid_28 <= wValid(28);

  wValid_29 <= wValid(29);

  wValid_30 <= wValid(30);

  wValid_31 <= wValid(31);

  wValid_32 <= wValid(32);

  wValid_33 <= wValid(33);

  wValid_34 <= wValid(34);

  wValid_35 <= wValid(35);

  Constant_out1_0 <= Constant_out1(0);

  EnabledDelay_out1_0 <= signed(EnabledDelay_out1_signed(0));

  
  Switch_out1_0 <= Constant_out1_0 WHEN wValid_0 = '0' ELSE
      EnabledDelay_out1_0;

  Constant_out1_1 <= Constant_out1(1);

  EnabledDelay_out1_1 <= signed(EnabledDelay_out1_signed(1));

  
  Switch_out1_1 <= Constant_out1_1 WHEN wValid_1 = '0' ELSE
      EnabledDelay_out1_1;

  Constant_out1_2 <= Constant_out1(2);

  EnabledDelay_out1_2 <= signed(EnabledDelay_out1_signed(2));

  
  Switch_out1_2 <= Constant_out1_2 WHEN wValid_2 = '0' ELSE
      EnabledDelay_out1_2;

  Constant_out1_3 <= Constant_out1(3);

  EnabledDelay_out1_3 <= signed(EnabledDelay_out1_signed(3));

  
  Switch_out1_3 <= Constant_out1_3 WHEN wValid_3 = '0' ELSE
      EnabledDelay_out1_3;

  Constant_out1_4 <= Constant_out1(4);

  EnabledDelay_out1_4 <= signed(EnabledDelay_out1_signed(4));

  
  Switch_out1_4 <= Constant_out1_4 WHEN wValid_4 = '0' ELSE
      EnabledDelay_out1_4;

  Constant_out1_5 <= Constant_out1(5);

  EnabledDelay_out1_5 <= signed(EnabledDelay_out1_signed(5));

  
  Switch_out1_5 <= Constant_out1_5 WHEN wValid_5 = '0' ELSE
      EnabledDelay_out1_5;

  Constant_out1_6 <= Constant_out1(6);

  EnabledDelay_out1_6 <= signed(EnabledDelay_out1_signed(6));

  
  Switch_out1_6 <= Constant_out1_6 WHEN wValid_6 = '0' ELSE
      EnabledDelay_out1_6;

  Constant_out1_7 <= Constant_out1(7);

  EnabledDelay_out1_7 <= signed(EnabledDelay_out1_signed(7));

  
  Switch_out1_7 <= Constant_out1_7 WHEN wValid_7 = '0' ELSE
      EnabledDelay_out1_7;

  Constant_out1_8 <= Constant_out1(8);

  EnabledDelay_out1_8 <= signed(EnabledDelay_out1_signed(8));

  
  Switch_out1_8 <= Constant_out1_8 WHEN wValid_8 = '0' ELSE
      EnabledDelay_out1_8;

  Constant_out1_9 <= Constant_out1(9);

  EnabledDelay_out1_9 <= signed(EnabledDelay_out1_signed(9));

  
  Switch_out1_9 <= Constant_out1_9 WHEN wValid_9 = '0' ELSE
      EnabledDelay_out1_9;

  Constant_out1_10 <= Constant_out1(10);

  EnabledDelay_out1_10 <= signed(EnabledDelay_out1_signed(10));

  
  Switch_out1_10 <= Constant_out1_10 WHEN wValid_10 = '0' ELSE
      EnabledDelay_out1_10;

  Constant_out1_11 <= Constant_out1(11);

  EnabledDelay_out1_11 <= signed(EnabledDelay_out1_signed(11));

  
  Switch_out1_11 <= Constant_out1_11 WHEN wValid_11 = '0' ELSE
      EnabledDelay_out1_11;

  Constant_out1_12 <= Constant_out1(12);

  EnabledDelay_out1_12 <= signed(EnabledDelay_out1_signed(12));

  
  Switch_out1_12 <= Constant_out1_12 WHEN wValid_12 = '0' ELSE
      EnabledDelay_out1_12;

  Constant_out1_13 <= Constant_out1(13);

  EnabledDelay_out1_13 <= signed(EnabledDelay_out1_signed(13));

  
  Switch_out1_13 <= Constant_out1_13 WHEN wValid_13 = '0' ELSE
      EnabledDelay_out1_13;

  Constant_out1_14 <= Constant_out1(14);

  EnabledDelay_out1_14 <= signed(EnabledDelay_out1_signed(14));

  
  Switch_out1_14 <= Constant_out1_14 WHEN wValid_14 = '0' ELSE
      EnabledDelay_out1_14;

  Constant_out1_15 <= Constant_out1(15);

  EnabledDelay_out1_15 <= signed(EnabledDelay_out1_signed(15));

  
  Switch_out1_15 <= Constant_out1_15 WHEN wValid_15 = '0' ELSE
      EnabledDelay_out1_15;

  Constant_out1_16 <= Constant_out1(16);

  EnabledDelay_out1_16 <= signed(EnabledDelay_out1_signed(16));

  
  Switch_out1_16 <= Constant_out1_16 WHEN wValid_16 = '0' ELSE
      EnabledDelay_out1_16;

  Constant_out1_17 <= Constant_out1(17);

  EnabledDelay_out1_17 <= signed(EnabledDelay_out1_signed(17));

  
  Switch_out1_17 <= Constant_out1_17 WHEN wValid_17 = '0' ELSE
      EnabledDelay_out1_17;

  Constant_out1_18 <= Constant_out1(18);

  EnabledDelay_out1_18 <= signed(EnabledDelay_out1_signed(18));

  
  Switch_out1_18 <= Constant_out1_18 WHEN wValid_18 = '0' ELSE
      EnabledDelay_out1_18;

  Constant_out1_19 <= Constant_out1(19);

  EnabledDelay_out1_19 <= signed(EnabledDelay_out1_signed(19));

  
  Switch_out1_19 <= Constant_out1_19 WHEN wValid_19 = '0' ELSE
      EnabledDelay_out1_19;

  Constant_out1_20 <= Constant_out1(20);

  EnabledDelay_out1_20 <= signed(EnabledDelay_out1_signed(20));

  
  Switch_out1_20 <= Constant_out1_20 WHEN wValid_20 = '0' ELSE
      EnabledDelay_out1_20;

  Constant_out1_21 <= Constant_out1(21);

  EnabledDelay_out1_21 <= signed(EnabledDelay_out1_signed(21));

  
  Switch_out1_21 <= Constant_out1_21 WHEN wValid_21 = '0' ELSE
      EnabledDelay_out1_21;

  Constant_out1_22 <= Constant_out1(22);

  EnabledDelay_out1_22 <= signed(EnabledDelay_out1_signed(22));

  
  Switch_out1_22 <= Constant_out1_22 WHEN wValid_22 = '0' ELSE
      EnabledDelay_out1_22;

  Constant_out1_23 <= Constant_out1(23);

  EnabledDelay_out1_23 <= signed(EnabledDelay_out1_signed(23));

  
  Switch_out1_23 <= Constant_out1_23 WHEN wValid_23 = '0' ELSE
      EnabledDelay_out1_23;

  Constant_out1_24 <= Constant_out1(24);

  EnabledDelay_out1_24 <= signed(EnabledDelay_out1_signed(24));

  
  Switch_out1_24 <= Constant_out1_24 WHEN wValid_24 = '0' ELSE
      EnabledDelay_out1_24;

  Constant_out1_25 <= Constant_out1(25);

  EnabledDelay_out1_25 <= signed(EnabledDelay_out1_signed(25));

  
  Switch_out1_25 <= Constant_out1_25 WHEN wValid_25 = '0' ELSE
      EnabledDelay_out1_25;

  Constant_out1_26 <= Constant_out1(26);

  EnabledDelay_out1_26 <= signed(EnabledDelay_out1_signed(26));

  
  Switch_out1_26 <= Constant_out1_26 WHEN wValid_26 = '0' ELSE
      EnabledDelay_out1_26;

  Constant_out1_27 <= Constant_out1(27);

  EnabledDelay_out1_27 <= signed(EnabledDelay_out1_signed(27));

  
  Switch_out1_27 <= Constant_out1_27 WHEN wValid_27 = '0' ELSE
      EnabledDelay_out1_27;

  Constant_out1_28 <= Constant_out1(28);

  EnabledDelay_out1_28 <= signed(EnabledDelay_out1_signed(28));

  
  Switch_out1_28 <= Constant_out1_28 WHEN wValid_28 = '0' ELSE
      EnabledDelay_out1_28;

  Constant_out1_29 <= Constant_out1(29);

  EnabledDelay_out1_29 <= signed(EnabledDelay_out1_signed(29));

  
  Switch_out1_29 <= Constant_out1_29 WHEN wValid_29 = '0' ELSE
      EnabledDelay_out1_29;

  Constant_out1_30 <= Constant_out1(30);

  EnabledDelay_out1_30 <= signed(EnabledDelay_out1_signed(30));

  
  Switch_out1_30 <= Constant_out1_30 WHEN wValid_30 = '0' ELSE
      EnabledDelay_out1_30;

  Constant_out1_31 <= Constant_out1(31);

  EnabledDelay_out1_31 <= signed(EnabledDelay_out1_signed(31));

  
  Switch_out1_31 <= Constant_out1_31 WHEN wValid_31 = '0' ELSE
      EnabledDelay_out1_31;

  Constant_out1_32 <= Constant_out1(32);

  EnabledDelay_out1_32 <= signed(EnabledDelay_out1_signed(32));

  
  Switch_out1_32 <= Constant_out1_32 WHEN wValid_32 = '0' ELSE
      EnabledDelay_out1_32;

  Constant_out1_33 <= Constant_out1(33);

  EnabledDelay_out1_33 <= signed(EnabledDelay_out1_signed(33));

  
  Switch_out1_33 <= Constant_out1_33 WHEN wValid_33 = '0' ELSE
      EnabledDelay_out1_33;

  Constant_out1_34 <= Constant_out1(34);

  EnabledDelay_out1_34 <= signed(EnabledDelay_out1_signed(34));

  
  Switch_out1_34 <= Constant_out1_34 WHEN wValid_34 = '0' ELSE
      EnabledDelay_out1_34;

  Constant_out1_35 <= Constant_out1(35);

  EnabledDelay_out1_35 <= signed(EnabledDelay_out1_signed(35));

  
  Switch_out1_35 <= Constant_out1_35 WHEN wValid_35 = '0' ELSE
      EnabledDelay_out1_35;

  Switch_out1(0) <= Switch_out1_0;
  Switch_out1(1) <= Switch_out1_1;
  Switch_out1(2) <= Switch_out1_2;
  Switch_out1(3) <= Switch_out1_3;
  Switch_out1(4) <= Switch_out1_4;
  Switch_out1(5) <= Switch_out1_5;
  Switch_out1(6) <= Switch_out1_6;
  Switch_out1(7) <= Switch_out1_7;
  Switch_out1(8) <= Switch_out1_8;
  Switch_out1(9) <= Switch_out1_9;
  Switch_out1(10) <= Switch_out1_10;
  Switch_out1(11) <= Switch_out1_11;
  Switch_out1(12) <= Switch_out1_12;
  Switch_out1(13) <= Switch_out1_13;
  Switch_out1(14) <= Switch_out1_14;
  Switch_out1(15) <= Switch_out1_15;
  Switch_out1(16) <= Switch_out1_16;
  Switch_out1(17) <= Switch_out1_17;
  Switch_out1(18) <= Switch_out1_18;
  Switch_out1(19) <= Switch_out1_19;
  Switch_out1(20) <= Switch_out1_20;
  Switch_out1(21) <= Switch_out1_21;
  Switch_out1(22) <= Switch_out1_22;
  Switch_out1(23) <= Switch_out1_23;
  Switch_out1(24) <= Switch_out1_24;
  Switch_out1(25) <= Switch_out1_25;
  Switch_out1(26) <= Switch_out1_26;
  Switch_out1(27) <= Switch_out1_27;
  Switch_out1(28) <= Switch_out1_28;
  Switch_out1(29) <= Switch_out1_29;
  Switch_out1(30) <= Switch_out1_30;
  Switch_out1(31) <= Switch_out1_31;
  Switch_out1(32) <= Switch_out1_32;
  Switch_out1(33) <= Switch_out1_33;
  Switch_out1(34) <= Switch_out1_34;
  Switch_out1(35) <= Switch_out1_35;

  outputgen: FOR k IN 0 TO 35 GENERATE
    coefIn(k) <= std_logic_vector(Switch_out1(k));
  END GENERATE;

END rtl;

