-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_EnLogic_block9.vhd
-- Created: 2025-10-22 15:46:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_EnLogic_block9
-- Source Path: testbench/DUT/DUT/Subsystem/CNN5_debug1/Debug Log TS/Debug Mem/DebugDecoder/EnLogic
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_EnLogic_block9 IS
  PORT( debugEnable                       :   IN    std_logic;
        debugSelection                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        debugValid                        :   IN    std_logic;
        de                                :   OUT   std_logic;
        id                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        we                                :   OUT   std_logic;
        debugBank                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END MyProc_src_EnLogic_block9;


ARCHITECTURE rtl OF MyProc_src_EnLogic_block9 IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL debugSelection_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL id_tmp                           : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL debugBank_tmp                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL debugBank_1                      : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL debugSelectID                    : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL s                                : std_logic;

BEGIN
  debugSelection_unsigned <= unsigned(debugSelection);

  debugBank_1 <= debugSelection_unsigned(31 DOWNTO 16);
  -- top bits are bank
  debugSelectID <= debugSelection_unsigned(15 DOWNTO 0);
  -- bottom bits are ID
  s <= (debugEnable AND debugValid) AND hdlcoder_to_stdlogic(debugSelectID = to_unsigned(16#000C#, 16));
  de <= debugEnable AND hdlcoder_to_stdlogic(debugSelectID = to_unsigned(16#000C#, 16));
  id_tmp <= to_unsigned(16#000C#, 16);
  we <= s AND hdlcoder_to_stdlogic(debugBank_1 = to_unsigned(16#0000#, 16));
  debugBank_tmp <= debugBank_1;

  id <= std_logic_vector(id_tmp);

  debugBank <= std_logic_vector(debugBank_tmp);

END rtl;

