-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_add.vhd
-- Created: 2025-10-22 15:46:34
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_add
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/add
-- Hierarchy Level: 4
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_add IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        sendBus_Valid                     :   IN    std_logic;
        sendBus_Payload_src0Addr          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_src1Addr          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_dstAddr           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_exponent          :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        sendBus_Payload_exponentIn1       :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        sendBus_Payload_exponentIn2       :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        sendBus_Payload_reluValue         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        sendBus_Payload_reluScaleExp      :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
        sendBus_Payload_single2Int8Exp    :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        sendBus_Payload_int82SingleExp    :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        sendBus_Deq                       :   IN    std_logic;
        backBus_Deq                       :   IN    std_logic;
        backBus_Valid                     :   IN    std_logic;
        status_active                     :   OUT   std_logic;
        status_num                        :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        CustomActive                      :   OUT   std_logic
        );
END MyProc_src_add;


ARCHITECTURE rtl OF MyProc_src_add IS

  -- Component Declarations
  COMPONENT MyProc_src_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          incr                            :   IN    std_logic;
          decr                            :   IN    std_logic;
          num                             :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Subsystem
    USE ENTITY work.MyProc_src_Subsystem(rtl);

  -- Signals
  SIGNAL Bus_Creator_out1                 : std_logic;
  SIGNAL Bus_Creator_out1_1               : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Valid                            : std_logic;
  SIGNAL Deq                              : std_logic;
  SIGNAL Deq_1                            : std_logic;
  SIGNAL start                            : std_logic;
  SIGNAL Valid_1                          : std_logic;
  SIGNAL finish                           : std_logic;
  SIGNAL num                              : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL num_unsigned                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL active                           : std_logic;

BEGIN
  u_Subsystem : MyProc_src_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              incr => start,
              decr => finish,
              num => num  -- ufix3
              );

  Bus_Creator_out1 <= '0';

  status_active <= Bus_Creator_out1;

  Bus_Creator_out1_1 <= to_unsigned(16#0#, 3);

  status_num <= std_logic_vector(Bus_Creator_out1_1);

  Valid <= sendBus_Valid;

  Deq <= sendBus_Deq;

  Deq_1 <= backBus_Deq;

  start <= Valid AND Deq_1;

  Valid_1 <= backBus_Valid;

  finish <= Deq AND Valid_1;

  num_unsigned <= unsigned(num);

  
  active <= '1' WHEN num_unsigned /= to_unsigned(16#0#, 3) ELSE
      '0';

  CustomActive <= active;

END rtl;

