-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_TokenSend.vhd
-- Created: 2025-10-22 15:46:42
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_TokenSend
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/Subsystem1/SchedulerIFC/TokenSend
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_TokenSend IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        send                              :   IN    std_logic;
        DEQ                               :   IN    std_logic;
        VALID                             :   OUT   std_logic;
        canSend                           :   OUT   std_logic
        );
END MyProc_src_TokenSend;


ARCHITECTURE rtl OF MyProc_src_TokenSend IS

  -- Component Declarations
  COMPONENT MyProc_src_FIFO_Token_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enq                             :   IN    std_logic;
          deq                             :   IN    std_logic;
          notEmpty                        :   OUT   std_logic;
          notFull                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_FIFO_Token_block2
    USE ENTITY work.MyProc_src_FIFO_Token_block2(rtl);

  -- Signals
  SIGNAL FIFO_Token_out1                  : std_logic;
  SIGNAL FIFO_Token_out2                  : std_logic;

BEGIN
  u_FIFO_Token : MyProc_src_FIFO_Token_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enq => send,
              deq => DEQ,
              notEmpty => FIFO_Token_out1,
              notFull => FIFO_Token_out2
              );

  VALID <= FIFO_Token_out1;

  canSend <= FIFO_Token_out2;

END rtl;

