-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_SyncedProcessorDynamicLCLoading.vhd
-- Created: 2025-10-22 15:46:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_SyncedProcessorDynamicLCLoading
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/InputProcessor0_T/IPSync/SyncedProcessorDynamicLCLoading
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_SyncedProcessorDynamicLCLoading IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        start                             :   IN    std_logic;
        wIn                               :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        progDone                          :   IN    std_logic;
        CONV_DEBUGINTAG_debugEnable       :   IN    std_logic;
        CONV_DEBUGINTAG_debugSelect       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_DEBUGINTAG_resultValid       :   IN    std_logic;
        CONV_DEBUGINTAG_resultWrData      :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_DEBUGINTAG_resultWrAddr      :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        CONV_DEBUGINTAG_resultRdAddr      :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        CONV_DEBUGINTAG_resultRdEn        :   IN    std_logic;
        sOut                              :   OUT   std_logic_vector(11 DOWNTO 0);  -- ufix12
        progStart                         :   OUT   std_logic;
        progActive                        :   OUT   std_logic;  -- ufix1
        moveOn                            :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        counterOut                        :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        CONV_DEBUGOUTTAG_2_debugID        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_DEBUGOUTTAG_2_debugRdData    :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END MyProc_src_SyncedProcessorDynamicLCLoading;


ARCHITECTURE rtl OF MyProc_src_SyncedProcessorDynamicLCLoading IS

  -- Component Declarations
  COMPONENT MyProc_src_SyncHub
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          start                           :   IN    std_logic;
          wIn                             :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
          moveOn                          :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          CONV_DEBUGINTAG_debugEnable     :   IN    std_logic;
          CONV_DEBUGINTAG_debugSelect     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          CONV_DEBUGINTAG_resultValid     :   IN    std_logic;
          CONV_DEBUGINTAG_resultWrData    :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          CONV_DEBUGINTAG_resultWrAddr    :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          CONV_DEBUGINTAG_resultRdAddr    :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          CONV_DEBUGINTAG_resultRdEn      :   IN    std_logic;
          sOut                            :   OUT   std_logic_vector(11 DOWNTO 0);  -- ufix12
          counterOut                      :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          CONV_DEBUGOUTTAG_2_debugID      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          CONV_DEBUGOUTTAG_2_debugRdData  :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_SyncHub
    USE ENTITY work.MyProc_src_SyncHub(rtl);

  -- Signals
  SIGNAL wIn_unsigned                     : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Bit_Concat_out1                  : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Constant_out1                    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL sOut_tmp                         : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL counterOut_tmp                   : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL CONV_DEBUGOUTTAG_2_debugID_tmp   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Bit_Slice1_out1                  : std_logic;  -- ufix1
  SIGNAL sOut_tmp_unsigned                : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Bit_Slice_out1                   : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  u_SyncHub : MyProc_src_SyncHub
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              start => start,
              wIn => std_logic_vector(Bit_Concat_out1),  -- ufix12
              moveOn => std_logic_vector(Constant_out1),  -- ufix2
              CONV_DEBUGINTAG_debugEnable => CONV_DEBUGINTAG_debugEnable,
              CONV_DEBUGINTAG_debugSelect => CONV_DEBUGINTAG_debugSelect,  -- uint32
              CONV_DEBUGINTAG_resultValid => CONV_DEBUGINTAG_resultValid,
              CONV_DEBUGINTAG_resultWrData => CONV_DEBUGINTAG_resultWrData,  -- single
              CONV_DEBUGINTAG_resultWrAddr => CONV_DEBUGINTAG_resultWrAddr,  -- ufix15
              CONV_DEBUGINTAG_resultRdAddr => CONV_DEBUGINTAG_resultRdAddr,  -- ufix15
              CONV_DEBUGINTAG_resultRdEn => CONV_DEBUGINTAG_resultRdEn,
              sOut => sOut_tmp,  -- ufix12
              counterOut => counterOut_tmp,  -- ufix13
              CONV_DEBUGOUTTAG_2_debugID => CONV_DEBUGOUTTAG_2_debugID_tmp,  -- uint32
              CONV_DEBUGOUTTAG_2_debugRdData => CONV_DEBUGOUTTAG_2_debugRdData  -- single
              );

  wIn_unsigned <= unsigned(wIn);

  Bit_Concat_out1 <= wIn_unsigned & progDone;

  Constant_out1 <= to_unsigned(16#1#, 2);

  progStart <= start;

  Bit_Slice1_out1 <= '0';

  progActive <= Bit_Slice1_out1;

  sOut_tmp_unsigned <= unsigned(sOut_tmp);

  Bit_Slice_out1 <= sOut_tmp_unsigned(1 DOWNTO 0);

  moveOn <= std_logic_vector(Bit_Slice_out1);

  sOut <= sOut_tmp;

  counterOut <= counterOut_tmp;

  CONV_DEBUGOUTTAG_2_debugID <= CONV_DEBUGOUTTAG_2_debugID_tmp;

END rtl;

