-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_zWeAdapter_block.vhd
-- Created: 2025-10-22 15:46:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_zWeAdapter_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/DataMemMask/DataMem/zAddapter/zWeAdapter
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_zWeAdapter_block IS
  PORT( weIn                              :   IN    std_logic_vector(8 DOWNTO 0);  -- boolean [9]
        zSelIn                            :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
        active                            :   IN    std_logic;
        weOut                             :   OUT   std_logic_vector(17 DOWNTO 0)  -- boolean [18]
        );
END MyProc_src_zWeAdapter_block;


ARCHITECTURE rtl OF MyProc_src_zWeAdapter_block IS

BEGIN
  dnnfpgaDatamemlibZAdapterslib_c1_segj1SdX44fH6wbTQ1Cm1cC_zWeAda_output : PROCESS (active, weIn, zSelIn)
    VARIABLE selT : std_logic_vector(8 DOWNTO 0);
    VARIABLE weOutT : matrix_of_std_logic(0 TO 8, 0 TO 1);
    VARIABLE t_0 : std_logic_vector(17 DOWNTO 0);
    VARIABLE cast_temp : unsigned(7 DOWNTO 0);
    VARIABLE cast_temp_0 : unsigned(15 DOWNTO 0);
    VARIABLE mul_temp : unsigned(15 DOWNTO 0);
    VARIABLE flat_idx : INTEGER;
  BEGIN
    cast_temp := to_unsigned(16#00#, 8);
    cast_temp_0 := to_unsigned(16#0000#, 16);
    mul_temp := to_unsigned(16#0000#, 16);
    flat_idx := 0;

    FOR t_1 IN 0 TO 8 LOOP
      selT(t_1) := zSelIn(t_1);
    END LOOP;


    FOR i IN 0 TO 1 LOOP
      FOR i2 IN 0 TO 8 LOOP
        weOutT(i2, i) := '0';
      END LOOP;
    END LOOP;


    FOR ibx IN 0 TO 8 LOOP
      IF active = '1' THEN 
        IF selT(ibx) /= '0' THEN 
          weOutT(ibx, 0) := '0';
          weOutT(ibx, 1) := weIn(ibx);
        ELSE 
          weOutT(ibx, 0) := weIn(ibx);
          weOutT(ibx, 1) := '0';
        END IF;
      ELSE 
        FOR t_3 IN 0 TO 1 LOOP
          weOutT(ibx, t_3) := weIn(ibx);
        END LOOP;
      END IF;
    END LOOP;


    FOR i_0 IN 0 TO 1 LOOP
      FOR i2_0 IN 0 TO 8 LOOP
        cast_temp := unsigned(resize(to_signed(i_0, 32), 8));
        cast_temp_0 := unsigned(resize(to_signed(i2_0, 32), 16));
        mul_temp := cast_temp * to_unsigned(16#09#, 8);
        flat_idx := to_integer(mul_temp + cast_temp_0);
        t_0(flat_idx) := weOutT(i2_0, i_0);
      END LOOP;
    END LOOP;


    FOR t_2 IN 0 TO 17 LOOP
      weOut(t_2) <= t_0(t_2);
    END LOOP;

  END PROCESS dnnfpgaDatamemlibZAdapterslib_c1_segj1SdX44fH6wbTQ1Cm1cC_zWeAda_output;


END rtl;

