-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_block4.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_block4
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/NoOp_ InstructionStack/Subsystem
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem_block4 IS
  PORT( backBus_Deq                       :   IN    std_logic;
        backBus_Valid                     :   IN    std_logic;
        sendValid                         :   IN    std_logic;
        sendPayload_oneBit                :   IN    std_logic;
        sendDeq                           :   IN    std_logic;
        backValid                         :   OUT   std_logic;
        backDeq                           :   OUT   std_logic;
        sendBus_Valid                     :   OUT   std_logic;
        sendBus_Payload_oneBit            :   OUT   std_logic;
        sendBus_Deq                       :   OUT   std_logic
        );
END MyProc_src_Subsystem_block4;


ARCHITECTURE rtl OF MyProc_src_Subsystem_block4 IS

  -- Signals
  SIGNAL Valid                            : std_logic;
  SIGNAL Deq                              : std_logic;

BEGIN
  Valid <= backBus_Valid;

  backValid <= Valid;

  Deq <= backBus_Deq;

  backDeq <= Deq;

  sendBus_Valid <= sendValid;

  sendBus_Payload_oneBit <= sendPayload_oneBit;

  sendBus_Deq <= sendDeq;

END rtl;

