-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_writeSelect1_block.vhd
-- Created: 2025-10-22 15:46:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_writeSelect1_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/writeSelect1
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_writeSelect1_block IS
  PORT( WrValid1                          :   IN    std_logic;
        WrValid2                          :   IN    std_logic;
        WrSelect                          :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
        );
END MyProc_src_writeSelect1_block;


ARCHITECTURE rtl OF MyProc_src_writeSelect1_block IS

  -- Signals
  SIGNAL WrSelect_tmp                     : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  dnnfpgacnn4integrationbeta2_c11_writeSelect1_output : PROCESS (WrValid1, WrValid2)
  BEGIN
    IF WrValid1 = '1' THEN 
      WrSelect_tmp <= to_unsigned(16#0#, 2);
    ELSIF WrValid2 = '1' THEN 
      WrSelect_tmp <= to_unsigned(16#1#, 2);
    ELSE 
      WrSelect_tmp <= to_unsigned(16#2#, 2);
    END IF;
  END PROCESS dnnfpgacnn4integrationbeta2_c11_writeSelect1_output;


  WrSelect <= std_logic_vector(WrSelect_tmp);

END rtl;

