-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_For_Each_Subsystem.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_For_Each_Subsystem
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FWFT_FIFO_Pipeline_Layer/HDL_FWFT_FIFO4/For Each 
-- Subsyste
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_For_Each_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Push                              :   IN    std_logic;
        Pop                               :   IN    std_logic;
        u                                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Empty                             :   OUT   std_logic;
        Full                              :   OUT   std_logic;
        Num                               :   OUT   std_logic_vector(4 DOWNTO 0)  -- ufix5
        );
END MyProc_src_For_Each_Subsystem;


ARCHITECTURE rtl OF MyProc_src_For_Each_Subsystem IS

  -- Component Declarations
  COMPONENT MyProc_src_HDL_FIFO_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Push                            :   IN    std_logic;
          Pop                             :   IN    std_logic;
          Out_rsvd                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Empty                           :   OUT   std_logic;
          Full                            :   OUT   std_logic;
          Num                             :   OUT   std_logic_vector(4 DOWNTO 0)  -- ufix5
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_HDL_FIFO_block2
    USE ENTITY work.MyProc_src_HDL_FIFO_block2(rtl);

  -- Signals
  SIGNAL HDL_FIFO_out1                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL HDL_FIFO_out2deadOut             : std_logic;
  SIGNAL HDL_FIFO_out3deadOut             : std_logic;
  SIGNAL wr_fifo_cntdeadOut               : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL HDL_FIFO_out2                    : std_logic;
  SIGNAL HDL_FIFO_out3                    : std_logic;
  SIGNAL wr_fifo_cnt                      : unsigned(4 DOWNTO 0);  -- ufix5

BEGIN
  u_HDL_FIFO : MyProc_src_HDL_FIFO_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => In1,  -- uint8
              Push => Push,
              Pop => Pop,
              Out_rsvd => HDL_FIFO_out1,  -- uint8
              Empty => HDL_FIFO_out2deadOut,
              Full => HDL_FIFO_out3deadOut,
              Num => wr_fifo_cntdeadOut  -- ufix5
              );

  HDL_FIFO_out2 <= '0';

  Empty <= HDL_FIFO_out2;

  HDL_FIFO_out3 <= '0';

  Full <= HDL_FIFO_out3;

  wr_fifo_cnt <= to_unsigned(16#00#, 5);

  Num <= std_logic_vector(wr_fifo_cnt);

  u <= HDL_FIFO_out1;

END rtl;

