-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_FC_Scheduler.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_FC_Scheduler
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/Subsystem/FC_Scheduler
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_FC_Scheduler IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        start                             :   IN    std_logic;
        validIn                           :   IN    std_logic;
        IMdone                            :   IN    std_logic;
        IPdone                            :   IN    std_logic;
        FCLayerDone                       :   IN    std_logic;
        FCdone                            :   IN    std_logic;
        OPdone                            :   IN    std_logic;
        opImageCount                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_instrCount                :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        payload_srcAddr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_dstAddr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadValid                      :   IN    std_logic;
        canSendDone                       :   IN    std_logic;
        readyOut                          :   OUT   std_logic;
        IMstart                           :   OUT   std_logic;
        moveOn                            :   OUT   std_logic;
        IPstart                           :   OUT   std_logic;
        IPvalid                           :   OUT   std_logic;
        FCstart                           :   OUT   std_logic;
        FCLayerStart                      :   OUT   std_logic;
        FCLayerRst                        :   OUT   std_logic;
        FCvalid                           :   OUT   std_logic;
        IPDDRaddr                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        OPstart                           :   OUT   std_logic;
        OPvalid                           :   OUT   std_logic;
        OPDDRaddr                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        stateOut                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        doneOut                           :   OUT   std_logic;
        payloadDeq                        :   OUT   std_logic;
        sendDone                          :   OUT   std_logic;
        RUNNING                           :   OUT   std_logic
        );
END MyProc_src_FC_Scheduler;


ARCHITECTURE rtl OF MyProc_src_FC_Scheduler IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL opImageCount_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_instrCount_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL payload_srcAddr_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_dstAddr_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL readyOutdeadOut                  : std_logic;
  SIGNAL IPvaliddeadOut                   : std_logic;
  SIGNAL IPDDRaddr_tmp                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL OPDDRaddr_tmp                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL stateOutdeadOut                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL doneOutdeadOut                   : std_logic;
  SIGNAL RUNNINGdeadOut                   : std_logic;
  SIGNAL ipAddr                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL opAddr                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL imageCounter                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL layerCounter                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL fcLayerCount                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state                            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL running_1                        : std_logic;
  SIGNAL ipAddr_next                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL opAddr_next                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL imageCounter_next                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL layerCounter_next                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL fcLayerCount_next                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state_next                       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL running_next                     : std_logic;
  SIGNAL stateOut_tmp                     : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  readyOut <= '0';

  opImageCount_unsigned <= unsigned(opImageCount);

  payload_instrCount_unsigned <= unsigned(payload_instrCount);

  payload_srcAddr_unsigned <= unsigned(payload_srcAddr);

  payload_dstAddr_unsigned <= unsigned(payload_dstAddr);

  dnnfpgaFCModuleCNN5_c346_FC_Scheduler_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ipAddr <= to_unsigned(16#00000000#, 32);
      opAddr <= to_unsigned(16#00000000#, 32);
      imageCounter <= to_unsigned(16#00000000#, 32);
      layerCounter <= to_unsigned(16#00#, 8);
      fcLayerCount <= to_unsigned(16#00#, 8);
      state <= to_unsigned(16#0#, 4);
      running_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ipAddr <= ipAddr_next;
        opAddr <= opAddr_next;
        imageCounter <= imageCounter_next;
        layerCounter <= layerCounter_next;
        fcLayerCount <= fcLayerCount_next;
        state <= state_next;
        running_1 <= running_next;
      END IF;
    END IF;
  END PROCESS dnnfpgaFCModuleCNN5_c346_FC_Scheduler_process;

  dnnfpgaFCModuleCNN5_c346_FC_Scheduler_output : PROCESS (FCLayerDone, FCdone, IMdone, IPdone, OPdone, canSendDone, fcLayerCount,
       imageCounter, ipAddr, layerCounter, opAddr, payloadValid,
       payload_dstAddr_unsigned, payload_instrCount_unsigned,
       payload_srcAddr_unsigned, running_1, start, state)
    VARIABLE add_temp : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(8 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(0, 33);
    add_temp_0 := to_unsigned(16#000#, 9);
    ipAddr_next <= ipAddr;
    opAddr_next <= opAddr;
    imageCounter_next <= imageCounter;
    layerCounter_next <= layerCounter;
    fcLayerCount_next <= fcLayerCount;
    running_next <= running_1;
    payloadDeq <= '0';
    sendDone <= '0';
    -- state machine
    -- State Memory Encoding
    -- output
    -- state machine definitions
    CASE state IS
      WHEN "0000" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
        --opAddr = uint32(0);
        imageCounter_next <= to_unsigned(16#00000000#, 32);
      WHEN "0001" =>
        readyOutdeadOut <= '1';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "0010" =>
        readyOutdeadOut <= '0';
        IMstart <= '1';
        moveOn <= '1';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "0011" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "0100" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '1';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
        add_temp := resize(imageCounter, 33) + to_unsigned(1, 33);
        IF add_temp(32) /= '0' THEN 
          imageCounter_next <= X"FFFFFFFF";
        ELSE 
          imageCounter_next <= add_temp(31 DOWNTO 0);
        END IF;
      WHEN "0101" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '1';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "0110" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '1';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "0111" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        -- Skip the move on for first layer as the instructions are already
        -- there, thus it doesn't need to move on for the next instructions
        moveOn <= hdlcoder_to_stdlogic( NOT (layerCounter = to_unsigned(16#00000000#, 8)));
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '1';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '1';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "1000" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '1';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "1001" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '1';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '1';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "1010" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '1';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
        --         if imageCounter == uint32(1)
        --             opAddr = opDDRbase;
        --         else
        --             opAddr = opAddr + opDDRoffset;
        --         end        
      WHEN "1011" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '1';
        doneOutdeadOut <= '0';
      WHEN "1100" =>
        readyOutdeadOut <= '1';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
      WHEN "1101" =>
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '1';
        --opAddr = uint32(0);
        imageCounter_next <= to_unsigned(16#00000000#, 32);
      WHEN OTHERS => 
        readyOutdeadOut <= '0';
        IMstart <= '0';
        moveOn <= '0';
        IPstart <= '0';
        FCstart <= '0';
        FCLayerStart <= '0';
        FCLayerRst <= '0';
        OPstart <= '0';
        IPvaliddeadOut <= '0';
        FCvalid <= '0';
        OPvalid <= '0';
        doneOutdeadOut <= '0';
        --opAddr = uint32(0);
        imageCounter_next <= to_unsigned(16#00000000#, 32);
    END CASE;
    -- state transition
    CASE state IS
      WHEN "0000" =>
        IF start = '1' THEN 
          state_next <= to_unsigned(16#1#, 4);
        ELSE 
          state_next <= to_unsigned(16#0#, 4);
        END IF;
      WHEN "0001" =>
        IF payloadValid = '1' THEN 
          ipAddr_next <= payload_srcAddr_unsigned;
          opAddr_next <= payload_dstAddr_unsigned;
          IF payload_instrCount_unsigned(15 DOWNTO 8) /= "00000000" THEN 
            fcLayerCount_next <= "11111111";
          ELSE 
            fcLayerCount_next <= payload_instrCount_unsigned(7 DOWNTO 0);
          END IF;
          payloadDeq <= '1';
          state_next <= to_unsigned(16#2#, 4);
          running_next <= '1';
        ELSE 
          state_next <= to_unsigned(16#1#, 4);
        END IF;
      WHEN "0010" =>
        state_next <= to_unsigned(16#3#, 4);
      WHEN "0011" =>
        IF IMdone = '1' THEN 
          state_next <= to_unsigned(16#4#, 4);
        ELSE 
          state_next <= to_unsigned(16#3#, 4);
        END IF;
      WHEN "0100" =>
        state_next <= to_unsigned(16#5#, 4);
      WHEN "0101" =>
        IF IPdone = '1' THEN 
          state_next <= to_unsigned(16#6#, 4);
        ELSE 
          state_next <= to_unsigned(16#5#, 4);
        END IF;
      WHEN "0110" =>
        state_next <= to_unsigned(16#7#, 4);
        layerCounter_next <= to_unsigned(16#00#, 8);
      WHEN "0111" =>
        state_next <= to_unsigned(16#8#, 4);
        add_temp_0 := resize(layerCounter, 9) + to_unsigned(16#001#, 9);
        IF add_temp_0(8) /= '0' THEN 
          layerCounter_next <= "11111111";
        ELSE 
          layerCounter_next <= add_temp_0(7 DOWNTO 0);
        END IF;
      WHEN "1000" =>
        IF FCLayerDone = '1' THEN 
          IF layerCounter < fcLayerCount THEN 
            state_next <= to_unsigned(16#7#, 4);
          ELSE 
            state_next <= to_unsigned(16#9#, 4);
          END IF;
        ELSE 
          state_next <= to_unsigned(16#8#, 4);
        END IF;
      WHEN "1001" =>
        IF FCdone = '1' THEN 
          state_next <= to_unsigned(16#A#, 4);
        ELSE 
          state_next <= to_unsigned(16#9#, 4);
        END IF;
      WHEN "1010" =>
        state_next <= to_unsigned(16#B#, 4);
      WHEN "1011" =>
        IF OPdone = '1' THEN 
          state_next <= to_unsigned(16#C#, 4);
        ELSE 
          state_next <= to_unsigned(16#B#, 4);
        END IF;
      WHEN "1100" =>
        IF canSendDone = '1' THEN 
          sendDone <= '1';
          running_next <= '0';
          state_next <= to_unsigned(16#1#, 4);
        ELSE 
          state_next <= to_unsigned(16#C#, 4);
        END IF;
        --         if imageCounter == opImageCount
        --             nextState = INIT1;
        --         elseif validIn
        --             nextState = IM_START;
        --         else
        --             nextState = DONE;
        --         end        
      WHEN "1101" =>
        IF start = '1' THEN 
          state_next <= to_unsigned(16#1#, 4);
        ELSE 
          state_next <= to_unsigned(16#D#, 4);
        END IF;
      WHEN OTHERS => 
        state_next <= to_unsigned(16#0#, 4);
    END CASE;
    IPDDRaddr_tmp <= ipAddr;
    OPDDRaddr_tmp <= opAddr;
    stateOutdeadOut <= state;
    RUNNINGdeadOut <= running_1;
  END PROCESS dnnfpgaFCModuleCNN5_c346_FC_Scheduler_output;


  IPvalid <= '0';

  IPDDRaddr <= std_logic_vector(IPDDRaddr_tmp);

  OPDDRaddr <= std_logic_vector(OPDDRaddr_tmp);

  stateOut_tmp <= to_unsigned(16#0#, 4);

  stateOut <= std_logic_vector(stateOut_tmp);

  doneOut <= '0';

  RUNNING <= '0';

END rtl;

