-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_StackLogic.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_StackLogic
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Output_InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackLogic/StackLogic
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_StackLogic IS
  PORT( payloadConst_addr                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_sizeInBytes          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_id                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        payloadConst_isLast               :   IN    std_logic;
        cmd_payload_words                 :   IN    vector_of_std_logic_vector32(0 TO 6);  -- uint32 [7]
        cmd_cmd                           :   IN    T_IStackCmd;  -- enum type IStackCmd (5 enums)
        cmd_instr_cmd                     :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        cmd_instr_src0                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        cmd_instr_src1                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        cmd_instr_dst0                    :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        cmd_instr_src0Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        cmd_instr_src1Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        cmd_instr_dst0Mode                :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        cmd_instr_epoch                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        cmdValid                          :   IN    std_logic;
        wrMode                            :   IN    std_logic;
        clear                             :   OUT   std_logic;
        deqCmd                            :   OUT   std_logic;
        enq                               :   OUT   std_logic;
        instr_cmd                         :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        instr_src0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src1                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_dst0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_src1Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_dst0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_epoch                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_addr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_sizeInBytes               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_id                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_isLast                    :   OUT   std_logic;
        wrModeNext                        :   OUT   std_logic;
        wrModeEn                          :   OUT   std_logic
        );
END MyProc_src_StackLogic;


ARCHITECTURE rtl OF MyProc_src_StackLogic IS

  -- Signals
  SIGNAL payloadConst_addr_unsigned       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_sizeInBytes_unsigned : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_id_unsigned         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL cmd_payload_words_unsigned       : vector_of_unsigned32(0 TO 6);  -- uint32 [7]
  SIGNAL cmd_instr_src0_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL cmd_instr_src1_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL cmd_instr_dst0_unsigned          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL cmd_instr_epoch_unsigned         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL instr_src0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_src1_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_dst0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_epoch_tmp                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payload_addr_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_sizeInBytes_tmp          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_id_tmp                   : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  payloadConst_addr_unsigned <= unsigned(payloadConst_addr);

  payloadConst_sizeInBytes_unsigned <= unsigned(payloadConst_sizeInBytes);

  payloadConst_id_unsigned <= unsigned(payloadConst_id);

  outputgen: FOR k IN 0 TO 6 GENERATE
    cmd_payload_words_unsigned(k) <= unsigned(cmd_payload_words(k));
  END GENERATE;

  cmd_instr_src0_unsigned <= unsigned(cmd_instr_src0);

  cmd_instr_src1_unsigned <= unsigned(cmd_instr_src1);

  cmd_instr_dst0_unsigned <= unsigned(cmd_instr_dst0);

  cmd_instr_epoch_unsigned <= unsigned(cmd_instr_epoch);

  StackLogic_output : PROCESS (cmdValid, cmd_cmd, cmd_instr_cmd, cmd_instr_dst0Mode, cmd_instr_dst0_unsigned,
       cmd_instr_epoch_unsigned, cmd_instr_src0Mode, cmd_instr_src0_unsigned,
       cmd_instr_src1Mode, cmd_instr_src1_unsigned, cmd_payload_words_unsigned,
       payloadConst_addr_unsigned, payloadConst_id_unsigned,
       payloadConst_sizeInBytes_unsigned, wrMode)
    VARIABLE bs : std_logic_vector(511 DOWNTO 0);
    VARIABLE c : vector_of_unsigned32(0 TO 6);
    VARIABLE fbs : std_logic_vector(511 DOWNTO 0);
    VARIABLE fsz : unsigned(31 DOWNTO 0);
    VARIABLE bs_0 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs1 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs1_0 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs1_1 : std_logic_vector(511 DOWNTO 0);
    VARIABLE a1 : unsigned(31 DOWNTO 0);
    VARIABLE a1_0 : unsigned(7 DOWNTO 0);
    VARIABLE mask : unsigned(7 DOWNTO 0);
    VARIABLE a1_1 : unsigned(31 DOWNTO 0);
    VARIABLE mask_0 : unsigned(31 DOWNTO 0);
    VARIABLE a1_2 : unsigned(31 DOWNTO 0);
    VARIABLE mask_1 : unsigned(31 DOWNTO 0);
    VARIABLE bs_1 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs1_2 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs_2 : std_logic_vector(511 DOWNTO 0);
    VARIABLE bs_3 : std_logic_vector(511 DOWNTO 0);
    VARIABLE t_6 : std_logic;
    VARIABLE t_7 : std_logic;
    VARIABLE add_temp : vector_of_signed32(0 TO 511);
    VARIABLE cast : vector_of_unsigned32(0 TO 511);
    VARIABLE sub_cast : vector_of_signed33(0 TO 511);
    VARIABLE sub_temp : vector_of_signed33(0 TO 511);
    VARIABLE cast_0 : vector_of_unsigned32(0 TO 511);
    VARIABLE cast_1 : vector_of_unsigned32(0 TO 7);
    VARIABLE sll_temp : vector_of_signed32(0 TO 7);
    VARIABLE slice_cast : vector_of_unsigned32(0 TO 31);
    VARIABLE slice_cast_0 : vector_of_unsigned32(0 TO 31);
    VARIABLE cast_2 : vector_of_signed32(0 TO 7);
    VARIABLE mask_2 : vector_of_unsigned8(0 TO 7);
    VARIABLE cast_3 : vector_of_signed32(0 TO 7);
    VARIABLE cast_4 : vector_of_signed32(0 TO 7);
    VARIABLE cast_5 : vector_of_signed32(0 TO 7);
    VARIABLE cast_6 : vector_of_signed32(0 TO 7);
    VARIABLE cast_7 : vector_of_signed32(0 TO 7);
    VARIABLE add_temp_0 : vector_of_unsigned33(0 TO 6);
    VARIABLE cast_8 : vector_of_unsigned32(0 TO 31);
    VARIABLE cast_9 : vector_of_unsigned32(0 TO 31);
  BEGIN
    fsz := to_unsigned(16#00000000#, 32);
    t_6 := '0';
    a1 := to_unsigned(16#00000000#, 32);
    mask_0 := to_unsigned(16#00000000#, 32);
    mask_1 := to_unsigned(16#00000000#, 32);
    t_7 := '0';
    mask := to_unsigned(16#00#, 8);
    enq <= '0';
    clear <= '0';
    deqCmd <= '0';
    instr_cmd <= DFLT;
    instr_src0_tmp <= to_unsigned(16#000#, 10);
    instr_src1_tmp <= to_unsigned(16#000#, 10);
    instr_dst0_tmp <= to_unsigned(16#000#, 10);
    instr_src0Mode <= Direct;
    instr_src1Mode <= Direct;
    instr_dst0Mode <= Direct;
    instr_epoch_tmp <= to_unsigned(16#00#, 8);
    a1_2 := to_unsigned(16#00000000#, 32);
    a1_1 := to_unsigned(16#00000000#, 32);
    a1_0 := to_unsigned(16#00#, 8);
    payload_isLast <= '0';
    wrModeEn <= '0';
    wrModeNext <= '0';
    IF (cmdValid AND wrMode) = '1' THEN 
      IF cmd_cmd = CLR THEN 
        clear <= '1';
      END IF;
      IF cmd_cmd = WR THEN 
        instr_cmd <= cmd_instr_cmd;
        instr_src0_tmp <= cmd_instr_src0_unsigned;
        instr_src1_tmp <= cmd_instr_src1_unsigned;
        instr_dst0_tmp <= cmd_instr_dst0_unsigned;
        instr_src0Mode <= cmd_instr_src0Mode;
        instr_src1Mode <= cmd_instr_src1Mode;
        instr_dst0Mode <= cmd_instr_dst0Mode;
        instr_epoch_tmp <= cmd_instr_epoch_unsigned;

        FOR t_0 IN 0 TO 6 LOOP
          c(t_0) := cmd_payload_words_unsigned(t_0);
        END LOOP;


        FOR t_1 IN 0 TO 511 LOOP
          fbs(t_1) := '0';
        END LOOP;

        fsz := to_unsigned(16#00000000#, 32);

        FOR n IN 0 TO 6 LOOP

          FOR t_2 IN 0 TO 511 LOOP
            bs_1(t_2) := '0';
          END LOOP;

          a1 := c(n);

          FOR bm1 IN 0 TO 31 LOOP
            slice_cast(bm1) := unsigned(to_signed(bm1, 32));
            slice_cast_0(bm1) := unsigned(to_signed(bm1, 32));
            bs_1(511 - bm1) := a1(to_integer(slice_cast(bm1)));
          END LOOP;


          FOR t_3 IN 0 TO 511 LOOP
            t_7 := fbs(t_3);
            fbs(t_3) := '0';
            bs1_2(t_3) := t_7;
          END LOOP;


          FOR i_1 IN 0 TO 511 LOOP
            IF (i_1 + 1) <= to_signed(16#000001E0#, 32) THEN 
              fbs(i_1) := bs1_2(i_1 + 32);
            END IF;
            fbs(i_1) := fbs(i_1) OR bs_1(i_1);
          END LOOP;

          add_temp_0(n) := resize(fsz, 33) + to_unsigned(32, 33);
          IF add_temp_0(n)(32) /= '0' THEN 
            fsz := X"FFFFFFFF";
          ELSE 
            fsz := add_temp_0(n)(31 DOWNTO 0);
          END IF;
        END LOOP;


        FOR i_2 IN 0 TO 511 LOOP
          t_6 := '0';
          add_temp(i_2) := to_signed(i_2 + 1, 32);
          cast(i_2) := unsigned(add_temp(i_2));
          sub_cast(i_2) := signed(resize(fsz, 33));
          sub_temp(i_2) := to_signed(512, 33) - sub_cast(i_2);
          IF sub_temp(i_2)(32) = '1' THEN 
            cast_0(i_2) := X"00000000";
          ELSE 
            cast_0(i_2) := unsigned(sub_temp(i_2)(31 DOWNTO 0));
          END IF;
          IF cast(i_2) <= cast_0(i_2) THEN 
            t_6 := '0';
          END IF;
          t_6 := t_6 OR fbs(i_2);
          bs(i_2) := t_6;
          bs_0(i_2) := '0';
          bs1(i_2) := t_6;
          IF (i_2 + 1) >= to_signed(16#00000002#, 32) THEN 
            bs_0(i_2) := bs1(i_2 - 1);
          END IF;
        END LOOP;

        a1_0 := payloadConst_id_unsigned;

        FOR bm1_0 IN 0 TO 7 LOOP
          cast_1(bm1_0) := unsigned(to_signed(bm1_0, 32));
          sll_temp(bm1_0) := to_signed(16#00000001#, 32) sll to_integer(cast_1(bm1_0));
          mask := unsigned(sll_temp(bm1_0)(7 DOWNTO 0));
          IF bs_0(511 - bm1_0) = '1' THEN 
            cast_5(bm1_0) := signed(resize(a1_0, 32));
            cast_6(bm1_0) := signed(resize(mask, 32));
            cast_7(bm1_0) := cast_5(bm1_0) OR cast_6(bm1_0);
            a1_0 := unsigned(cast_7(bm1_0)(7 DOWNTO 0));
          ELSE 
            cast_2(bm1_0) := signed(resize(a1_0, 32));
            mask_2(bm1_0) :=  NOT mask;
            cast_3(bm1_0) := signed(resize(mask_2(bm1_0), 32));
            cast_4(bm1_0) := cast_2(bm1_0) AND cast_3(bm1_0);
            a1_0 := unsigned(cast_4(bm1_0)(7 DOWNTO 0));
          END IF;
        END LOOP;


        FOR t_4 IN 0 TO 511 LOOP
          bs_2(t_4) := '0';
          bs1_0(t_4) := bs_0(t_4);
        END LOOP;


        FOR i IN 0 TO 504 LOOP
          IF (i + 8) >= to_signed(16#00000009#, 32) THEN 
            bs_2(i + 7) := bs1_0(i - 1);
          END IF;
        END LOOP;

        a1_1 := payloadConst_sizeInBytes_unsigned;

        FOR bm1_1 IN 0 TO 31 LOOP
          cast_8(bm1_1) := unsigned(to_signed(bm1_1, 32));
          mask_0 := to_unsigned(16#00000001#, 32) sll to_integer(cast_8(bm1_1));
          IF bs_2(511 - bm1_1) = '1' THEN 
            a1_1 := a1_1 OR mask_0;
          ELSE 
            a1_1 := a1_1 AND ( NOT mask_0);
          END IF;
        END LOOP;


        FOR t_5 IN 0 TO 511 LOOP
          bs_3(t_5) := '0';
          bs1_1(t_5) := bs_2(t_5);
        END LOOP;


        FOR i_0 IN 0 TO 480 LOOP
          IF (i_0 + 32) >= to_signed(16#00000021#, 32) THEN 
            bs_3(i_0 + 31) := bs1_1(i_0 - 1);
          END IF;
        END LOOP;

        a1_2 := payloadConst_addr_unsigned;

        FOR bm1_2 IN 0 TO 31 LOOP
          cast_9(bm1_2) := unsigned(to_signed(bm1_2, 32));
          mask_1 := to_unsigned(16#00000001#, 32) sll to_integer(cast_9(bm1_2));
          IF bs_3(511 - bm1_2) = '1' THEN 
            a1_2 := a1_2 OR mask_1;
          ELSE 
            a1_2 := a1_2 AND ( NOT mask_1);
          END IF;
        END LOOP;

        payload_isLast <= bs(511);
        enq <= '1';
      END IF;
      IF cmd_cmd = LST THEN 
        wrModeEn <= '1';
      END IF;
      deqCmd <= '1';
    END IF;
    IF (cmdValid AND ( NOT wrMode)) = '1' THEN 
      IF cmd_cmd = CLR THEN 
        clear <= '1';
        wrModeNext <= '1';
        wrModeEn <= '1';
      END IF;
      deqCmd <= '1';
    END IF;
    payload_addr_tmp <= a1_2;
    payload_sizeInBytes_tmp <= a1_1;
    payload_id_tmp <= a1_0;
  END PROCESS StackLogic_output;


  instr_src0 <= std_logic_vector(instr_src0_tmp);

  instr_src1 <= std_logic_vector(instr_src1_tmp);

  instr_dst0 <= std_logic_vector(instr_dst0_tmp);

  instr_epoch <= std_logic_vector(instr_epoch_tmp);

  payload_addr <= std_logic_vector(payload_addr_tmp);

  payload_sizeInBytes <= std_logic_vector(payload_sizeInBytes_tmp);

  payload_id <= std_logic_vector(payload_id_tmp);

END rtl;

