-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Delay4_block.vhd
-- Created: 2025-10-22 15:46:42
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Delay4_block
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/DataMemSingleCycleAccumulator/Result 
-- Mem1/Delay
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Delay4_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    vector_of_std_logic_vector32(0 TO 3);  -- single [4]
        alpharesultRdEn                   :   IN    std_logic;
        Out1                              :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- single [4]
        );
END MyProc_src_Delay4_block;


ARCHITECTURE rtl OF MyProc_src_Delay4_block IS

  -- Signals
  SIGNAL Delay3_out1                      : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Delay3_ectrl                     : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]

BEGIN
  
  Delay3_ectrl <= Delay3_out1 WHEN alpharesultRdEn = '0' ELSE
      In1;

  Delay3_lowered_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Delay3_ectrl;
      END IF;
    END IF;
  END PROCESS Delay3_lowered_process;


  Out1 <= Delay3_out1;

END rtl;

