-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_createPayload_block1.vhd
-- Created: 2025-10-22 15:46:35
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_createPayload_block1
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/NoOp_ InstructionStack/Subsystem Reference1/Subsystem Reference1/createPayload/createPayload
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_createPayload_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        inputAddrOffsetIn                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        top_cmd                           :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        top_src0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src1                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_dst0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_src1Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_dst0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_epoch                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        topValid                          :   IN    std_logic;
        payloadIn_oneBit                  :   IN    std_logic;
        outputAddrOffsetIn                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputAddrOffsetPrevIn            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputTotalLSBsIn                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        state                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        payloadConst_oneBit               :   IN    std_logic;
        topDeq                            :   OUT   std_logic;
        instr_cmd                         :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        instr_src0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src1                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_dst0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_src1Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_dst0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_epoch                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_oneBit                    :   OUT   std_logic;
        valid                             :   OUT   std_logic;
        advance                           :   OUT   std_logic;
        toIdle                            :   OUT   std_logic
        );
END MyProc_src_createPayload_block1;


ARCHITECTURE rtl OF MyProc_src_createPayload_block1 IS

  -- Signals
  SIGNAL inputAddrOffsetIn_unsigned       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL top_src0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_src1_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_dst0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_epoch_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL outputAddrOffsetIn_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetPrevIn_unsigned  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputTotalLSBsIn_unsigned       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL state_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL instr_src0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_src1_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_dst0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_epoch_tmp                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL topReg_cmd                       : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL topReg_src0                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src1                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_dst0                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src0Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_src1Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_dst0Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_epoch                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadReg_oneBit                : std_logic;
  SIGNAL topReg_cmd_next                  : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL topReg_src0_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src1_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_dst0_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src0Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_src1Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_dst0Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_epoch_next                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadReg_oneBit_next           : std_logic;

BEGIN
  inputAddrOffsetIn_unsigned <= unsigned(inputAddrOffsetIn);

  top_src0_unsigned <= unsigned(top_src0);

  top_src1_unsigned <= unsigned(top_src1);

  top_dst0_unsigned <= unsigned(top_dst0);

  top_epoch_unsigned <= unsigned(top_epoch);

  outputAddrOffsetIn_unsigned <= unsigned(outputAddrOffsetIn);

  outputAddrOffsetPrevIn_unsigned <= unsigned(outputAddrOffsetPrevIn);

  outputTotalLSBsIn_unsigned <= unsigned(outputTotalLSBsIn);

  state_unsigned <= unsigned(state);

  createPayload_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      topReg_cmd <= DFLT;
      topReg_src0 <= to_unsigned(16#000#, 10);
      topReg_src1 <= to_unsigned(16#000#, 10);
      topReg_dst0 <= to_unsigned(16#000#, 10);
      topReg_src0Mode <= Direct;
      topReg_src1Mode <= Direct;
      topReg_dst0Mode <= Direct;
      topReg_epoch <= to_unsigned(16#00#, 8);
      payloadReg_oneBit <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        topReg_cmd <= topReg_cmd_next;
        topReg_src0 <= topReg_src0_next;
        topReg_src1 <= topReg_src1_next;
        topReg_dst0 <= topReg_dst0_next;
        topReg_src0Mode <= topReg_src0Mode_next;
        topReg_src1Mode <= topReg_src1Mode_next;
        topReg_dst0Mode <= topReg_dst0Mode_next;
        topReg_epoch <= topReg_epoch_next;
        payloadReg_oneBit <= payloadReg_oneBit_next;
      END IF;
    END IF;
  END PROCESS createPayload_process;

  createPayload_output : PROCESS (payloadIn_oneBit, payloadReg_oneBit, state_unsigned, topReg_cmd, topReg_dst0,
       topReg_dst0Mode, topReg_epoch, topReg_src0, topReg_src0Mode, topReg_src1,
       topReg_src1Mode, topValid, top_cmd, top_dst0Mode, top_dst0_unsigned,
       top_epoch_unsigned, top_src0Mode, top_src0_unsigned, top_src1Mode,
       top_src1_unsigned)
  BEGIN
    topReg_cmd_next <= topReg_cmd;
    topReg_src0_next <= topReg_src0;
    topReg_src1_next <= topReg_src1;
    topReg_dst0_next <= topReg_dst0;
    topReg_src0Mode_next <= topReg_src0Mode;
    topReg_src1Mode_next <= topReg_src1Mode;
    topReg_dst0Mode_next <= topReg_dst0Mode;
    topReg_epoch_next <= topReg_epoch;
    payloadReg_oneBit_next <= payloadReg_oneBit;
    topDeq <= '0';
    advance <= '0';
    toIdle <= '0';
    valid <= '0';
    -- If we need to increment an output address wait until the
    -- outputAddrOffset is up-to-date
    CASE state_unsigned IS
      WHEN "00000000" =>
        IF topValid = '1' THEN 
          advance <= '1';
          topReg_cmd_next <= top_cmd;
          topReg_src0_next <= top_src0_unsigned;
          topReg_src1_next <= top_src1_unsigned;
          topReg_dst0_next <= top_dst0_unsigned;
          topReg_src0Mode_next <= top_src0Mode;
          topReg_src1Mode_next <= top_src1Mode;
          topReg_dst0Mode_next <= top_dst0Mode;
          topReg_epoch_next <= top_epoch_unsigned;
          topDeq <= '1';
          --            %% conditions based on epayload are statically known so hopefully added
          --            %% regs/logic for streaming should be omitted if not needed.
          payloadReg_oneBit_next <= payloadIn_oneBit;
        END IF;
      WHEN "00000001" =>
        valid <= '1';
      WHEN "00000010" =>
        toIdle <= '1';
      WHEN OTHERS => 
        NULL;
    END CASE;
    instr_cmd <= topReg_cmd;
    instr_src0_tmp <= topReg_src0;
    instr_src1_tmp <= topReg_src1;
    instr_dst0_tmp <= topReg_dst0;
    instr_src0Mode <= topReg_src0Mode;
    instr_src1Mode <= topReg_src1Mode;
    instr_dst0Mode <= topReg_dst0Mode;
    instr_epoch_tmp <= topReg_epoch;
    payload_oneBit <= payloadReg_oneBit;
  END PROCESS createPayload_output;


  instr_src0 <= std_logic_vector(instr_src0_tmp);

  instr_src1 <= std_logic_vector(instr_src1_tmp);

  instr_dst0 <= std_logic_vector(instr_dst0_tmp);

  instr_epoch <= std_logic_vector(instr_epoch_tmp);

END rtl;

