-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_From4_block2.vhd
-- Created: 2025-10-22 15:46:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_From4_block2
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/From4
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_From4_block2 IS
  PORT( CONV_LCTAG_memDirection           :   IN    std_logic;
        CONV_LCTAG_convMode               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        CONV_LCTAG_strideMode             :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        CONV_LCTAG_reLUMode               :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        CONV_LCTAG_paddingMode            :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        CONV_LCTAG_halfInputFeatureNum    :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        CONV_LCTAG_halfOutputFeatureNum   :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        CONV_LCTAG_convTileSize           :   IN    vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        CONV_LCTAG_convTileThreadExpansionSize :   IN    vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        CONV_LCTAG_convImgSize            :   IN    vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        CONV_LCTAG_convOpSize             :   IN    vector_of_std_logic_vector9(0 TO 2);  -- ufix9 [3]
        CONV_LCTAG_leftMemSize            :   IN    vector_of_std_logic_vector6(0 TO 2);  -- ufix6 [3]
        CONV_LCTAG_rightMemSize           :   IN    vector_of_std_logic_vector6(0 TO 2);  -- ufix6 [3]
        CONV_LCTAG_stride                 :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        CONV_LCTAG_padding                :   IN    vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        CONV_LCTAG_dilation               :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        CONV_LCTAG_resultSize             :   IN    vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        CONV_LCTAG_resultSizeDivByOpW     :   IN    vector_of_std_logic_vector5(0 TO 1);  -- ufix5 [2]
        CONV_LCTAG_resultSizeDivByOpWSquared :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        CONV_LCTAG_imgSize                :   IN    vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        CONV_LCTAG_imgSizeDivByOpW        :   IN    vector_of_std_logic_vector5(0 TO 1);  -- ufix5 [2]
        CONV_LCTAG_imgSizeDivByOpWSquared :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        CONV_LCTAG_xy0                    :   IN    vector_of_std_logic_vector6(0 TO 17);  -- sfix6 [18]
        CONV_LCTAG_rxy0                   :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
        CONV_LCTAG_wAddr0                 :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        CONV_LCTAG_dw                     :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        CONV_LCTAG_dr                     :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        CONV_LCTAG_dz                     :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        CONV_LCTAG_rzLimitOriginal        :   IN    vector_of_std_logic_vector8(0 TO 1);  -- int8 [2]
        CONV_LCTAG_lrnLocalSize           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        CONV_LCTAG_lrnAlpha               :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_LCTAG_lrnBeta                :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_LCTAG_lrnK                   :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_LCTAG_lrnFeaturePadding      :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        CONV_LCTAG_convOutputFeature      :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        CONV_LCTAG_lrnPadddingSize        :   IN    vector_of_std_logic_vector11(0 TO 2);  -- ufix11 [3]
        CONV_LCTAG_inputMemZAdapterActive :   IN    std_logic;  -- ufix1
        CONV_LCTAG_activeFIFOEn           :   IN    std_logic;  -- ufix1
        CONV_LCTAG_activeFIFOMemSel       :   IN    std_logic;  -- ufix1
        CONV_LCTAG_accumulateRightMem     :   IN    std_logic;  -- ufix1
        CONV_LCTAG_finalWriteSize         :   IN    vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        CONV_LCTAG_convOpSizePlusPaddingSizeMinusOne :   IN    vector_of_std_logic_vector7(0 TO 2);  -- sfix7 [3]
        CONV_LCTAG_convImgSizeMinusOne    :   IN    vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        CONV_LCTAG_convImgSizeMinusOpSizePlusTwoPaddingSize :   IN    vector_of_std_logic_vector10(0 TO 2);  -- ufix10 [3]
        CONV_LCTAG_convTileSizeMinusOne   :   IN    vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        CONV_LCTAG_convTileSizeMinusTwo   :   IN    vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        CONV_LCTAG_convReLUValue          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        CONV_LCTAG_avgpoolMultiplier      :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_firstWritePos          :   IN    vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        CONV_LCTAG_int32ToInt8Exp         :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_int8ToSingleExp        :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_singleToInt8Exp        :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_reLUScaleExp           :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_smallPoolLayerEn       :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        CONV_LCTAG_paddingModThree        :   IN    vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        CONV_LCTAG_weightBaseAddrOffset   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_LCTAG_LegWeightBaseAddr      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_LCTAG_nextTileOffset         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_LCTAG_isMaxpoolIndexLeg      :   IN    std_logic;  -- ufix1
        CONV_LCTAG_fullFeatureSize        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_LCTAG_fullColumnsSize        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONV_LCTAG_IndexActsSelectorOffsetInit :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        CONV_LCTAG_IndexActsDimensionalOffsetsInit :   IN    vector_of_std_logic_vector2(0 TO 2);  -- ufix2 [3]
        CONV_LCTAG_tileActivationNum      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        CONV_LCTAG_lastLayer              :   IN    std_logic;  -- ufix1
        CONV_LCTAG_FirstLayer             :   IN    std_logic;  -- ufix1
        Out1_memDirection                 :   OUT   std_logic;
        Out1_convMode                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1_strideMode                   :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        Out1_reLUMode                     :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        Out1_paddingMode                  :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        Out1_halfInputFeatureNum          :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        Out1_halfOutputFeatureNum         :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        Out1_convTileSize                 :   OUT   vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        Out1_convTileThreadExpansionSize  :   OUT   vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        Out1_convImgSize                  :   OUT   vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        Out1_convOpSize                   :   OUT   vector_of_std_logic_vector9(0 TO 2);  -- ufix9 [3]
        Out1_leftMemSize                  :   OUT   vector_of_std_logic_vector6(0 TO 2);  -- ufix6 [3]
        Out1_rightMemSize                 :   OUT   vector_of_std_logic_vector6(0 TO 2);  -- ufix6 [3]
        Out1_stride                       :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        Out1_padding                      :   OUT   vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        Out1_dilation                     :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        Out1_resultSize                   :   OUT   vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        Out1_resultSizeDivByOpW           :   OUT   vector_of_std_logic_vector5(0 TO 1);  -- ufix5 [2]
        Out1_resultSizeDivByOpWSquared    :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        Out1_imgSize                      :   OUT   vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        Out1_imgSizeDivByOpW              :   OUT   vector_of_std_logic_vector5(0 TO 1);  -- ufix5 [2]
        Out1_imgSizeDivByOpWSquared       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        Out1_xy0                          :   OUT   vector_of_std_logic_vector6(0 TO 17);  -- sfix6 [18]
        Out1_rxy0                         :   OUT   vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
        Out1_wAddr0                       :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        Out1_dw                           :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        Out1_dr                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1_dz                           :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        Out1_rzLimitOriginal              :   OUT   vector_of_std_logic_vector8(0 TO 1);  -- int8 [2]
        Out1_lrnLocalSize                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1_lrnAlpha                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out1_lrnBeta                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out1_lrnK                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out1_lrnFeaturePadding            :   OUT   std_logic_vector(10 DOWNTO 0);  -- ufix11
        Out1_convOutputFeature            :   OUT   std_logic_vector(10 DOWNTO 0);  -- ufix11
        Out1_lrnPadddingSize              :   OUT   vector_of_std_logic_vector11(0 TO 2);  -- ufix11 [3]
        Out1_inputMemZAdapterActive       :   OUT   std_logic;  -- ufix1
        Out1_activeFIFOEn                 :   OUT   std_logic;  -- ufix1
        Out1_activeFIFOMemSel             :   OUT   std_logic;  -- ufix1
        Out1_accumulateRightMem           :   OUT   std_logic;  -- ufix1
        Out1_finalWriteSize               :   OUT   vector_of_std_logic_vector7(0 TO 1);  -- ufix7 [2]
        Out1_convOpSizePlusPaddingSizeMinusOne :   OUT   vector_of_std_logic_vector7(0 TO 2);  -- sfix7 [3]
        Out1_convImgSizeMinusOne          :   OUT   vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        Out1_convImgSizeMinusOpSizePlusTwoPaddingSize :   OUT   vector_of_std_logic_vector10(0 TO 2);  -- ufix10 [3]
        Out1_convTileSizeMinusOne         :   OUT   vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        Out1_convTileSizeMinusTwo         :   OUT   vector_of_std_logic_vector8(0 TO 4);  -- uint8 [5]
        Out1_convReLUValue                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out1_avgpoolMultiplier            :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_firstWritePos                :   OUT   vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        Out1_int32ToInt8Exp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_int8ToSingleExp              :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_singleToInt8Exp              :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_reLUScaleExp                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_smallPoolLayerEn             :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        Out1_paddingModThree              :   OUT   vector_of_std_logic_vector7(0 TO 3);  -- ufix7 [4]
        Out1_weightBaseAddrOffset         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1_LegWeightBaseAddr            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1_nextTileOffset               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1_isMaxpoolIndexLeg            :   OUT   std_logic;  -- ufix1
        Out1_fullFeatureSize              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1_fullColumnsSize              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1_IndexActsSelectorOffsetInit  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        Out1_IndexActsDimensionalOffsetsInit :   OUT   vector_of_std_logic_vector2(0 TO 2);  -- ufix2 [3]
        Out1_tileActivationNum            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1_lastLayer                    :   OUT   std_logic;  -- ufix1
        Out1_FirstLayer                   :   OUT   std_logic  -- ufix1
        );
END MyProc_src_From4_block2;


ARCHITECTURE rtl OF MyProc_src_From4_block2 IS

BEGIN
  Out1_memDirection <= CONV_LCTAG_memDirection;

  Out1_lrnAlpha <= CONV_LCTAG_lrnAlpha;

  Out1_lrnBeta <= CONV_LCTAG_lrnBeta;

  Out1_lrnK <= CONV_LCTAG_lrnK;

  Out1_inputMemZAdapterActive <= CONV_LCTAG_inputMemZAdapterActive;

  Out1_activeFIFOEn <= CONV_LCTAG_activeFIFOEn;

  Out1_activeFIFOMemSel <= CONV_LCTAG_activeFIFOMemSel;

  Out1_accumulateRightMem <= CONV_LCTAG_accumulateRightMem;

  Out1_convReLUValue <= CONV_LCTAG_convReLUValue;

  Out1_isMaxpoolIndexLeg <= CONV_LCTAG_isMaxpoolIndexLeg;

  Out1_lastLayer <= CONV_LCTAG_lastLayer;

  Out1_FirstLayer <= CONV_LCTAG_FirstLayer;

  Out1_convMode <= CONV_LCTAG_convMode;

  Out1_strideMode <= CONV_LCTAG_strideMode;

  Out1_reLUMode <= CONV_LCTAG_reLUMode;

  Out1_paddingMode <= CONV_LCTAG_paddingMode;

  Out1_halfInputFeatureNum <= CONV_LCTAG_halfInputFeatureNum;

  Out1_halfOutputFeatureNum <= CONV_LCTAG_halfOutputFeatureNum;

  Out1_convTileSize <= CONV_LCTAG_convTileSize;

  Out1_convTileThreadExpansionSize <= CONV_LCTAG_convTileThreadExpansionSize;

  Out1_convImgSize <= CONV_LCTAG_convImgSize;

  Out1_convOpSize <= CONV_LCTAG_convOpSize;

  Out1_leftMemSize <= CONV_LCTAG_leftMemSize;

  Out1_rightMemSize <= CONV_LCTAG_rightMemSize;

  Out1_stride <= CONV_LCTAG_stride;

  Out1_padding <= CONV_LCTAG_padding;

  Out1_dilation <= CONV_LCTAG_dilation;

  Out1_resultSize <= CONV_LCTAG_resultSize;

  Out1_resultSizeDivByOpW <= CONV_LCTAG_resultSizeDivByOpW;

  Out1_resultSizeDivByOpWSquared <= CONV_LCTAG_resultSizeDivByOpWSquared;

  Out1_imgSize <= CONV_LCTAG_imgSize;

  Out1_imgSizeDivByOpW <= CONV_LCTAG_imgSizeDivByOpW;

  Out1_imgSizeDivByOpWSquared <= CONV_LCTAG_imgSizeDivByOpWSquared;

  Out1_xy0 <= CONV_LCTAG_xy0;

  Out1_rxy0 <= CONV_LCTAG_rxy0;

  Out1_wAddr0 <= CONV_LCTAG_wAddr0;

  Out1_dw <= CONV_LCTAG_dw;

  Out1_dr <= CONV_LCTAG_dr;

  Out1_dz <= CONV_LCTAG_dz;

  Out1_rzLimitOriginal <= CONV_LCTAG_rzLimitOriginal;

  Out1_lrnLocalSize <= CONV_LCTAG_lrnLocalSize;

  Out1_lrnFeaturePadding <= CONV_LCTAG_lrnFeaturePadding;

  Out1_convOutputFeature <= CONV_LCTAG_convOutputFeature;

  Out1_lrnPadddingSize <= CONV_LCTAG_lrnPadddingSize;

  Out1_finalWriteSize <= CONV_LCTAG_finalWriteSize;

  Out1_convOpSizePlusPaddingSizeMinusOne <= CONV_LCTAG_convOpSizePlusPaddingSizeMinusOne;

  Out1_convImgSizeMinusOne <= CONV_LCTAG_convImgSizeMinusOne;

  Out1_convImgSizeMinusOpSizePlusTwoPaddingSize <= CONV_LCTAG_convImgSizeMinusOpSizePlusTwoPaddingSize;

  Out1_convTileSizeMinusOne <= CONV_LCTAG_convTileSizeMinusOne;

  Out1_convTileSizeMinusTwo <= CONV_LCTAG_convTileSizeMinusTwo;

  Out1_avgpoolMultiplier <= CONV_LCTAG_avgpoolMultiplier;

  Out1_firstWritePos <= CONV_LCTAG_firstWritePos;

  Out1_int32ToInt8Exp <= CONV_LCTAG_int32ToInt8Exp;

  Out1_int8ToSingleExp <= CONV_LCTAG_int8ToSingleExp;

  Out1_singleToInt8Exp <= CONV_LCTAG_singleToInt8Exp;

  Out1_reLUScaleExp <= CONV_LCTAG_reLUScaleExp;

  Out1_smallPoolLayerEn <= CONV_LCTAG_smallPoolLayerEn;

  Out1_paddingModThree <= CONV_LCTAG_paddingModThree;

  Out1_weightBaseAddrOffset <= CONV_LCTAG_weightBaseAddrOffset;

  Out1_LegWeightBaseAddr <= CONV_LCTAG_LegWeightBaseAddr;

  Out1_nextTileOffset <= CONV_LCTAG_nextTileOffset;

  Out1_fullFeatureSize <= CONV_LCTAG_fullFeatureSize;

  Out1_fullColumnsSize <= CONV_LCTAG_fullColumnsSize;

  Out1_IndexActsSelectorOffsetInit <= CONV_LCTAG_IndexActsSelectorOffsetInit;

  Out1_IndexActsDimensionalOffsetsInit <= CONV_LCTAG_IndexActsDimensionalOffsetsInit;

  Out1_tileActivationNum <= CONV_LCTAG_tileActivationNum;

END rtl;

