-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Global_Counter_block.vhd
-- Created: 2025-10-22 15:46:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Global_Counter_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/OutputProcessor_T/OutputProcesssorCoreBusT/PaddingLogicT/fifo2_upstream1/2D 
-- Early Turnaround Counter/Global Counte
-- Hierarchy Level: 10
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Global_Counter_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        reset_1                           :   IN    std_logic;
        enb_1                             :   IN    std_logic;
        countLimit                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        EarlierCountLimit                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        selectLimit                       :   IN    std_logic;
        countReach                        :   OUT   std_logic;
        CountValue                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        FinalStage                        :   OUT   std_logic
        );
END MyProc_src_Global_Counter_block;


ARCHITECTURE rtl OF MyProc_src_Global_Counter_block IS

  -- Signals
  SIGNAL countLimit_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion_out1        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL EarlierCountLimit_unsigned       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion1_out1       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Multiport_Switch_out1            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Relational_Operator2_out1        : std_logic;
  SIGNAL Subtract_out1                    : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  countLimit_unsigned <= unsigned(countLimit);

  Data_Type_Conversion_out1 <= countLimit_unsigned(15 DOWNTO 0);

  EarlierCountLimit_unsigned <= unsigned(EarlierCountLimit);

  Data_Type_Conversion1_out1 <= EarlierCountLimit_unsigned(15 DOWNTO 0);

  
  Multiport_Switch_out1 <= Data_Type_Conversion_out1 WHEN selectLimit = '0' ELSE
      Data_Type_Conversion1_out1;

  Logical_Operator_out1 <= Logical_Operator1_out1 OR reset_1;

  -- Free running, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#0001#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator_out1 = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(16#0001#, 16);
        ELSIF enb_1 = '1' THEN 
          HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#0001#, 16);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Relational_Operator2_out1 <= '1' WHEN HDL_Counter_out1 >= Multiport_Switch_out1 ELSE
      '0';

  Logical_Operator1_out1 <= Relational_Operator2_out1 AND enb_1;

  countReach <= Logical_Operator1_out1;

  Subtract_out1 <= to_unsigned(16#0000#, 16);

  CountValue <= std_logic_vector(Subtract_out1);

  FinalStage <= Relational_Operator2_out1;

END rtl;

