-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_FIFO1_block28.vhd
-- Created: 2025-10-22 15:46:49
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_FIFO1_block28
-- Source Path: testbench/DUT/DUT/Adder Module/Dummy Adder Kernel/addKernel/ModRecv1/FIFO1
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_FIFO1_block28 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enq                               :   IN    std_logic;
        dIn_src0Addr                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_src1Addr                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_dstAddr                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_exponent                      :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        dIn_exponentIn1                   :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        dIn_exponentIn2                   :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        dIn_reluValue                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_reluScaleExp                  :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
        dIn_single2Int8Exp                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        dIn_int82SingleExp                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        deq                               :   IN    std_logic;
        dOut_src0Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dOut_src1Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dOut_dstAddr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dOut_exponent                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        dOut_exponentIn1                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        dOut_exponentIn2                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        dOut_reluValue                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dOut_reluScaleExp                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
        dOut_single2Int8Exp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        dOut_int82SingleExp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        notEmpty                          :   OUT   std_logic;
        notFull                           :   OUT   std_logic
        );
END MyProc_src_FIFO1_block28;


ARCHITECTURE rtl OF MyProc_src_FIFO1_block28 IS

  -- Component Declarations
  COMPONENT MyProc_src_calcData_INSTR_block86
    PORT( deq                             :   IN    std_logic;
          enq                             :   IN    std_logic;
          dIn_src0Addr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_src1Addr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_dstAddr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_exponent                    :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          dIn_exponentIn1                 :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          dIn_exponentIn2                 :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          dIn_reluValue                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_reluScaleExp                :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
          dIn_single2Int8Exp              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          dIn_int82SingleExp              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d0In_src0Addr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d0In_src1Addr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d0In_dstAddr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d0In_exponent                   :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d0In_exponentIn1                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d0In_exponentIn2                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d0In_reluValue                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d0In_reluScaleExp               :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
          d0In_single2Int8Exp             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d0In_int82SingleExp             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d1In_src0Addr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d1In_src1Addr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d1In_dstAddr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d1In_exponent                   :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d1In_exponentIn1                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d1In_exponentIn2                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d1In_reluValue                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          d1In_reluScaleExp               :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
          d1In_single2Int8Exp             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          d1In_int82SingleExp             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          notFullIn                       :   IN    std_logic;
          notEmptyIn                      :   IN    std_logic;
          notFull                         :   OUT   std_logic;
          d0_src0Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d0_src1Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d0_dstAddr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d0_exponent                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d0_exponentIn1                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d0_exponentIn2                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d0_reluValue                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d0_reluScaleExp                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
          d0_single2Int8Exp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d0_int82SingleExp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d1_src0Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d1_src1Addr                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d1_dstAddr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d1_exponent                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d1_exponentIn1                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d1_exponentIn2                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d1_reluValue                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          d1_reluScaleExp                 :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
          d1_single2Int8Exp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          d1_int82SingleExp               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
          notEmpty                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_calcData_INSTR_block86
    USE ENTITY work.MyProc_src_calcData_INSTR_block86(rtl);

  -- Signals
  SIGNAL notFullReg_ctrl_const_out        : std_logic;
  SIGNAL notFullReg_ctrl_delay_out        : std_logic;
  SIGNAL notFullReg_Initial_Val_out       : std_logic;
  SIGNAL notEmpty_1                       : std_logic;
  SIGNAL notEmptyReg_out1                 : std_logic;
  SIGNAL notFull_1                        : std_logic;
  SIGNAL notFullReg_out                   : std_logic;
  SIGNAL notFullReg_out1                  : std_logic;
  SIGNAL d1_int82SingleExp                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_int82SingleExp_signed         : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_out1_int82SingleExp           : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_single2Int8Exp                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_single2Int8Exp_signed         : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_out1_single2Int8Exp           : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_reluScaleExp                  : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_reluScaleExp_signed           : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL d1_out1_reluScaleExp             : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL d1_reluValue                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d1_reluValue_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_out1_reluValue                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_exponentIn2                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_exponentIn2_signed            : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_out1_exponentIn2              : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_exponentIn1                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_exponentIn1_signed            : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_out1_exponentIn1              : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_exponent                      : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d1_exponent_signed               : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_out1_exponent                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL d1_dstAddr                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d1_dstAddr_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_out1_dstAddr                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_src1Addr                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d1_src1Addr_unsigned             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_out1_src1Addr                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_src0Addr                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d1_src0Addr_unsigned             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d1_out1_src0Addr                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_int82SingleExp                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_int82SingleExp_signed         : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_out1_int82SingleExp           : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_single2Int8Exp                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_single2Int8Exp_signed         : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_out1_single2Int8Exp           : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_reluScaleExp                  : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_reluScaleExp_signed           : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL d0_out1_reluScaleExp             : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL d0_reluValue                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d0_reluValue_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_out1_reluValue                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_exponentIn2                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_exponentIn2_signed            : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_out1_exponentIn2              : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_exponentIn1                   : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_exponentIn1_signed            : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_out1_exponentIn1              : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_exponent                      : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL d0_exponent_signed               : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_out1_exponent                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL d0_dstAddr                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d0_dstAddr_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_out1_dstAddr                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_src1Addr                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d0_src1Addr_unsigned             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_out1_src1Addr                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_out1_src0Addr                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL d0_src0Addr                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL d0_src0Addr_unsigned             : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_calcData_INSTR : MyProc_src_calcData_INSTR_block86
    PORT MAP( deq => deq,
              enq => enq,
              dIn_src0Addr => dIn_src0Addr,  -- uint32
              dIn_src1Addr => dIn_src1Addr,  -- uint32
              dIn_dstAddr => dIn_dstAddr,  -- uint32
              dIn_exponent => dIn_exponent,  -- int8
              dIn_exponentIn1 => dIn_exponentIn1,  -- int8
              dIn_exponentIn2 => dIn_exponentIn2,  -- int8
              dIn_reluValue => dIn_reluValue,  -- uint32
              dIn_reluScaleExp => dIn_reluScaleExp,  -- sfix8
              dIn_single2Int8Exp => dIn_single2Int8Exp,  -- int8
              dIn_int82SingleExp => dIn_int82SingleExp,  -- int8
              d0In_src0Addr => std_logic_vector(d0_out1_src0Addr),  -- uint32
              d0In_src1Addr => std_logic_vector(d0_out1_src1Addr),  -- uint32
              d0In_dstAddr => std_logic_vector(d0_out1_dstAddr),  -- uint32
              d0In_exponent => std_logic_vector(d0_out1_exponent),  -- int8
              d0In_exponentIn1 => std_logic_vector(d0_out1_exponentIn1),  -- int8
              d0In_exponentIn2 => std_logic_vector(d0_out1_exponentIn2),  -- int8
              d0In_reluValue => std_logic_vector(d0_out1_reluValue),  -- uint32
              d0In_reluScaleExp => std_logic_vector(d0_out1_reluScaleExp),  -- sfix8
              d0In_single2Int8Exp => std_logic_vector(d0_out1_single2Int8Exp),  -- int8
              d0In_int82SingleExp => std_logic_vector(d0_out1_int82SingleExp),  -- int8
              d1In_src0Addr => std_logic_vector(d1_out1_src0Addr),  -- uint32
              d1In_src1Addr => std_logic_vector(d1_out1_src1Addr),  -- uint32
              d1In_dstAddr => std_logic_vector(d1_out1_dstAddr),  -- uint32
              d1In_exponent => std_logic_vector(d1_out1_exponent),  -- int8
              d1In_exponentIn1 => std_logic_vector(d1_out1_exponentIn1),  -- int8
              d1In_exponentIn2 => std_logic_vector(d1_out1_exponentIn2),  -- int8
              d1In_reluValue => std_logic_vector(d1_out1_reluValue),  -- uint32
              d1In_reluScaleExp => std_logic_vector(d1_out1_reluScaleExp),  -- sfix8
              d1In_single2Int8Exp => std_logic_vector(d1_out1_single2Int8Exp),  -- int8
              d1In_int82SingleExp => std_logic_vector(d1_out1_int82SingleExp),  -- int8
              notFullIn => notFullReg_out1,
              notEmptyIn => notEmptyReg_out1,
              notFull => notFull_1,
              d0_src0Addr => d0_src0Addr,  -- uint32
              d0_src1Addr => d0_src1Addr,  -- uint32
              d0_dstAddr => d0_dstAddr,  -- uint32
              d0_exponent => d0_exponent,  -- int8
              d0_exponentIn1 => d0_exponentIn1,  -- int8
              d0_exponentIn2 => d0_exponentIn2,  -- int8
              d0_reluValue => d0_reluValue,  -- uint32
              d0_reluScaleExp => d0_reluScaleExp,  -- sfix8
              d0_single2Int8Exp => d0_single2Int8Exp,  -- int8
              d0_int82SingleExp => d0_int82SingleExp,  -- int8
              d1_src0Addr => d1_src0Addr,  -- uint32
              d1_src1Addr => d1_src1Addr,  -- uint32
              d1_dstAddr => d1_dstAddr,  -- uint32
              d1_exponent => d1_exponent,  -- int8
              d1_exponentIn1 => d1_exponentIn1,  -- int8
              d1_exponentIn2 => d1_exponentIn2,  -- int8
              d1_reluValue => d1_reluValue,  -- uint32
              d1_reluScaleExp => d1_reluScaleExp,  -- sfix8
              d1_single2Int8Exp => d1_single2Int8Exp,  -- int8
              d1_int82SingleExp => d1_int82SingleExp,  -- int8
              notEmpty => notEmpty_1
              );

  notFullReg_ctrl_const_out <= '1';

  notFullReg_ctrl_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      notFullReg_ctrl_delay_out <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        notFullReg_ctrl_delay_out <= notFullReg_ctrl_const_out;
      END IF;
    END IF;
  END PROCESS notFullReg_ctrl_delay_process;


  notFullReg_Initial_Val_out <= '1';

  notEmptyReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      notEmptyReg_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        notEmptyReg_out1 <= notEmpty_1;
      END IF;
    END IF;
  END PROCESS notEmptyReg_process;


  notFullReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      notFullReg_out <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        notFullReg_out <= notFull_1;
      END IF;
    END IF;
  END PROCESS notFullReg_process;


  
  notFullReg_out1 <= notFullReg_Initial_Val_out WHEN notFullReg_ctrl_delay_out = '0' ELSE
      notFullReg_out;

  d1_int82SingleExp_signed <= signed(d1_int82SingleExp);

  c_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_int82SingleExp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_int82SingleExp <= d1_int82SingleExp_signed;
      END IF;
    END IF;
  END PROCESS c_process;


  d1_single2Int8Exp_signed <= signed(d1_single2Int8Exp);

  c_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_single2Int8Exp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_single2Int8Exp <= d1_single2Int8Exp_signed;
      END IF;
    END IF;
  END PROCESS c_1_process;


  d1_reluScaleExp_signed <= signed(d1_reluScaleExp);

  c_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_reluScaleExp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_reluScaleExp <= d1_reluScaleExp_signed;
      END IF;
    END IF;
  END PROCESS c_2_process;


  d1_reluValue_unsigned <= unsigned(d1_reluValue);

  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_reluValue <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_reluValue <= d1_reluValue_unsigned;
      END IF;
    END IF;
  END PROCESS c_3_process;


  d1_exponentIn2_signed <= signed(d1_exponentIn2);

  c_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_exponentIn2 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_exponentIn2 <= d1_exponentIn2_signed;
      END IF;
    END IF;
  END PROCESS c_4_process;


  d1_exponentIn1_signed <= signed(d1_exponentIn1);

  c_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_exponentIn1 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_exponentIn1 <= d1_exponentIn1_signed;
      END IF;
    END IF;
  END PROCESS c_5_process;


  d1_exponent_signed <= signed(d1_exponent);

  c_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_exponent <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_exponent <= d1_exponent_signed;
      END IF;
    END IF;
  END PROCESS c_6_process;


  d1_dstAddr_unsigned <= unsigned(d1_dstAddr);

  c_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_dstAddr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_dstAddr <= d1_dstAddr_unsigned;
      END IF;
    END IF;
  END PROCESS c_7_process;


  d1_src1Addr_unsigned <= unsigned(d1_src1Addr);

  c_8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_src1Addr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_src1Addr <= d1_src1Addr_unsigned;
      END IF;
    END IF;
  END PROCESS c_8_process;


  d1_src0Addr_unsigned <= unsigned(d1_src0Addr);

  c_9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_out1_src0Addr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_out1_src0Addr <= d1_src0Addr_unsigned;
      END IF;
    END IF;
  END PROCESS c_9_process;


  d0_int82SingleExp_signed <= signed(d0_int82SingleExp);

  c_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_int82SingleExp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_int82SingleExp <= d0_int82SingleExp_signed;
      END IF;
    END IF;
  END PROCESS c_10_process;


  d0_single2Int8Exp_signed <= signed(d0_single2Int8Exp);

  c_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_single2Int8Exp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_single2Int8Exp <= d0_single2Int8Exp_signed;
      END IF;
    END IF;
  END PROCESS c_11_process;


  d0_reluScaleExp_signed <= signed(d0_reluScaleExp);

  c_12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_reluScaleExp <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_reluScaleExp <= d0_reluScaleExp_signed;
      END IF;
    END IF;
  END PROCESS c_12_process;


  d0_reluValue_unsigned <= unsigned(d0_reluValue);

  c_13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_reluValue <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_reluValue <= d0_reluValue_unsigned;
      END IF;
    END IF;
  END PROCESS c_13_process;


  d0_exponentIn2_signed <= signed(d0_exponentIn2);

  c_14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_exponentIn2 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_exponentIn2 <= d0_exponentIn2_signed;
      END IF;
    END IF;
  END PROCESS c_14_process;


  d0_exponentIn1_signed <= signed(d0_exponentIn1);

  c_15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_exponentIn1 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_exponentIn1 <= d0_exponentIn1_signed;
      END IF;
    END IF;
  END PROCESS c_15_process;


  d0_exponent_signed <= signed(d0_exponent);

  c_16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_exponent <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_exponent <= d0_exponent_signed;
      END IF;
    END IF;
  END PROCESS c_16_process;


  d0_dstAddr_unsigned <= unsigned(d0_dstAddr);

  c_17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_dstAddr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_dstAddr <= d0_dstAddr_unsigned;
      END IF;
    END IF;
  END PROCESS c_17_process;


  d0_src1Addr_unsigned <= unsigned(d0_src1Addr);

  c_18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_src1Addr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_src1Addr <= d0_src1Addr_unsigned;
      END IF;
    END IF;
  END PROCESS c_18_process;


  d0_src0Addr_unsigned <= unsigned(d0_src0Addr);

  c_19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d0_out1_src0Addr <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d0_out1_src0Addr <= d0_src0Addr_unsigned;
      END IF;
    END IF;
  END PROCESS c_19_process;


  dOut_src0Addr <= std_logic_vector(d0_out1_src0Addr);

  dOut_src1Addr <= std_logic_vector(d0_out1_src1Addr);

  dOut_dstAddr <= std_logic_vector(d0_out1_dstAddr);

  dOut_exponent <= std_logic_vector(d0_out1_exponent);

  dOut_exponentIn1 <= std_logic_vector(d0_out1_exponentIn1);

  dOut_exponentIn2 <= std_logic_vector(d0_out1_exponentIn2);

  dOut_reluValue <= std_logic_vector(d0_out1_reluValue);

  dOut_reluScaleExp <= std_logic_vector(d0_out1_reluScaleExp);

  dOut_single2Int8Exp <= std_logic_vector(d0_out1_single2Int8Exp);

  dOut_int82SingleExp <= std_logic_vector(d0_out1_int82SingleExp);

  notEmpty <= notEmptyReg_out1;

  notFull <= notFullReg_out1;

END rtl;

