-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_ShiftStageRegister1_block.vhd
-- Created: 2025-10-22 15:46:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_ShiftStageRegister1_block
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/OutputProcessor_T/OutputProcesssorCoreBusT/InstructionAssembler1/ShiftStageRegister1
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_ShiftStageRegister1_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        load                              :   IN    std_logic;
        stage                             :   IN    std_logic;
        D                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out2                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out3                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out4                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out5                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out6                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out7                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out8                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out9                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out10                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out11                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out12                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out13                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out14                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END MyProc_src_ShiftStageRegister1_block;


ARCHITECTURE rtl OF MyProc_src_ShiftStageRegister1_block IS

  -- Component Declarations
  COMPONENT MyProc_src_SSR_block4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          D                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          load                            :   IN    std_logic;
          stage                           :   IN    std_logic;
          out1                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out2                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out3                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out4                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out5                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out6                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out7                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out8                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out9                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out10                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out11                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out12                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out13                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          out14                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_SSR_block4
    USE ENTITY work.MyProc_src_SSR_block4(rtl);

  -- Signals
  SIGNAL SSR_out1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out2                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out3                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out4                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out5                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out6                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out7                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out8                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out9                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out10                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out11                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out12                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out13                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SSR_out14                        : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_SSR : MyProc_src_SSR_block4
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              D => D,  -- uint32
              load => load,
              stage => stage,
              out1 => SSR_out1,  -- uint32
              out2 => SSR_out2,  -- uint32
              out3 => SSR_out3,  -- uint32
              out4 => SSR_out4,  -- uint32
              out5 => SSR_out5,  -- uint32
              out6 => SSR_out6,  -- uint32
              out7 => SSR_out7,  -- uint32
              out8 => SSR_out8,  -- uint32
              out9 => SSR_out9,  -- uint32
              out10 => SSR_out10,  -- uint32
              out11 => SSR_out11,  -- uint32
              out12 => SSR_out12,  -- uint32
              out13 => SSR_out13,  -- uint32
              out14 => SSR_out14  -- uint32
              );

  Out1 <= SSR_out1;

  Out2 <= SSR_out2;

  Out3 <= SSR_out3;

  Out4 <= SSR_out4;

  Out5 <= SSR_out5;

  Out6 <= SSR_out6;

  Out7 <= SSR_out7;

  Out8 <= SSR_out8;

  Out9 <= SSR_out9;

  Out10 <= SSR_out10;

  Out11 <= SSR_out11;

  Out12 <= SSR_out12;

  Out13 <= SSR_out13;

  Out14 <= SSR_out14;

END rtl;

