-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DataTypeConv_block.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DataTypeConv_block
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/StreamFIFO_DDRBurstControl/DataTypeConv
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_DataTypeConv_block IS
  PORT( InData                            :   IN    vector_of_std_logic_vector8(0 TO 3);  -- uint8 [4]
        OutData                           :   OUT   vector_of_std_logic_vector8(0 TO 3)  -- int8 [4]
        );
END MyProc_src_DataTypeConv_block;


ARCHITECTURE rtl OF MyProc_src_DataTypeConv_block IS

  -- Signals
  SIGNAL InData_unsigned                  : vector_of_unsigned8(0 TO 3);  -- uint8 [4]
  SIGNAL DTC_out1                         : vector_of_signed8(0 TO 3);  -- int8 [4]

BEGIN
  outputgen1: FOR k IN 0 TO 3 GENERATE
    InData_unsigned(k) <= unsigned(InData(k));
  END GENERATE;


  DTC_out1_gen: FOR ii IN 0 TO 3 GENERATE
    DTC_out1(ii) <= signed(InData_unsigned(ii));
  END GENERATE DTC_out1_gen;


  outputgen: FOR k IN 0 TO 3 GENERATE
    OutData(k) <= std_logic_vector(DTC_out1(k));
  END GENERATE;

END rtl;

