-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Variant_Subsystem_block.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Variant_Subsystem_block
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/Variant Subsystem
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Variant_Subsystem_block IS
  PORT( reset_1                           :   IN    std_logic;
        start                             :   IN    std_logic;
        inputRdData                       :   IN    vector_of_std_logic_vector32(0 TO 3);  -- single [4]
        Done                              :   OUT   std_logic;
        resultValid                       :   OUT   std_logic;
        resultWrData                      :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- single [4]
        resultWrAddr                      :   OUT   std_logic_vector(14 DOWNTO 0);  -- ufix15
        inputRdAddr                       :   OUT   std_logic_vector(14 DOWNTO 0)  -- ufix15
        );
END MyProc_src_Variant_Subsystem_block;


ARCHITECTURE rtl OF MyProc_src_Variant_Subsystem_block IS

  -- Component Declarations
  COMPONENT MyProc_src_Dummy_System
    PORT( reset_1                         :   IN    std_logic;
          start                           :   IN    std_logic;
          inputRdData                     :   IN    vector_of_std_logic_vector32(0 TO 3);  -- single [4]
          Done                            :   OUT   std_logic;
          resultValid                     :   OUT   std_logic;
          resultWrData                    :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- single [4]
          resultWrAddr                    :   OUT   std_logic_vector(14 DOWNTO 0);  -- ufix15
          inputRdAddr                     :   OUT   std_logic_vector(14 DOWNTO 0)  -- ufix15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Dummy_System
    USE ENTITY work.MyProc_src_Dummy_System(rtl);

  -- Signals
  SIGNAL resetdeadIndeadIn                : std_logic;
  SIGNAL startdeadIndeadIn                : std_logic;
  SIGNAL inputRdDatadeadIndeadIn          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL inputRdDatadeadIndeadIn_1        : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Dummy_System_out1                : std_logic;
  SIGNAL Dummy_System_out2                : std_logic;
  SIGNAL Dummy_System_out3                : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Dummy_System_out4                : std_logic_vector(14 DOWNTO 0);  -- ufix15
  SIGNAL Dummy_System_out5                : std_logic_vector(14 DOWNTO 0);  -- ufix15

BEGIN
  u_Dummy_System : MyProc_src_Dummy_System
    PORT MAP( reset_1 => resetdeadIndeadIn,
              start => startdeadIndeadIn,
              inputRdData => inputRdDatadeadIndeadIn_1,  -- single [4]
              Done => Dummy_System_out1,
              resultValid => Dummy_System_out2,
              resultWrData => Dummy_System_out3,  -- single [4]
              resultWrAddr => Dummy_System_out4,  -- ufix15
              inputRdAddr => Dummy_System_out5  -- ufix15
              );

  resetdeadIndeadIn <= '0';

  startdeadIndeadIn <= '0';

  inputRdDatadeadIndeadIn <= X"00000000";

  inputRdDatadeadIndeadIn_1(0) <= inputRdDatadeadIndeadIn;
  inputRdDatadeadIndeadIn_1(1) <= inputRdDatadeadIndeadIn;
  inputRdDatadeadIndeadIn_1(2) <= inputRdDatadeadIndeadIn;
  inputRdDatadeadIndeadIn_1(3) <= inputRdDatadeadIndeadIn;

  Done <= Dummy_System_out1;

  resultValid <= Dummy_System_out2;

  resultWrData <= Dummy_System_out3;

  resultWrAddr <= Dummy_System_out4;

  inputRdAddr <= Dummy_System_out5;

END rtl;

