-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_WR_MODE_block1.vhd
-- Created: 2025-10-22 15:46:36
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_WR_MODE_block1
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Input_InstructionStack  /Subsystem Reference1/Subsystem Reference/IStack/StackLogic/WR_MODE
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_WR_MODE_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        DIN                               :   IN    std_logic;
        EN                                :   IN    std_logic;
        DOUT                              :   OUT   std_logic
        );
END MyProc_src_WR_MODE_block1;


ARCHITECTURE rtl OF MyProc_src_WR_MODE_block1 IS

  -- Signals
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Switch3_out1                     : std_logic;

BEGIN
  
  Switch3_out1 <= Delay3_out1 WHEN EN = '0' ELSE
      DIN;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Switch3_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  DOUT <= Delay3_out1;

END rtl;

