-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_sendReqs_block.vhd
-- Created: 2025-10-22 15:46:40
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_sendReqs_block
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/DDRInterface/Subsystem/ModifiedForBoth/sendReqs
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_sendReqs_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        reqMulti_addr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        reqMulti_length                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        valid                             :   IN    std_logic;
        available                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        canSend                           :   IN    std_logic;
        enq                               :   OUT   std_logic;
        req_addr                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        req_length                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        deq                               :   OUT   std_logic
        );
END MyProc_src_sendReqs_block;


ARCHITECTURE rtl OF MyProc_src_sendReqs_block IS

  -- Component Declarations
  COMPONENT MyProc_src_sendReqs
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          valid                           :   IN    std_logic;
          reqMulti_addr                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          reqMulti_length                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          canSend                         :   IN    std_logic;
          available                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          req_addr                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          req_length                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          enq                             :   OUT   std_logic;
          deq                             :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_sendReqs
    USE ENTITY work.MyProc_src_sendReqs(rtl);

  -- Signals
  SIGNAL req_addr_tmp                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL req_length_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_sendReqs : MyProc_src_sendReqs
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              valid => valid,
              reqMulti_addr => reqMulti_addr,  -- uint32
              reqMulti_length => reqMulti_length,  -- uint32
              canSend => canSend,
              available => available,  -- uint32
              req_addr => req_addr_tmp,  -- uint32
              req_length => req_length_tmp,  -- uint32
              enq => enq,
              deq => deq
              );

  req_addr <= req_addr_tmp;

  req_length <= req_length_tmp;

END rtl;

