-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_QFC_block1.vhd
-- Created: 2025-10-22 15:46:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_QFC_block1
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/VectorQuant/QFC
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_QFC_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        InData                            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Exp                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        OutData                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END MyProc_src_QFC_block1;


ARCHITECTURE rtl OF MyProc_src_QFC_block1 IS

  -- Component Declarations
  COMPONENT MyProc_src_DTC_block9
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Exponent                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          DataOut                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_DTC_block9
    USE ENTITY work.MyProc_src_DTC_block9(rtl);

  -- Signals
  SIGNAL DTC_out1                         : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_DTC : MyProc_src_DTC_block9
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Data => InData,  -- int32
              Exponent => Exp,  -- int32
              DataOut => DTC_out1  -- int8
              );

  OutData <= DTC_out1;

END rtl;

