-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_switch_block7.vhd
-- Created: 2025-10-22 15:46:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_switch_block7
-- Source Path: testbench/DUT/DUT/Subsystem/CNN5_debug1/Debug Log Msg/Debug Mem/DebugDecoder/switch
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_switch_block7 IS
  PORT( In1                               :   IN    std_logic;
        In2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        In3                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        In4                               :   IN    std_logic;
        In5                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        In6                               :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        In7                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        In8                               :   IN    std_logic;
        In9                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out2                              :   OUT   std_logic_vector(11 DOWNTO 0);  -- ufix12
        Out3                              :   OUT   std_logic;
        Out4                              :   OUT   std_logic_vector(11 DOWNTO 0)  -- ufix12
        );
END MyProc_src_switch_block7;


ARCHITECTURE rtl OF MyProc_src_switch_block7 IS

  -- Signals
  SIGNAL Switch_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL In7_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL In3_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Switch1_out1                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Switch2_out1                     : std_logic;
  SIGNAL In9_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL In5_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Switch3_out1                     : unsigned(11 DOWNTO 0);  -- ufix12

BEGIN
  
  Switch_out1 <= In6 WHEN In1 = '0' ELSE
      In2;

  Out1 <= Switch_out1;

  In7_unsigned <= unsigned(In7);

  In3_unsigned <= unsigned(In3);

  
  Switch1_out1 <= In7_unsigned WHEN In1 = '0' ELSE
      In3_unsigned;

  Out2 <= std_logic_vector(Switch1_out1);

  
  Switch2_out1 <= In8 WHEN In1 = '0' ELSE
      In4;

  Out3 <= Switch2_out1;

  In9_unsigned <= unsigned(In9);

  In5_unsigned <= unsigned(In5);

  
  Switch3_out1 <= In9_unsigned WHEN In1 = '0' ELSE
      In5_unsigned;

  Out4 <= std_logic_vector(Switch3_out1);

END rtl;

