-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_Reference4_block8.vhd
-- Created: 2025-10-22 15:46:38
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_Reference4_block8
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Conv_InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/Subsystem 
-- Reference
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Subsystem_Reference4_block8 IS
  PORT( Fxd                               :   IN    vector_of_std_logic_vector32(0 TO 2);  -- uint32 [3]
        Data_ipCount                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Data_opCount                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Data_srcAddr                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Data_dstAddr                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END MyProc_src_Subsystem_Reference4_block8;


ARCHITECTURE rtl OF MyProc_src_Subsystem_Reference4_block8 IS

  -- Component Declarations
  COMPONENT MyProc_src_fromFixed_block18
    PORT( fs                              :   IN    vector_of_std_logic_vector32(0 TO 2);  -- uint32 [3]
          dataConst_ipCount               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          dataConst_opCount               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          dataConst_srcAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataConst_dstAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_ipCount                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          data_opCount                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          data_srcAddr                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          data_dstAddr                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_fromFixed_block18
    USE ENTITY work.MyProc_src_fromFixed_block18(rtl);

  -- Signals
  SIGNAL Constant_out1_ipCount            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant_out1_opCount            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant_out1_srcAddr            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant_out1_dstAddr            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_ipCount_1                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL data_opCount_1                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL data_srcAddr_1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL data_dstAddr_1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_fromFixed : MyProc_src_fromFixed_block18
    PORT MAP( fs => Fxd,  -- uint32 [3]
              dataConst_ipCount => std_logic_vector(Constant_out1_ipCount),  -- uint16
              dataConst_opCount => std_logic_vector(Constant_out1_opCount),  -- uint16
              dataConst_srcAddr => std_logic_vector(Constant_out1_srcAddr),  -- uint32
              dataConst_dstAddr => std_logic_vector(Constant_out1_dstAddr),  -- uint32
              data_ipCount => data_ipCount_1,  -- uint16
              data_opCount => data_opCount_1,  -- uint16
              data_srcAddr => data_srcAddr_1,  -- uint32
              data_dstAddr => data_dstAddr_1  -- uint32
              );

  Constant_out1_ipCount <= to_unsigned(16#0000#, 16);

  Constant_out1_opCount <= to_unsigned(16#0000#, 16);

  Constant_out1_srcAddr <= to_unsigned(0, 32);

  Constant_out1_dstAddr <= to_unsigned(0, 32);

  Data_ipCount <= data_ipCount_1;

  Data_opCount <= data_opCount_1;

  Data_srcAddr <= data_srcAddr_1;

  Data_dstAddr <= data_dstAddr_1;

END rtl;

