-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Debug_Log_Tap_block24.vhd
-- Created: 2025-10-22 15:46:49
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Debug_Log_Tap_block24
-- Source Path: testbench/DUT/DUT/Adder Module/Dummy Adder Kernel/adder output burst done/Debug Log Tap
-- Hierarchy Level: 5
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Debug_Log_Tap_block24 IS
  PORT( data                              :   IN    std_logic;
        valid                             :   IN    std_logic;
        adder_outputBurstDone_data        :   OUT   std_logic;
        adder_outputBurstDone_valid       :   OUT   std_logic
        );
END MyProc_src_Debug_Log_Tap_block24;


ARCHITECTURE rtl OF MyProc_src_Debug_Log_Tap_block24 IS

BEGIN
  adder_outputBurstDone_data <= data;

  adder_outputBurstDone_valid <= valid;

END rtl;

