-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_RdBusMatrix.vhd
-- Created: 2025-10-22 15:46:41
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_RdBusMatrix
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/DataMemSingleCycleAccumulator/RdBusMatrix
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_RdBusMatrix IS
  PORT( BusSelect                         :   IN    std_logic;  -- ufix1
        RdBus1_RdValid                    :   IN    std_logic;
        RdBus1_RdAddr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        RdBus1_RdDir                      :   IN    std_logic;
        RdBusOut_RdValid                  :   OUT   std_logic;
        RdBusOut_RdAddr                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        RdBusOut_RdDir                    :   OUT   std_logic
        );
END MyProc_src_RdBusMatrix;


ARCHITECTURE rtl OF MyProc_src_RdBusMatrix IS

  -- Component Declarations
  COMPONENT MyProc_src_Scalar_Replicator16
    PORT( In_rsvd                         :   IN    std_logic;
          Out_rsvd                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MyProc_src_Scalar_Replicator15
    PORT( In_rsvd                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          Out_rsvd                        :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Scalar_Replicator16
    USE ENTITY work.MyProc_src_Scalar_Replicator16(rtl);

  FOR ALL : MyProc_src_Scalar_Replicator15
    USE ENTITY work.MyProc_src_Scalar_Replicator15(rtl);

  -- Signals
  SIGNAL RdValid                          : std_logic;
  SIGNAL RdValid_1                        : std_logic;
  SIGNAL RdValid_2                        : std_logic;
  SIGNAL RdValid_3                        : std_logic;
  SIGNAL RdAddr                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL RdAddr_1                         : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL RdAddr_2                         : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL RdAddr_unsigned                  : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL RdAddr_dtc                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL RdAddr_3                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL RdDir                            : std_logic;
  SIGNAL RdDir_1                          : std_logic;
  SIGNAL RdDir_2                          : std_logic;

BEGIN
  u_Scalar_Replicator16 : MyProc_src_Scalar_Replicator16
    PORT MAP( In_rsvd => RdValid_1,
              Out_rsvd => RdValid_2
              );

  u_Scalar_Replicator15 : MyProc_src_Scalar_Replicator15
    PORT MAP( In_rsvd => std_logic_vector(RdAddr_1),  -- ufix13
              Out_rsvd => RdAddr_2  -- ufix13
              );

  RdValid <= RdBus1_RdValid;

  RdValid_1 <= '0';

  
  RdValid_3 <= RdValid WHEN BusSelect = '0' ELSE
      RdValid_2;

  RdBusOut_RdValid <= RdValid_3;

  RdAddr <= unsigned(RdBus1_RdAddr);

  RdAddr_1 <= to_unsigned(16#0000#, 13);

  RdAddr_unsigned <= unsigned(RdAddr_2);

  RdAddr_dtc <= resize(RdAddr_unsigned, 32);

  
  RdAddr_3 <= RdAddr WHEN BusSelect = '0' ELSE
      RdAddr_dtc;

  RdBusOut_RdAddr <= std_logic_vector(RdAddr_3);

  RdDir <= RdBus1_RdDir;

  RdDir_1 <= '0';

  
  RdDir_2 <= RdDir WHEN BusSelect = '0' ELSE
      RdDir_1;

  RdBusOut_RdDir <= RdDir_2;

END rtl;

