-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_MATLAB_Function_block25.vhd
-- Created: 2025-10-22 15:46:38
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_MATLAB_Function_block25
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Add_ InstructionStack/Subsystem Reference1/Subsystem Reference1/updateTable/MATLAB 
-- Functio
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_MATLAB_Function_block25 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        instr_cmd                         :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        instr_src0                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src1                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_dst0                        :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src0Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_src1Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_dst0Mode                    :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_epoch                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        instrValid                        :   IN    std_logic;
        canSend                           :   IN    std_logic;
        tableOpConst_stackNum             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_num                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableOpConst_cmd                  :   IN    T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        tableOpConst_staticReads          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_epoch                :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOpConst_isConstant           :   IN    std_logic;
        deq                               :   OUT   std_logic;
        enq                               :   OUT   std_logic;
        tableOp_stackNum                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_num                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        tableOp_cmd                       :   OUT   T_TableOpCmd;  -- enum type TableOpCmd (10 enums)
        tableOp_staticReads               :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_epoch                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        tableOp_isConstant                :   OUT   std_logic
        );
END MyProc_src_MATLAB_Function_block25;


ARCHITECTURE rtl OF MyProc_src_MATLAB_Function_block25 IS

  -- Signals
  SIGNAL instr_src0_unsigned              : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_src1_unsigned              : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_dst0_unsigned              : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_epoch_unsigned             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOpConst_stackNum_unsigned   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOpConst_num_unsigned        : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tableOpConst_staticReads_unsigned : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOpConst_epoch_unsigned      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_stackNum_tmp             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_num_tmp                  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tableOp_staticReads_tmp          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL tableOp_epoch_tmp                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state                            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state_next                       : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  instr_src0_unsigned <= unsigned(instr_src0);

  instr_src1_unsigned <= unsigned(instr_src1);

  instr_dst0_unsigned <= unsigned(instr_dst0);

  instr_epoch_unsigned <= unsigned(instr_epoch);

  tableOpConst_stackNum_unsigned <= unsigned(tableOpConst_stackNum);

  tableOpConst_num_unsigned <= unsigned(tableOpConst_num);

  tableOpConst_staticReads_unsigned <= unsigned(tableOpConst_staticReads);

  tableOpConst_epoch_unsigned <= unsigned(tableOpConst_epoch);

  MATLAB_Function_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      state <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        state <= state_next;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_process;

  MATLAB_Function_output : PROCESS (canSend, instrValid, instr_dst0_unsigned, instr_src0_unsigned,
       instr_src1_unsigned, state)
  BEGIN
    state_next <= state;
    enq <= '0';
    deq <= '0';
    tableOp_num_tmp <= to_unsigned(16#000#, 10);
    tableOp_cmd <= DFLT;
    CASE state IS
      WHEN "00000000" =>
        IF instrValid = '1' THEN 
          state_next <= to_unsigned(16#01#, 8);
        END IF;
      WHEN "00000001" =>
        IF instr_src0_unsigned /= to_unsigned(16#000#, 10) THEN 
          IF canSend = '1' THEN 
            tableOp_cmd <= DOREAD;
            tableOp_num_tmp <= instr_src0_unsigned;
            enq <= '1';
            state_next <= to_unsigned(16#02#, 8);
          END IF;
        ELSE 
          state_next <= to_unsigned(16#02#, 8);
        END IF;
      WHEN "00000010" =>
        IF instr_src1_unsigned /= to_unsigned(16#000#, 10) THEN 
          IF canSend = '1' THEN 
            tableOp_cmd <= DOREAD;
            tableOp_num_tmp <= instr_src1_unsigned;
            enq <= '1';
            state_next <= to_unsigned(16#03#, 8);
          END IF;
        ELSE 
          state_next <= to_unsigned(16#03#, 8);
        END IF;
      WHEN "00000011" =>
        IF instr_dst0_unsigned /= to_unsigned(16#000#, 10) THEN 
          IF canSend = '1' THEN 
            tableOp_cmd <= DOWRITE;
            tableOp_num_tmp <= instr_dst0_unsigned;
            enq <= '1';
            state_next <= to_unsigned(16#04#, 8);
          END IF;
        ELSE 
          state_next <= to_unsigned(16#04#, 8);
        END IF;
      WHEN "00000100" =>
        deq <= '1';
        state_next <= to_unsigned(16#00#, 8);
      WHEN OTHERS => 
        NULL;
    END CASE;
    tableOp_stackNum_tmp <= to_unsigned(16#00#, 8);
    tableOp_staticReads_tmp <= to_unsigned(16#00#, 8);
    tableOp_epoch_tmp <= to_unsigned(16#00#, 8);
    tableOp_isConstant <= '0';
  END PROCESS MATLAB_Function_output;


  tableOp_stackNum <= std_logic_vector(tableOp_stackNum_tmp);

  tableOp_num <= std_logic_vector(tableOp_num_tmp);

  tableOp_staticReads <= std_logic_vector(tableOp_staticReads_tmp);

  tableOp_epoch <= std_logic_vector(tableOp_epoch_tmp);

END rtl;

