-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_convert_data_to_out_mem1.vhd
-- Created: 2025-10-22 15:46:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_convert_data_to_out_mem1
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/convert_data_to_out_mem1
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_convert_data_to_out_mem1 IS
  PORT( bin_sel                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        data_in                           :   IN    vector_of_std_logic_vector8(0 TO 8);  -- int8 [9]
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END MyProc_src_convert_data_to_out_mem1;


ARCHITECTURE rtl OF MyProc_src_convert_data_to_out_mem1 IS

  -- Signals
  SIGNAL bin_sel_unsigned                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL data_in_signed                   : vector_of_signed8(0 TO 8);  -- int8 [9]
  SIGNAL Selector_out1                    : signed(7 DOWNTO 0);  -- int8

BEGIN
  bin_sel_unsigned <= unsigned(bin_sel);

  Data_Type_Conversion_out1 <= resize(bin_sel_unsigned, 8);

  outputgen: FOR k IN 0 TO 8 GENERATE
    data_in_signed(k) <= signed(data_in(k));
  END GENERATE;

  
  Selector_out1 <= data_in_signed(0) WHEN Data_Type_Conversion_out1 = to_unsigned(16#00#, 8) ELSE
      data_in_signed(1) WHEN Data_Type_Conversion_out1 = to_unsigned(16#01#, 8) ELSE
      data_in_signed(2) WHEN Data_Type_Conversion_out1 = to_unsigned(16#02#, 8) ELSE
      data_in_signed(3) WHEN Data_Type_Conversion_out1 = to_unsigned(16#03#, 8) ELSE
      data_in_signed(4) WHEN Data_Type_Conversion_out1 = to_unsigned(16#04#, 8) ELSE
      data_in_signed(5) WHEN Data_Type_Conversion_out1 = to_unsigned(16#05#, 8) ELSE
      data_in_signed(6) WHEN Data_Type_Conversion_out1 = to_unsigned(16#06#, 8) ELSE
      data_in_signed(7) WHEN Data_Type_Conversion_out1 = to_unsigned(16#07#, 8) ELSE
      data_in_signed(8);

  Out1 <= std_logic_vector(Selector_out1);

END rtl;

