-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Scalar_Replicator2_block6.vhd
-- Created: 2025-10-22 15:46:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Scalar_Replicator2_block6
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Scalar Replicator2
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Scalar_Replicator2_block6 IS
  PORT( In_rsvd                           :   IN    vector_of_std_logic_vector8(0 TO 17);  -- int8 [18]
        Out_rsvd                          :   OUT   vector_of_std_logic_vector8(0 TO 35)  -- int8 [36]
        );
END MyProc_src_Scalar_Replicator2_block6;


ARCHITECTURE rtl OF MyProc_src_Scalar_Replicator2_block6 IS

  -- Signals
  SIGNAL In_signed                        : vector_of_std_logic_vector8(0 TO 17);  -- ufix8 [18]
  SIGNAL Mux_out1                         : vector_of_std_logic_vector8(0 TO 35);  -- ufix8 [36]

BEGIN
  In_signed <= In_rsvd;

  Mux_out1(0) <= In_signed(0);
  Mux_out1(1) <= In_signed(1);
  Mux_out1(2) <= In_signed(2);
  Mux_out1(3) <= In_signed(3);
  Mux_out1(4) <= In_signed(4);
  Mux_out1(5) <= In_signed(5);
  Mux_out1(6) <= In_signed(6);
  Mux_out1(7) <= In_signed(7);
  Mux_out1(8) <= In_signed(8);
  Mux_out1(9) <= In_signed(9);
  Mux_out1(10) <= In_signed(10);
  Mux_out1(11) <= In_signed(11);
  Mux_out1(12) <= In_signed(12);
  Mux_out1(13) <= In_signed(13);
  Mux_out1(14) <= In_signed(14);
  Mux_out1(15) <= In_signed(15);
  Mux_out1(16) <= In_signed(16);
  Mux_out1(17) <= In_signed(17);
  Mux_out1(18) <= In_signed(0);
  Mux_out1(19) <= In_signed(1);
  Mux_out1(20) <= In_signed(2);
  Mux_out1(21) <= In_signed(3);
  Mux_out1(22) <= In_signed(4);
  Mux_out1(23) <= In_signed(5);
  Mux_out1(24) <= In_signed(6);
  Mux_out1(25) <= In_signed(7);
  Mux_out1(26) <= In_signed(8);
  Mux_out1(27) <= In_signed(9);
  Mux_out1(28) <= In_signed(10);
  Mux_out1(29) <= In_signed(11);
  Mux_out1(30) <= In_signed(12);
  Mux_out1(31) <= In_signed(13);
  Mux_out1(32) <= In_signed(14);
  Mux_out1(33) <= In_signed(15);
  Mux_out1(34) <= In_signed(16);
  Mux_out1(35) <= In_signed(17);

  Out_rsvd <= Mux_out1;

END rtl;

