-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_writeSelect1.vhd
-- Created: 2025-10-22 15:46:42
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_writeSelect1
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/DataMemSingleCycleAccumulator/writeSelect1
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_writeSelect1 IS
  PORT( WrValid1                          :   IN    std_logic;
        WrValid2                          :   IN    std_logic;
        WrSelect                          :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
        );
END MyProc_src_writeSelect1;


ARCHITECTURE rtl OF MyProc_src_writeSelect1 IS

  -- Signals
  SIGNAL WrSelect_tmp                     : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  dnnfpgaNewdatamemlibforFC_c91_writeSelect1_output : PROCESS (WrValid1, WrValid2)
  BEGIN
    IF WrValid1 = '1' THEN 
      WrSelect_tmp <= to_unsigned(16#0#, 2);
    ELSIF WrValid2 = '1' THEN 
      WrSelect_tmp <= to_unsigned(16#1#, 2);
    ELSE 
      WrSelect_tmp <= to_unsigned(16#2#, 2);
    END IF;
  END PROCESS dnnfpgaNewdatamemlibforFC_c91_writeSelect1_output;


  WrSelect <= std_logic_vector(WrSelect_tmp);

END rtl;

