-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_StackBufferWithClr_block5.vhd
-- Created: 2025-10-22 15:46:37
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_StackBufferWithClr_block5
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/FC_InstructionStack/Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/StackBufferWithClr
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_StackBufferWithClr_block5 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        DataIn                            :   IN    std_logic_vector(69 DOWNTO 0);  -- ufix70
        next_rsvd                         :   IN    std_logic;
        enq                               :   IN    std_logic;
        PayloadIn                         :   IN    vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
        wrMode                            :   IN    std_logic;
        Clear                             :   IN    std_logic;
        DataOut                           :   OUT   std_logic_vector(69 DOWNTO 0);  -- ufix70
        Valid                             :   OUT   std_logic;
        PayloadOut                        :   OUT   vector_of_std_logic_vector27(0 TO 2)  -- ufix27 [3]
        );
END MyProc_src_StackBufferWithClr_block5;


ARCHITECTURE rtl OF MyProc_src_StackBufferWithClr_block5 IS

  -- Component Declarations
  COMPONENT MyProc_src_Subsystem_Reference1_block13
    PORT( Fxd                             :   IN    std_logic_vector(69 DOWNTO 0);  -- ufix70
          Data_cmd                        :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
          Data_src0                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_src1                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_dst0                       :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_src0Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_src1Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_dst0Mode                   :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_epoch                      :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT MyProc_src_updateEpoch_block2
    PORT( dlInstrIn_cmd                   :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
          dlInstrIn_src0                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrIn_src1                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrIn_dst0                  :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrIn_src0Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrIn_src1Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrIn_dst0Mode              :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrIn_epoch                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          dlInstrOut_cmd                  :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
          dlInstrOut_src0                 :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrOut_src1                 :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrOut_dst0                 :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
          dlInstrOut_src0Mode             :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrOut_src1Mode             :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrOut_dst0Mode             :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
          dlInstrOut_epoch                :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT MyProc_src_Subsystem_Reference2_block5
    PORT( Data_cmd                        :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
          Data_src0                       :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_src1                       :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_dst0                       :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          Data_src0Mode                   :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_src1Mode                   :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_dst0Mode                   :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
          Data_epoch                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Fxd                             :   OUT   std_logic_vector(69 DOWNTO 0)  -- ufix70
          );
  END COMPONENT;

  COMPONENT MyProc_src_FIFO_DL_INSTR_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DIn                             :   IN    std_logic_vector(69 DOWNTO 0);  -- ufix70
          Enq                             :   IN    std_logic;
          Deq                             :   IN    std_logic;
          Clear                           :   IN    std_logic;
          DOut                            :   OUT   std_logic_vector(69 DOWNTO 0);  -- ufix70
          notEmpty                        :   OUT   std_logic;
          notFull                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MyProc_src_Subsystem_Reference3_block5
    PORT( Fxd                             :   IN    vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
          Data_instrCount                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          Data_srcAddr                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Data_dstAddr                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT MyProc_src_updateFrameNumber_block2
    PORT( payloadIn_instrCount            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          payloadIn_srcAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadIn_dstAddr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadOut_instrCount           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          payloadOut_srcAddr              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          payloadOut_dstAddr              :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT MyProc_src_Subsystem_Reference4_block5
    PORT( Data_instrCount                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Data_srcAddr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Data_dstAddr                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Fxd                             :   OUT   vector_of_std_logic_vector27(0 TO 2)  -- ufix27 [3]
          );
  END COMPONENT;

  COMPONENT MyProc_src_FIFO_PAYLOAD_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DIn                             :   IN    vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
          Enq                             :   IN    std_logic;
          Deq                             :   IN    std_logic;
          Clear                           :   IN    std_logic;
          DOut                            :   OUT   vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
          notEmpty                        :   OUT   std_logic;
          notFull                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_Subsystem_Reference1_block13
    USE ENTITY work.MyProc_src_Subsystem_Reference1_block13(rtl);

  FOR ALL : MyProc_src_updateEpoch_block2
    USE ENTITY work.MyProc_src_updateEpoch_block2(rtl);

  FOR ALL : MyProc_src_Subsystem_Reference2_block5
    USE ENTITY work.MyProc_src_Subsystem_Reference2_block5(rtl);

  FOR ALL : MyProc_src_FIFO_DL_INSTR_block2
    USE ENTITY work.MyProc_src_FIFO_DL_INSTR_block2(rtl);

  FOR ALL : MyProc_src_Subsystem_Reference3_block5
    USE ENTITY work.MyProc_src_Subsystem_Reference3_block5(rtl);

  FOR ALL : MyProc_src_updateFrameNumber_block2
    USE ENTITY work.MyProc_src_updateFrameNumber_block2(rtl);

  FOR ALL : MyProc_src_Subsystem_Reference4_block5
    USE ENTITY work.MyProc_src_Subsystem_Reference4_block5(rtl);

  FOR ALL : MyProc_src_FIFO_PAYLOAD_block2
    USE ENTITY work.MyProc_src_FIFO_PAYLOAD_block2(rtl);

  -- Signals
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL DataIn_unsigned                  : unsigned(69 DOWNTO 0);  -- ufix70
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL DOUT_A                           : std_logic_vector(69 DOWNTO 0);  -- ufix70
  SIGNAL data_cmd                         : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL data_src0                        : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_src1                        : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_dst0                        : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL data_src0Mode                    : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_src1Mode                    : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_dst0Mode                    : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL data_epoch                       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL dlInstr_cmd                      : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL dlInstr_src0                     : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_src1                     : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_dst0                     : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL dlInstr_src0Mode                 : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL dlInstr_src1Mode                 : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL dlInstr_dst0Mode                 : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL dlInstr_epoch                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL fs                               : std_logic_vector(69 DOWNTO 0);  -- ufix70
  SIGNAL fs_unsigned                      : unsigned(69 DOWNTO 0);  -- ufix70
  SIGNAL Switch_out1                      : unsigned(69 DOWNTO 0);  -- ufix70
  SIGNAL FIFO_DL_INSTR_out2               : std_logic;
  SIGNAL FIFO_DL_INSTR_out3deadOutdeadOut : std_logic;
  SIGNAL PayloadIn_unsigned               : vector_of_unsigned27(0 TO 2);  -- ufix27 [3]
  SIGNAL FIFO_PAYLOAD_out1                : vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
  SIGNAL data_instrCount                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL data_srcAddr                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL data_dstAddr                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL payload_instrCount               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL payload_srcAddr                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL payload_dstAddr                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL fs_1                             : vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
  SIGNAL fs_unsigned_1                    : vector_of_unsigned27(0 TO 2);  -- ufix27 [3]
  SIGNAL Switch1_out1                     : vector_of_unsigned27(0 TO 2);  -- ufix27 [3]
  SIGNAL Reshape_out1                     : vector_of_std_logic_vector27(0 TO 2);  -- ufix27 [3]
  SIGNAL FIFO_PAYLOAD_out2deadOutdeadOut  : std_logic;
  SIGNAL FIFO_PAYLOAD_out3deadOutdeadOut  : std_logic;

BEGIN
  u_Subsystem_Reference1 : MyProc_src_Subsystem_Reference1_block13
    PORT MAP( Fxd => DOUT_A,  -- ufix70
              Data_cmd => data_cmd,  -- enum type DLCmd (11 enums)
              Data_src0 => data_src0,  -- ufix10
              Data_src1 => data_src1,  -- ufix10
              Data_dst0 => data_dst0,  -- ufix10
              Data_src0Mode => data_src0Mode,  -- enum type AddrMode (5 enums)
              Data_src1Mode => data_src1Mode,  -- enum type AddrMode (5 enums)
              Data_dst0Mode => data_dst0Mode,  -- enum type AddrMode (5 enums)
              Data_epoch => data_epoch  -- uint8
              );

  u_updateEpoch : MyProc_src_updateEpoch_block2
    PORT MAP( dlInstrIn_cmd => data_cmd,  -- enum type DLCmd (11 enums)
              dlInstrIn_src0 => data_src0,  -- ufix10
              dlInstrIn_src1 => data_src1,  -- ufix10
              dlInstrIn_dst0 => data_dst0,  -- ufix10
              dlInstrIn_src0Mode => data_src0Mode,  -- enum type AddrMode (5 enums)
              dlInstrIn_src1Mode => data_src1Mode,  -- enum type AddrMode (5 enums)
              dlInstrIn_dst0Mode => data_dst0Mode,  -- enum type AddrMode (5 enums)
              dlInstrIn_epoch => data_epoch,  -- uint8
              dlInstrOut_cmd => dlInstr_cmd,  -- enum type DLCmd (11 enums)
              dlInstrOut_src0 => dlInstr_src0,  -- ufix10
              dlInstrOut_src1 => dlInstr_src1,  -- ufix10
              dlInstrOut_dst0 => dlInstr_dst0,  -- ufix10
              dlInstrOut_src0Mode => dlInstr_src0Mode,  -- enum type AddrMode (5 enums)
              dlInstrOut_src1Mode => dlInstr_src1Mode,  -- enum type AddrMode (5 enums)
              dlInstrOut_dst0Mode => dlInstr_dst0Mode,  -- enum type AddrMode (5 enums)
              dlInstrOut_epoch => dlInstr_epoch  -- uint8
              );

  u_Subsystem_Reference2 : MyProc_src_Subsystem_Reference2_block5
    PORT MAP( Data_cmd => dlInstr_cmd,  -- enum type DLCmd (11 enums)
              Data_src0 => dlInstr_src0,  -- ufix10
              Data_src1 => dlInstr_src1,  -- ufix10
              Data_dst0 => dlInstr_dst0,  -- ufix10
              Data_src0Mode => dlInstr_src0Mode,  -- enum type AddrMode (5 enums)
              Data_src1Mode => dlInstr_src1Mode,  -- enum type AddrMode (5 enums)
              Data_dst0Mode => dlInstr_dst0Mode,  -- enum type AddrMode (5 enums)
              Data_epoch => dlInstr_epoch,  -- uint8
              Fxd => fs  -- ufix70
              );

  u_FIFO_DL_INSTR : MyProc_src_FIFO_DL_INSTR_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DIn => std_logic_vector(Switch_out1),  -- ufix70
              Enq => Logical_Operator3_out1,
              Deq => Logical_Operator1_out1,
              Clear => Clear,
              DOut => DOUT_A,  -- ufix70
              notEmpty => FIFO_DL_INSTR_out2,
              notFull => FIFO_DL_INSTR_out3deadOutdeadOut
              );

  u_Subsystem_Reference3 : MyProc_src_Subsystem_Reference3_block5
    PORT MAP( Fxd => FIFO_PAYLOAD_out1,  -- ufix27 [3]
              Data_instrCount => data_instrCount,  -- uint16
              Data_srcAddr => data_srcAddr,  -- uint32
              Data_dstAddr => data_dstAddr  -- uint32
              );

  u_updateFrameNumber : MyProc_src_updateFrameNumber_block2
    PORT MAP( payloadIn_instrCount => data_instrCount,  -- uint16
              payloadIn_srcAddr => data_srcAddr,  -- uint32
              payloadIn_dstAddr => data_dstAddr,  -- uint32
              payloadOut_instrCount => payload_instrCount,  -- uint16
              payloadOut_srcAddr => payload_srcAddr,  -- uint32
              payloadOut_dstAddr => payload_dstAddr  -- uint32
              );

  u_Subsystem_Reference4 : MyProc_src_Subsystem_Reference4_block5
    PORT MAP( Data_instrCount => payload_instrCount,  -- uint16
              Data_srcAddr => payload_srcAddr,  -- uint32
              Data_dstAddr => payload_dstAddr,  -- uint32
              Fxd => fs_1  -- ufix27 [3]
              );

  u_FIFO_PAYLOAD : MyProc_src_FIFO_PAYLOAD_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DIn => Reshape_out1,  -- ufix27 [3]
              Enq => Logical_Operator3_out1,
              Deq => Logical_Operator1_out1,
              Clear => Clear,
              DOut => FIFO_PAYLOAD_out1,  -- ufix27 [3]
              notEmpty => FIFO_PAYLOAD_out2deadOutdeadOut,
              notFull => FIFO_PAYLOAD_out3deadOutdeadOut
              );

  Logical_Operator2_out1 <=  NOT wrMode;

  DataIn_unsigned <= unsigned(DataIn);

  Logical_Operator5_out1 <= enq AND wrMode;

  Logical_Operator1_out1 <= Logical_Operator2_out1 AND next_rsvd;

  Logical_Operator3_out1 <= Logical_Operator5_out1 OR Logical_Operator1_out1;

  fs_unsigned <= unsigned(fs);

  
  Switch_out1 <= DataIn_unsigned WHEN Logical_Operator2_out1 = '0' ELSE
      fs_unsigned;

  Valid <= FIFO_DL_INSTR_out2;

  outputgen2: FOR k IN 0 TO 2 GENERATE
    PayloadIn_unsigned(k) <= unsigned(PayloadIn(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 2 GENERATE
    fs_unsigned_1(k) <= unsigned(fs_1(k));
  END GENERATE;

  
  Switch1_out1 <= PayloadIn_unsigned WHEN Logical_Operator2_out1 = '0' ELSE
      fs_unsigned_1;

  outputgen: FOR k IN 0 TO 2 GENERATE
    Reshape_out1(k) <= std_logic_vector(Switch1_out1(k));
  END GENERATE;

  DataOut <= DOUT_A;

  PayloadOut <= FIFO_PAYLOAD_out1;

END rtl;

