-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_Reference4_block3.vhd
-- Created: 2025-10-22 15:46:36
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_Reference4_block3
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Input_InstructionStack  /Subsystem Reference1/Subsystem Reference/IStack/StackBufferWithClr/StackBufferWithClr/Subsystem 
-- Reference
-- Hierarchy Level: 10
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_Subsystem_Reference4_block3 IS
  PORT( Data_addr                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Data_sizeInBytes                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Data_id                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Data_frameNumber                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Data_isFirst                      :   IN    std_logic;
        Fxd                               :   OUT   vector_of_std_logic_vector27(0 TO 3)  -- ufix27 [4]
        );
END MyProc_src_Subsystem_Reference4_block3;


ARCHITECTURE rtl OF MyProc_src_Subsystem_Reference4_block3 IS

  -- Component Declarations
  COMPONENT MyProc_src_toFixed_block8
    PORT( data_addr                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_sizeInBytes                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_id                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data_frameNumber                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_isFirst                    :   IN    std_logic;
          fs                              :   OUT   vector_of_std_logic_vector27(0 TO 3)  -- ufix27 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_toFixed_block8
    USE ENTITY work.MyProc_src_toFixed_block8(rtl);

  -- Signals
  SIGNAL fs                               : vector_of_std_logic_vector27(0 TO 3);  -- ufix27 [4]

BEGIN
  u_toFixed : MyProc_src_toFixed_block8
    PORT MAP( data_addr => Data_addr,  -- uint32
              data_sizeInBytes => Data_sizeInBytes,  -- uint32
              data_id => Data_id,  -- uint8
              data_frameNumber => Data_frameNumber,  -- uint32
              data_isFirst => Data_isFirst,
              fs => fs  -- ufix27 [4]
              );

  Fxd <= fs;

END rtl;

