-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_createPayload_block9.vhd
-- Created: 2025-10-22 15:46:38
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_createPayload_block9
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Add_ InstructionStack/Subsystem Reference1/Subsystem Reference1/createPayload/createPayload
-- Hierarchy Level: 8
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_createPayload_block9 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        inputAddrOffsetIn                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        top_cmd                           :   IN    T_DLCmd;  -- enum type DLCmd (11 enums)
        top_src0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src1                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_dst0                          :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        top_src0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_src1Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_dst0Mode                      :   IN    T_AddrMode;  -- enum type AddrMode (5 enums)
        top_epoch                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        topValid                          :   IN    std_logic;
        payloadIn_src0Addr                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_src1Addr                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_dstAddr                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_exponent                :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadIn_exponentIn1             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadIn_exponentIn2             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadIn_reluValue               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadIn_reluScaleExp            :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
        payloadIn_single2Int8Exp          :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadIn_int82SingleExp          :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        outputAddrOffsetIn                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputAddrOffsetPrevIn            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        outputTotalLSBsIn                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        state                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        payloadConst_src0Addr             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_src1Addr             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_dstAddr              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_exponent             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadConst_exponentIn1          :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadConst_exponentIn2          :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadConst_reluValue            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        payloadConst_reluScaleExp         :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8
        payloadConst_single2Int8Exp       :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        payloadConst_int82SingleExp       :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        topDeq                            :   OUT   std_logic;
        instr_cmd                         :   OUT   T_DLCmd;  -- enum type DLCmd (11 enums)
        instr_src0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src1                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_dst0                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- ufix10
        instr_src0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_src1Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_dst0Mode                    :   OUT   T_AddrMode;  -- enum type AddrMode (5 enums)
        instr_epoch                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        payload_src0Addr                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_src1Addr                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_dstAddr                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_exponent                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        payload_exponentIn1               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        payload_exponentIn2               :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        payload_reluValue                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        payload_reluScaleExp              :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
        payload_single2Int8Exp            :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        payload_int82SingleExp            :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        valid                             :   OUT   std_logic;
        advance                           :   OUT   std_logic;
        toIdle                            :   OUT   std_logic
        );
END MyProc_src_createPayload_block9;


ARCHITECTURE rtl OF MyProc_src_createPayload_block9 IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL inputAddrOffsetIn_unsigned       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL top_src0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_src1_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_dst0_unsigned                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL top_epoch_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadIn_src0Addr_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadIn_src1Addr_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadIn_dstAddr_unsigned       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadIn_exponent_signed        : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadIn_exponentIn1_signed     : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadIn_exponentIn2_signed     : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadIn_reluValue_unsigned     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadIn_reluScaleExp_signed    : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL payloadIn_single2Int8Exp_signed  : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadIn_int82SingleExp_signed  : signed(7 DOWNTO 0);  -- int8
  SIGNAL outputAddrOffsetIn_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetPrevIn_unsigned  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputTotalLSBsIn_unsigned       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL state_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadConst_src0Addr_unsigned   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_src1Addr_unsigned   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_dstAddr_unsigned    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_exponent_signed     : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadConst_exponentIn1_signed  : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadConst_exponentIn2_signed  : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadConst_reluValue_unsigned  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadConst_reluScaleExp_signed : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL payloadConst_single2Int8Exp_signed : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadConst_int82SingleExp_signed : signed(7 DOWNTO 0);  -- int8
  SIGNAL instr_src0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_src1_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_dst0_tmp                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL instr_epoch_tmp                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payload_src0Addr_tmp             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_src1Addr_tmp             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_dstAddr_tmp              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_exponent_tmp             : signed(7 DOWNTO 0);  -- int8
  SIGNAL payload_exponentIn1_tmp          : signed(7 DOWNTO 0);  -- int8
  SIGNAL payload_exponentIn2_tmp          : signed(7 DOWNTO 0);  -- int8
  SIGNAL payload_reluValue_tmp            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payload_reluScaleExp_tmp         : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL payload_single2Int8Exp_tmp       : signed(7 DOWNTO 0);  -- int8
  SIGNAL payload_int82SingleExp_tmp       : signed(7 DOWNTO 0);  -- int8
  SIGNAL topReg_cmd                       : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL topReg_src0                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src1                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_dst0                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src0Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_src1Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_dst0Mode                  : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_epoch                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadReg_src0Addr              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_src1Addr              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_dstAddr               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_exponent              : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_exponentIn1           : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_exponentIn2           : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_reluValue             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_reluScaleExp          : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_single2Int8Exp        : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_int82SingleExp        : signed(7 DOWNTO 0);  -- int8
  SIGNAL inputAddrOffsetReg               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetReg              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetPrevReg          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputTotalLSBsReg               : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL topReg_cmd_next                  : T_DLCmd;  -- enum type DLCmd (11 enums)
  SIGNAL topReg_src0_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src1_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_dst0_next                 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL topReg_src0Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_src1Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_dst0Mode_next             : T_AddrMode;  -- enum type AddrMode (5 enums)
  SIGNAL topReg_epoch_next                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL payloadReg_src0Addr_next         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_src1Addr_next         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_dstAddr_next          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_exponent_next         : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_exponentIn1_next      : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_exponentIn2_next      : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_reluValue_next        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL payloadReg_reluScaleExp_next     : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_single2Int8Exp_next   : signed(7 DOWNTO 0);  -- int8
  SIGNAL payloadReg_int82SingleExp_next   : signed(7 DOWNTO 0);  -- int8
  SIGNAL inputAddrOffsetReg_next          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetReg_next         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputAddrOffsetPrevReg_next     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL outputTotalLSBsReg_next          : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  inputAddrOffsetIn_unsigned <= unsigned(inputAddrOffsetIn);

  top_src0_unsigned <= unsigned(top_src0);

  top_src1_unsigned <= unsigned(top_src1);

  top_dst0_unsigned <= unsigned(top_dst0);

  top_epoch_unsigned <= unsigned(top_epoch);

  payloadIn_src0Addr_unsigned <= unsigned(payloadIn_src0Addr);

  payloadIn_src1Addr_unsigned <= unsigned(payloadIn_src1Addr);

  payloadIn_dstAddr_unsigned <= unsigned(payloadIn_dstAddr);

  payloadIn_exponent_signed <= signed(payloadIn_exponent);

  payloadIn_exponentIn1_signed <= signed(payloadIn_exponentIn1);

  payloadIn_exponentIn2_signed <= signed(payloadIn_exponentIn2);

  payloadIn_reluValue_unsigned <= unsigned(payloadIn_reluValue);

  payloadIn_reluScaleExp_signed <= signed(payloadIn_reluScaleExp);

  payloadIn_single2Int8Exp_signed <= signed(payloadIn_single2Int8Exp);

  payloadIn_int82SingleExp_signed <= signed(payloadIn_int82SingleExp);

  outputAddrOffsetIn_unsigned <= unsigned(outputAddrOffsetIn);

  outputAddrOffsetPrevIn_unsigned <= unsigned(outputAddrOffsetPrevIn);

  outputTotalLSBsIn_unsigned <= unsigned(outputTotalLSBsIn);

  state_unsigned <= unsigned(state);

  payloadConst_src0Addr_unsigned <= unsigned(payloadConst_src0Addr);

  payloadConst_src1Addr_unsigned <= unsigned(payloadConst_src1Addr);

  payloadConst_dstAddr_unsigned <= unsigned(payloadConst_dstAddr);

  payloadConst_exponent_signed <= signed(payloadConst_exponent);

  payloadConst_exponentIn1_signed <= signed(payloadConst_exponentIn1);

  payloadConst_exponentIn2_signed <= signed(payloadConst_exponentIn2);

  payloadConst_reluValue_unsigned <= unsigned(payloadConst_reluValue);

  payloadConst_reluScaleExp_signed <= signed(payloadConst_reluScaleExp);

  payloadConst_single2Int8Exp_signed <= signed(payloadConst_single2Int8Exp);

  payloadConst_int82SingleExp_signed <= signed(payloadConst_int82SingleExp);

  createPayload_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      topReg_cmd <= DFLT;
      topReg_src0 <= to_unsigned(16#000#, 10);
      topReg_src1 <= to_unsigned(16#000#, 10);
      topReg_dst0 <= to_unsigned(16#000#, 10);
      topReg_src0Mode <= Direct;
      topReg_src1Mode <= Direct;
      topReg_dst0Mode <= Direct;
      topReg_epoch <= to_unsigned(16#00#, 8);
      payloadReg_src0Addr <= to_unsigned(16#00000000#, 32);
      payloadReg_src1Addr <= to_unsigned(16#00000000#, 32);
      payloadReg_dstAddr <= to_unsigned(16#00000000#, 32);
      payloadReg_exponent <= to_signed(16#00#, 8);
      payloadReg_exponentIn1 <= to_signed(16#00#, 8);
      payloadReg_exponentIn2 <= to_signed(16#00#, 8);
      payloadReg_reluValue <= to_unsigned(16#00000000#, 32);
      payloadReg_reluScaleExp <= to_signed(16#00#, 8);
      payloadReg_single2Int8Exp <= to_signed(16#00#, 8);
      payloadReg_int82SingleExp <= to_signed(16#00#, 8);
      inputAddrOffsetReg <= to_unsigned(16#00000000#, 32);
      outputAddrOffsetReg <= to_unsigned(16#00000000#, 32);
      outputAddrOffsetPrevReg <= to_unsigned(16#00000000#, 32);
      outputTotalLSBsReg <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        topReg_cmd <= topReg_cmd_next;
        topReg_src0 <= topReg_src0_next;
        topReg_src1 <= topReg_src1_next;
        topReg_dst0 <= topReg_dst0_next;
        topReg_src0Mode <= topReg_src0Mode_next;
        topReg_src1Mode <= topReg_src1Mode_next;
        topReg_dst0Mode <= topReg_dst0Mode_next;
        topReg_epoch <= topReg_epoch_next;
        payloadReg_src0Addr <= payloadReg_src0Addr_next;
        payloadReg_src1Addr <= payloadReg_src1Addr_next;
        payloadReg_dstAddr <= payloadReg_dstAddr_next;
        payloadReg_exponent <= payloadReg_exponent_next;
        payloadReg_exponentIn1 <= payloadReg_exponentIn1_next;
        payloadReg_exponentIn2 <= payloadReg_exponentIn2_next;
        payloadReg_reluValue <= payloadReg_reluValue_next;
        payloadReg_reluScaleExp <= payloadReg_reluScaleExp_next;
        payloadReg_single2Int8Exp <= payloadReg_single2Int8Exp_next;
        payloadReg_int82SingleExp <= payloadReg_int82SingleExp_next;
        inputAddrOffsetReg <= inputAddrOffsetReg_next;
        outputAddrOffsetReg <= outputAddrOffsetReg_next;
        outputAddrOffsetPrevReg <= outputAddrOffsetPrevReg_next;
        outputTotalLSBsReg <= outputTotalLSBsReg_next;
      END IF;
    END IF;
  END PROCESS createPayload_process;

  createPayload_output : PROCESS (inputAddrOffsetIn_unsigned, inputAddrOffsetReg, outputAddrOffsetIn_unsigned,
       outputAddrOffsetPrevIn_unsigned, outputAddrOffsetPrevReg,
       outputAddrOffsetReg, outputTotalLSBsIn_unsigned, outputTotalLSBsReg,
       payloadIn_dstAddr_unsigned, payloadIn_exponentIn1_signed,
       payloadIn_exponentIn2_signed, payloadIn_exponent_signed,
       payloadIn_int82SingleExp_signed, payloadIn_reluScaleExp_signed,
       payloadIn_reluValue_unsigned, payloadIn_single2Int8Exp_signed,
       payloadIn_src0Addr_unsigned, payloadIn_src1Addr_unsigned,
       payloadReg_dstAddr, payloadReg_exponent, payloadReg_exponentIn1,
       payloadReg_exponentIn2, payloadReg_int82SingleExp,
       payloadReg_reluScaleExp, payloadReg_reluValue, payloadReg_single2Int8Exp,
       payloadReg_src0Addr, payloadReg_src1Addr, state_unsigned, topReg_cmd,
       topReg_dst0, topReg_dst0Mode, topReg_epoch, topReg_src0, topReg_src0Mode,
       topReg_src1, topReg_src1Mode, topValid, top_cmd, top_dst0Mode,
       top_dst0_unsigned, top_epoch_unsigned, top_src0Mode, top_src0_unsigned,
       top_src1Mode, top_src1_unsigned)
    VARIABLE epochLSBs : unsigned(3 DOWNTO 0);
    VARIABLE r_src0Addr : unsigned(31 DOWNTO 0);
    VARIABLE r_src1Addr : unsigned(31 DOWNTO 0);
    VARIABLE r_dstAddr : unsigned(31 DOWNTO 0);
    VARIABLE hasOutputIncrement : std_logic;
    VARIABLE wait_rsvd : std_logic;
    VARIABLE add_temp : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_1 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_2 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_3 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_4 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_5 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_6 : unsigned(32 DOWNTO 0);
    VARIABLE add_temp_7 : unsigned(32 DOWNTO 0);
  BEGIN
    r_src0Addr := to_unsigned(16#00000000#, 32);
    r_src1Addr := to_unsigned(16#00000000#, 32);
    r_dstAddr := to_unsigned(16#00000000#, 32);
    add_temp := to_unsigned(0, 33);
    add_temp_0 := to_unsigned(0, 33);
    add_temp_1 := to_unsigned(0, 33);
    add_temp_2 := to_unsigned(0, 33);
    add_temp_3 := to_unsigned(0, 33);
    add_temp_4 := to_unsigned(0, 33);
    add_temp_5 := to_unsigned(0, 33);
    add_temp_6 := to_unsigned(0, 33);
    add_temp_7 := to_unsigned(0, 33);
    topReg_cmd_next <= topReg_cmd;
    topReg_src0_next <= topReg_src0;
    topReg_src1_next <= topReg_src1;
    topReg_dst0_next <= topReg_dst0;
    topReg_src0Mode_next <= topReg_src0Mode;
    topReg_src1Mode_next <= topReg_src1Mode;
    topReg_dst0Mode_next <= topReg_dst0Mode;
    topReg_epoch_next <= topReg_epoch;
    payloadReg_src0Addr_next <= payloadReg_src0Addr;
    payloadReg_src1Addr_next <= payloadReg_src1Addr;
    payloadReg_dstAddr_next <= payloadReg_dstAddr;
    payloadReg_exponent_next <= payloadReg_exponent;
    payloadReg_exponentIn1_next <= payloadReg_exponentIn1;
    payloadReg_exponentIn2_next <= payloadReg_exponentIn2;
    payloadReg_reluValue_next <= payloadReg_reluValue;
    payloadReg_reluScaleExp_next <= payloadReg_reluScaleExp;
    payloadReg_single2Int8Exp_next <= payloadReg_single2Int8Exp;
    payloadReg_int82SingleExp_next <= payloadReg_int82SingleExp;
    topDeq <= '0';
    advance <= '0';
    toIdle <= '0';
    valid <= '0';
    inputAddrOffsetReg_next <= inputAddrOffsetIn_unsigned;
    outputAddrOffsetReg_next <= outputAddrOffsetIn_unsigned;
    outputAddrOffsetPrevReg_next <= outputAddrOffsetPrevIn_unsigned;
    outputTotalLSBsReg_next <= outputTotalLSBsIn_unsigned;
    -- If we need to increment an output address wait until the
    -- outputAddrOffset is up-to-date
    epochLSBs := top_epoch_unsigned(3 DOWNTO 0);
    hasOutputIncrement := hdlcoder_to_stdlogic(((top_src0Mode = IncrementOutput) OR (top_src1Mode = IncrementOutput)) OR (top_dst0Mode = IncrementOutput));
    wait_rsvd := hasOutputIncrement AND hdlcoder_to_stdlogic(epochLSBs /= outputTotalLSBsReg);
    CASE state_unsigned IS
      WHEN "00000000" =>
        IF (topValid AND ( NOT wait_rsvd)) = '1' THEN 
          advance <= '1';
          topReg_cmd_next <= top_cmd;
          topReg_src0_next <= top_src0_unsigned;
          topReg_src1_next <= top_src1_unsigned;
          topReg_dst0_next <= top_dst0_unsigned;
          topReg_src0Mode_next <= top_src0Mode;
          topReg_src1Mode_next <= top_src1Mode;
          topReg_dst0Mode_next <= top_dst0Mode;
          topReg_epoch_next <= top_epoch_unsigned;
          topDeq <= '1';
          r_src0Addr := payloadIn_src0Addr_unsigned;
          r_src1Addr := payloadIn_src1Addr_unsigned;
          r_dstAddr := payloadIn_dstAddr_unsigned;
          --            %% conditions based on epayload are statically known so hopefully added
          --            %% regs/logic for streaming should be omitted if not needed.
          IF top_src0Mode = IncrementInput THEN 
            add_temp := resize(payloadIn_src0Addr_unsigned, 33) + resize(inputAddrOffsetReg, 33);
            IF add_temp(32) /= '0' THEN 
              r_src0Addr := X"FFFFFFFF";
            ELSE 
              r_src0Addr := add_temp(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_src0Mode = IncrementOutput THEN 
            add_temp_0 := resize(r_src0Addr, 33) + resize(outputAddrOffsetReg, 33);
            IF add_temp_0(32) /= '0' THEN 
              r_src0Addr := X"FFFFFFFF";
            ELSE 
              r_src0Addr := add_temp_0(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_src0Mode = IncrementOutputPrev THEN 
            add_temp_1 := resize(r_src0Addr, 33) + resize(outputAddrOffsetPrevReg, 33);
            IF add_temp_1(32) /= '0' THEN 
              r_src0Addr := X"FFFFFFFF";
            ELSE 
              r_src0Addr := add_temp_1(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_src1Mode = IncrementInput THEN 
            add_temp_2 := resize(payloadIn_src1Addr_unsigned, 33) + resize(inputAddrOffsetReg, 33);
            IF add_temp_2(32) /= '0' THEN 
              r_src1Addr := X"FFFFFFFF";
            ELSE 
              r_src1Addr := add_temp_2(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_src1Mode = IncrementOutput THEN 
            add_temp_3 := resize(r_src1Addr, 33) + resize(outputAddrOffsetReg, 33);
            IF add_temp_3(32) /= '0' THEN 
              r_src1Addr := X"FFFFFFFF";
            ELSE 
              r_src1Addr := add_temp_3(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_src1Mode = IncrementOutputPrev THEN 
            add_temp_4 := resize(r_src1Addr, 33) + resize(outputAddrOffsetPrevReg, 33);
            IF add_temp_4(32) /= '0' THEN 
              r_src1Addr := X"FFFFFFFF";
            ELSE 
              r_src1Addr := add_temp_4(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_dst0Mode = IncrementInput THEN 
            add_temp_5 := resize(payloadIn_dstAddr_unsigned, 33) + resize(inputAddrOffsetReg, 33);
            IF add_temp_5(32) /= '0' THEN 
              r_dstAddr := X"FFFFFFFF";
            ELSE 
              r_dstAddr := add_temp_5(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_dst0Mode = IncrementOutput THEN 
            add_temp_6 := resize(r_dstAddr, 33) + resize(outputAddrOffsetReg, 33);
            IF add_temp_6(32) /= '0' THEN 
              r_dstAddr := X"FFFFFFFF";
            ELSE 
              r_dstAddr := add_temp_6(31 DOWNTO 0);
            END IF;
          END IF;
          IF top_dst0Mode = IncrementOutputPrev THEN 
            add_temp_7 := resize(r_dstAddr, 33) + resize(outputAddrOffsetPrevReg, 33);
            IF add_temp_7(32) /= '0' THEN 
              r_dstAddr := X"FFFFFFFF";
            ELSE 
              r_dstAddr := add_temp_7(31 DOWNTO 0);
            END IF;
          END IF;
          payloadReg_src0Addr_next <= r_src0Addr;
          payloadReg_src1Addr_next <= r_src1Addr;
          payloadReg_dstAddr_next <= r_dstAddr;
          payloadReg_exponent_next <= payloadIn_exponent_signed;
          payloadReg_exponentIn1_next <= payloadIn_exponentIn1_signed;
          payloadReg_exponentIn2_next <= payloadIn_exponentIn2_signed;
          payloadReg_reluValue_next <= payloadIn_reluValue_unsigned;
          payloadReg_reluScaleExp_next <= payloadIn_reluScaleExp_signed;
          payloadReg_single2Int8Exp_next <= payloadIn_single2Int8Exp_signed;
          payloadReg_int82SingleExp_next <= payloadIn_int82SingleExp_signed;
        END IF;
      WHEN "00000001" =>
        valid <= '1';
      WHEN "00000010" =>
        toIdle <= '1';
      WHEN OTHERS => 
        NULL;
    END CASE;
    instr_cmd <= topReg_cmd;
    instr_src0_tmp <= topReg_src0;
    instr_src1_tmp <= topReg_src1;
    instr_dst0_tmp <= topReg_dst0;
    instr_src0Mode <= topReg_src0Mode;
    instr_src1Mode <= topReg_src1Mode;
    instr_dst0Mode <= topReg_dst0Mode;
    instr_epoch_tmp <= topReg_epoch;
    payload_src0Addr_tmp <= payloadReg_src0Addr;
    payload_src1Addr_tmp <= payloadReg_src1Addr;
    payload_dstAddr_tmp <= payloadReg_dstAddr;
    payload_exponent_tmp <= payloadReg_exponent;
    payload_exponentIn1_tmp <= payloadReg_exponentIn1;
    payload_exponentIn2_tmp <= payloadReg_exponentIn2;
    payload_reluValue_tmp <= payloadReg_reluValue;
    payload_reluScaleExp_tmp <= payloadReg_reluScaleExp;
    payload_single2Int8Exp_tmp <= payloadReg_single2Int8Exp;
    payload_int82SingleExp_tmp <= payloadReg_int82SingleExp;
  END PROCESS createPayload_output;


  instr_src0 <= std_logic_vector(instr_src0_tmp);

  instr_src1 <= std_logic_vector(instr_src1_tmp);

  instr_dst0 <= std_logic_vector(instr_dst0_tmp);

  instr_epoch <= std_logic_vector(instr_epoch_tmp);

  payload_src0Addr <= std_logic_vector(payload_src0Addr_tmp);

  payload_src1Addr <= std_logic_vector(payload_src1Addr_tmp);

  payload_dstAddr <= std_logic_vector(payload_dstAddr_tmp);

  payload_exponent <= std_logic_vector(payload_exponent_tmp);

  payload_exponentIn1 <= std_logic_vector(payload_exponentIn1_tmp);

  payload_exponentIn2 <= std_logic_vector(payload_exponentIn2_tmp);

  payload_reluValue <= std_logic_vector(payload_reluValue_tmp);

  payload_reluScaleExp <= std_logic_vector(payload_reluScaleExp_tmp);

  payload_single2Int8Exp <= std_logic_vector(payload_single2Int8Exp_tmp);

  payload_int82SingleExp <= std_logic_vector(payload_int82SingleExp_tmp);

END rtl;

