-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_payloadSend_block1.vhd
-- Created: 2025-10-22 15:46:36
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_payloadSend_block1
-- Source Path: testbench/DUT/DUT/Scheduler/Scheduler/Input_InstructionStack  /Subsystem Reference1/Subsystem Reference1/payloadSend
-- Hierarchy Level: 7
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_payloadSend_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enq                               :   IN    std_logic;
        dIn_addr                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_sizeInBytes                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_id                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dIn_frameNumber                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dIn_isFirst                       :   IN    std_logic;
        DEQ                               :   IN    std_logic;
        DOUT_addr                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        DOUT_sizeInBytes                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        DOUT_id                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        DOUT_frameNumber                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        DOUT_isFirst                      :   OUT   std_logic;
        VALID                             :   OUT   std_logic;
        notFull                           :   OUT   std_logic
        );
END MyProc_src_payloadSend_block1;


ARCHITECTURE rtl OF MyProc_src_payloadSend_block1 IS

  -- Component Declarations
  COMPONENT MyProc_src_FIFO_block8
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enq                             :   IN    std_logic;
          dIn_addr                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_sizeInBytes                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_id                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          dIn_frameNumber                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dIn_isFirst                     :   IN    std_logic;
          deq                             :   IN    std_logic;
          dOut_addr                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dOut_sizeInBytes                :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dOut_id                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          dOut_frameNumber                :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dOut_isFirst                    :   OUT   std_logic;
          notEmpty                        :   OUT   std_logic;
          notFull                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MyProc_src_FIFO_block8
    USE ENTITY work.MyProc_src_FIFO_block8(rtl);

  -- Signals
  SIGNAL FIFO_out1_addr                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL FIFO_out1_sizeInBytes            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL FIFO_out1_id                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL FIFO_out1_frameNumber            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL FIFO_out1_isFirst                : std_logic;
  SIGNAL FIFO_out2                        : std_logic;
  SIGNAL FIFO_out3                        : std_logic;

BEGIN
  u_FIFO : MyProc_src_FIFO_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enq => enq,
              dIn_addr => dIn_addr,  -- uint32
              dIn_sizeInBytes => dIn_sizeInBytes,  -- uint32
              dIn_id => dIn_id,  -- uint8
              dIn_frameNumber => dIn_frameNumber,  -- uint32
              dIn_isFirst => dIn_isFirst,
              deq => DEQ,
              dOut_addr => FIFO_out1_addr,  -- uint32
              dOut_sizeInBytes => FIFO_out1_sizeInBytes,  -- uint32
              dOut_id => FIFO_out1_id,  -- uint8
              dOut_frameNumber => FIFO_out1_frameNumber,  -- uint32
              dOut_isFirst => FIFO_out1_isFirst,
              notEmpty => FIFO_out2,
              notFull => FIFO_out3
              );

  DOUT_isFirst <= FIFO_out1_isFirst;

  VALID <= FIFO_out2;

  notFull <= FIFO_out3;

  DOUT_addr <= FIFO_out1_addr;

  DOUT_sizeInBytes <= FIFO_out1_sizeInBytes;

  DOUT_id <= FIFO_out1_id;

  DOUT_frameNumber <= FIFO_out1_frameNumber;

END rtl;

