-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_Subsystem_block35.vhd
-- Created: 2025-10-22 15:46:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_Subsystem_block35
-- Source Path: testbench/DUT/DUT/Subsystem/CNN5_debug1/DebugableDelay1/DebugDecoder/Subsystem
-- Hierarchy Level: 6
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_Subsystem_block35 IS
  PORT( In1                               :   IN    std_logic;
        In2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        In3                               :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        In4                               :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Out2                              :   OUT   std_logic;  -- ufix1
        Out3                              :   OUT   std_logic;
        Out4                              :   OUT   std_logic  -- ufix1
        );
END MyProc_src_Subsystem_block35;


ARCHITECTURE rtl OF MyProc_src_Subsystem_block35 IS

  -- Signals
  SIGNAL wr_din                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL wr_addr                          : std_logic;  -- ufix1
  SIGNAL wr_en                            : std_logic;
  SIGNAL rd_addr                          : std_logic;  -- ufix1

BEGIN
  wr_din <= In2;

  Out1 <= wr_din;

  wr_addr <= '0';

  Out2 <= wr_addr;

  wr_en <= In1;

  Out3 <= wr_en;

  rd_addr <= '0';

  Out4 <= rd_addr;

END rtl;

