-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DataTypeConv1_block2.vhd
-- Created: 2025-10-22 15:46:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DataTypeConv1_block2
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/DataMemMask/DataMem/zAddapter/DataTypeConv1
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_DataTypeConv1_block2 IS
  PORT( InData                            :   IN    vector_of_std_logic_vector32(0 TO 17);  -- uint32 [18]
        OutData                           :   OUT   vector_of_std_logic_vector32(0 TO 17)  -- int32 [18]
        );
END MyProc_src_DataTypeConv1_block2;


ARCHITECTURE rtl OF MyProc_src_DataTypeConv1_block2 IS

  -- Signals
  SIGNAL InData_unsigned                  : vector_of_unsigned32(0 TO 17);  -- uint32 [18]
  SIGNAL DTC_out1                         : vector_of_signed32(0 TO 17);  -- int32 [18]

BEGIN
  outputgen1: FOR k IN 0 TO 17 GENERATE
    InData_unsigned(k) <= unsigned(InData(k));
  END GENERATE;


  DTC_out1_gen: FOR ii IN 0 TO 17 GENERATE
    DTC_out1(ii) <= signed(InData_unsigned(ii));
  END GENERATE DTC_out1_gen;


  outputgen: FOR k IN 0 TO 17 GENERATE
    OutData(k) <= std_logic_vector(DTC_out1(k));
  END GENERATE;

END rtl;

