-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_From4_block10.vhd
-- Created: 2025-10-22 15:46:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_From4_block10
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/ConvEngine/CONV/CONV_Compute/Convolver/Subsystem2/ConvXDc/Conv/PEc2/From4
-- Hierarchy Level: 12
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MyProc_src_DUT_pkg.ALL;

ENTITY MyProc_src_From4_block10 IS
  PORT( CONV_IndexTag                     :   IN    vector_of_std_logic_vector17(0 TO 8);  -- ufix17 [9]
        Out1                              :   OUT   vector_of_std_logic_vector17(0 TO 8)  -- ufix17 [9]
        );
END MyProc_src_From4_block10;


ARCHITECTURE rtl OF MyProc_src_From4_block10 IS

BEGIN
  Out1 <= CONV_IndexTag;

END rtl;

