-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_DataTypeConv_block2.vhd
-- Created: 2025-10-22 15:46:42
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_DataTypeConv_block2
-- Source Path: testbench/DUT/DUT/FC Kernel/Real FC Kernel/FCEngine/FCDUT/FCUnit/DataMemSingleCycleAccumulator/WrBusMatrix1/DataTypeConv
-- Hierarchy Level: 9
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_DataTypeConv_block2 IS
  PORT( InData                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        OutData                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
        );
END MyProc_src_DataTypeConv_block2;


ARCHITECTURE rtl OF MyProc_src_DataTypeConv_block2 IS

  -- Signals
  SIGNAL InData_unsigned                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL DTC_out1                         : signed(31 DOWNTO 0);  -- int32

BEGIN
  InData_unsigned <= unsigned(InData);

  DTC_out1 <= signed(InData_unsigned);

  OutData <= std_logic_vector(DTC_out1);

END rtl;

