-- -------------------------------------------------------------
-- 
-- File Name: customProc\hdlsrc\testbench\MyProc_src_central_state_machine.vhd
-- Created: 2025-10-22 15:46:43
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MyProc_src_central_state_machine
-- Source Path: testbench/DUT/DUT/Conv Module/Real Conv Kernel/central_state_machine
-- Hierarchy Level: 4
-- Model version: 8.28
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MyProc_src_central_state_machine IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        payLoadValid                      :   IN    std_logic;
        done                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        canSendDone                       :   IN    std_logic;
        startIP                           :   OUT   std_logic;
        startConv                         :   OUT   std_logic;
        startOP                           :   OUT   std_logic;
        sendDone                          :   OUT   std_logic;
        deque                             :   OUT   std_logic;
        reset_1                           :   OUT   std_logic;
        stateOut                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        longReset                         :   OUT   std_logic
        );
END MyProc_src_central_state_machine;


ARCHITECTURE rtl OF MyProc_src_central_state_machine IS

  -- Signals
  SIGNAL done_unsigned                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL reset_2                          : std_logic;
  SIGNAL stateOutdeadOut                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL longResetdeadOut                 : std_logic;
  SIGNAL state                            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL resetCountReg                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL state_next                       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL resetCountReg_next               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL stateOut_tmp                     : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  done_unsigned <= unsigned(done);

  dnnfpgaConv5Module_c71_central_state_machine_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      state <= to_unsigned(16#0#, 4);
      resetCountReg <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        state <= state_next;
        resetCountReg <= resetCountReg_next;
      END IF;
    END IF;
  END PROCESS dnnfpgaConv5Module_c71_central_state_machine_process;

  dnnfpgaConv5Module_c71_central_state_machine_output : PROCESS (canSendDone, done_unsigned, payLoadValid, resetCountReg, state)
    VARIABLE reset1 : std_logic;
    VARIABLE longReset1 : std_logic;
    VARIABLE payloadV : std_logic;
    VARIABLE add_temp : unsigned(8 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#000#, 9);
    resetCountReg_next <= resetCountReg;
    -- state difinition
    -- State Memory Encoding
    IF resetCountReg >= to_unsigned(16#00000020#, 8) THEN 
      longReset1 := '1';
    ELSE 
      longReset1 := '0';
    END IF;
    payloadV := payLoadValid AND longReset1;
    -- output
    -- state definition
    CASE state IS
      WHEN "0000" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= '0';
        reset1 := '0';
      WHEN "0001" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= '0';
        reset1 := '1';
      WHEN "0010" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= payloadV;
        reset1 := '1';
      WHEN "0011" =>
        startIP <= '1';
        startConv <= '1';
        startOP <= '1';
        sendDone <= '0';
        deque <= '0';
        reset1 := '0';
      WHEN "0100" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= '0';
        reset1 := '0';
      WHEN "0101" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= canSendDone;
        deque <= '0';
        reset1 := '1';
      WHEN "0110" =>
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= payloadV;
        reset1 := '1';
      WHEN OTHERS => 
        startIP <= '0';
        startConv <= '0';
        startOP <= '0';
        sendDone <= '0';
        deque <= '0';
        reset1 := '0';
    END CASE;
    -- next state transition
    CASE state IS
      WHEN "0000" =>
        IF done_unsigned = to_unsigned(16#00000007#, 32) THEN 
          state_next <= to_unsigned(16#1#, 4);
        ELSE 
          state_next <= to_unsigned(16#0#, 4);
        END IF;
      WHEN "0001" =>
        state_next <= to_unsigned(16#2#, 4);
      WHEN "0010" =>
        IF payloadV = '1' THEN 
          state_next <= to_unsigned(16#3#, 4);
        ELSE 
          state_next <= to_unsigned(16#2#, 4);
        END IF;
      WHEN "0011" =>
        state_next <= to_unsigned(16#4#, 4);
      WHEN "0100" =>
        IF done_unsigned = to_unsigned(16#00000007#, 32) THEN 
          state_next <= to_unsigned(16#5#, 4);
        ELSE 
          state_next <= to_unsigned(16#4#, 4);
        END IF;
      WHEN "0101" =>
        IF canSendDone = '1' THEN 
          state_next <= to_unsigned(16#6#, 4);
        ELSE 
          state_next <= to_unsigned(16#5#, 4);
        END IF;
      WHEN "0110" =>
        IF payloadV = '1' THEN 
          state_next <= to_unsigned(16#3#, 4);
        ELSE 
          state_next <= to_unsigned(16#6#, 4);
        END IF;
      WHEN OTHERS => 
        state_next <= to_unsigned(16#0#, 4);
    END CASE;
    IF reset1 = '1' THEN 
      IF resetCountReg /= to_unsigned(16#000000FF#, 8) THEN 
        add_temp := resize(resetCountReg, 9) + to_unsigned(16#001#, 9);
        IF add_temp(8) /= '0' THEN 
          resetCountReg_next <= "11111111";
        ELSE 
          resetCountReg_next <= add_temp(7 DOWNTO 0);
        END IF;
      END IF;
    ELSE 
      resetCountReg_next <= to_unsigned(16#00#, 8);
    END IF;
    reset_2 <= reset1;
    stateOutdeadOut <= state;
    longResetdeadOut <= longReset1;
  END PROCESS dnnfpgaConv5Module_c71_central_state_machine_output;


  stateOut_tmp <= to_unsigned(16#0#, 4);

  stateOut <= std_logic_vector(stateOut_tmp);

  longReset <= '0';

  reset_1 <= reset_2;

END rtl;

